### ISSUE TITLE
Preload feature is broken in v1.1.0

### ISSUE THREAD

**Issue by chk-** [node-inspector/node-inspector#1004]
Windows 10, node v6.10.2, node-inspector v1.1.0
The preload feature is not working any more.
I started node-inspector without parameters.
After reverting to v1.0.0, node-inspector does preloading.

**Comment by hustxiaoc** [comment]
HI, could  you post some more detail information ? Any error log ?

**Comment by chk-** [comment]
Hi hustxiaoc,
no error is thrown.
1.) I start node-inspector, which is listening with the default settings.
2.) I start my project with node --debug-brk startpoint.js
3.) I connect to node-inspector with google chrome browser.

@v1.0.0 all *.js project files get loaded and show up in the left sides project/files tree, while
@v1.1.0 only the startingpoint js file is present and the project/files tree gets filled with js files linked one after the other, as soon as I release the breakpoint.

**Comment by chk-** [comment]
With version 1.1.1 this issue is gone, the preload feature works as expected! 
I am wondering why, I couldn't find any hint for a fix.
