### ISSUE TITLE
If i press enter in console it does nothing

### ISSUE THREAD

**Issue by ivantot2** [node-inspector/node-inspector#1005]
whenever i press enter in node inspector it just does nothing.
not even a new line.
it just erases what i have written and nothing.

chrome version: 58.0.3029.81 (64-bit)
node-inspector: 1.1.0
node: 6.3.0

**Comment by hustxiaoc** [comment]
Thanks for reporting, I'll fix it ASAP.

**Comment by hustxiaoc** [comment]
Fixed in `node-inspector@1.1.1`
