### ISSUE TITLE
Node-inspector stepping not working

### ISSUE THREAD

**Issue by dheitzer** [node-inspector/node-inspector#1008]
Hi, I'm having an issue with node inspector where the stepping functions are not working properly.  When I use "step over" or "step in", the debugger often proceeds until the next breakpoint (or the end if there is no breakpoint) just like I have pressed "Resume script execution".  

This behavior is happening consistently, but not always at the same time.  For example, I start debugging and the debugger will step correctly for the first 3-10 lines of script, and then will proceed to the end.  The point at which the stepping fails seems to have more to do with timing than a spot in the script.

My setup is very current:
Node: 6.10.2
Node Inspector: 1.1.1

I have tried in Opera (won't open the GUI), Chrome, and Chromium and all do the same thing.

Thanks,
D

**Comment by hustxiaoc** [comment]
Thanks for your report, I'll figure it out ASAP.

**Comment by dheitzer** [comment]
Thanks a lot.

**Comment by hustxiaoc** [comment]
@dheitzer , could you please give some specific steps on how to reproduce this issue ? Like how did you launch your program with Node Inspector.

**Comment by dheitzer** [comment]
Hi, sure thing I can.  I am launching it from Ubuntu using node-debug <jsfile>command.  

Here's a .gif demoing the issue.  

![node-debug demo](https://cloud.githubusercontent.com/assets/16611111/26251442/409a1434-3c7b-11e7-923e-298f70b7af47.gif)

Do let me know if I can provide any more info.

Thanks,

D

**Comment by hustxiaoc** [comment]
Turns out it has something to do with `console.log`, you can set a breakpoint after console.log by now.

**Comment by dheitzer** [comment]
@hustxiaoc Ah, very good info, thanks for the help.  Stepping seem to work fine outside of console.log statements.  

Thanks,

D
