### ISSUE TITLE
Heap snapshots not longer loading

### ISSUE THREAD

**Issue by jfromaniello** [node-inspector/node-inspector#1012]
I am not sure if something changed but I can't load `heapsnapshots` files anymore. It was working fine last week.

So far I tried on `Chrome Version 59.0.3071.115` and `Chromiun Version 61.0.3149.0 (Developer Build) (64-bit)`

I see this error in the console:

```
WorkerRuntime.js:138 Uncaught (in promise) DOMException: Failed to construct 'Worker': Access to the script at 'blob:http://127.0.0.1:8080/5a81f659-934c-434a-9d36-f6b4f54acc57' is denied by the document's Content Security Policy.
```

**Comment by jfromaniello** [comment]
Works fine on `Chrome Version 57.0.2987.133` on the same machine.

**Comment by dillonkrug** [comment]
I also had this issue and can confirm that the pull request fixes it.

**Comment by andrew8er** [comment]
I guess that Chrome tightened the default content security policy between 57 and 59.
