### ISSUE TITLE
not found file https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz

### ISSUE THREAD

**Issue by sanchezzzhak** [node-inspector/node-inspector#1031]
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>debug/v1.0.1/node-v57-win32-x64.tar.gz</Key>
<RequestId>60422E2FE58F1918</RequestId>
<HostId>
oZAFxY2/sLrp3mSFgI5URhiePdU7RN0FlInY7U4xoOgYf3vv0y4k42MFM3V+t+0bvL86c4z9UIk=
</HostId>
</Error>
```

**Comment by hemith** [comment]
macOS too.

npm install -g node-inspector

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.9.3 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by whusl** [comment]
node-inspector do not support node v8 debug api,  you can get the latest method from [my blog](www.ddkiss.com/archives/106.html)

**Comment by aminshoman** [comment]
Node 8 brings a big break change in the debug api which is too difficult to implement in Node Inspector. Besides it provides a built-in DevTools-based debugger which mostly deprecates Node Inspector. So basically you can just use the built-in debugger tools. https://nodejs.org/en/docs/inspector/

you can get use the same results by running the --inspector option

`$ node --inspect server.js
`

**Comment by RocGit** [comment]
`npm install -g node-inspector@0.7.5`  maybe ok

**Comment by wangyapeng** [comment]
ou.it's confused

**Comment by sanchezzzhak** [comment]
reason close: I closed this issue because I don't see the error anymore. if you encounter an error, create a new issue.
