### ISSUE TITLE
Chrome Devtools collapse, won't display code

### ISSUE THREAD

**Issue by sedge** [node-inspector/node-inspector#1033]
Node version: `v4.3.1`
Node-inspector version: `v0.12.10`

I run my app with --debug, and on connecting in the browser at a breakpoint this is what I see:
![screen shot 2018-01-10 at 12 17 41 pm](https://user-images.githubusercontent.com/1616860/34785827-4c4bf98e-f600-11e7-9641-5c6c21922507.png)

Any idea what could be going wrong? I can't upgrade to a newer node version, and it's worth noting that this is the first time I've ever seen this.

**Comment by jaredmcateer** [comment]
Duplicate of https://github.com/node-inspector/node-inspector/issues/1028

There are some workarounds mentioned in there.

**Comment by sedge** [comment]
@jaredmcateer 🙏

**Comment by hustxiaoc** [comment]
fixed https://github.com/node-inspector/node-inspector/pull/1034
