### ISSUE TITLE
Console does not print objects while breakpoint is not hit

### ISSUE THREAD

**Issue by nvlbg** [node-inspector/node-inspector#146]
First, sorry for my bad english. Basically, if I'm on a breakpoint and, for example, type global in the console, the whole global object is shown, and I can see its properties. However, if the script isn't paused (no breakpoint), props of objects does not appear, but ints and strings for example does appear.

**Comment by eplawless** [comment]
It looks like this still isn't resolved, is there a plan to eventually tackle this?
