### ISSUE TITLE
Break on Exception

### ISSUE THREAD

**Issue by soitgoes** [node-inspector/node-inspector#16]
I haven't been able to find a way to break on exeception.  Is this a feature or in the roadmap?

**Comment by rainabba** [comment]
How do we use this feature? I see reference to setPauseOnExceptions and the enums, but not how to set this (environment, command-line, in the debugger interface, etc).

**Comment by derwaldgeist** [comment]
I am also looking for a way to enable this feature. Where can I find it?

**Comment by rainabba** [comment]
You likely won't care once you're setup with the following (assuming you're using a new enough version of node to have this as an option): https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27
