### ISSUE TITLE
Bind to other than 127.0.0.1 address

### ISSUE THREAD

**Issue by ArtS** [node-inspector/node-inspector#17]
Hi,

is it possible to add an extra parameter like

--web-ip 

so one can specify other than 127.0.0.1 IPs?

Thanks

**Comment by bradisbell** [comment]
For anyone else looking for an updated answer on this, it seems that the default is now `127.0.0.1` (and the parameter is named `--web-host`).  The documentation is ambiguous, as noted here:  https://github.com/node-inspector/node-inspector/issues/852
