### ISSUE TITLE
Failed to open socket on port 5858, waiting 1000 ms before retrying

### ISSUE THREAD

**Issue by vjsrinath** [node-inspector/node-inspector#199]
![screenshot from 2013-08-18 16 31 13](https://f.cloud.github.com/assets/5001683/982475/bbf1b240-07f5-11e3-83e9-7b7ba2776980.png)
![screenshot from 2013-08-18 16 31 33](https://f.cloud.github.com/assets/5001683/982476/bc20131a-07f5-11e3-9c88-f5af80f2807b.png)
![screenshot from 2013-08-18 16 32 37](https://f.cloud.github.com/assets/5001683/982477/bc4cfab0-07f5-11e3-962b-f32def07d36b.png)

I am not able to launch the debugging in ubuntu 12.04. 
When "netstat -l" command issued before launching app in debug mode, i don't see port 5858 is opened
But once after launching the application in debug mode, I do see the socket listening on port 5858 but in console it says "Failed to open socket on port 5858, waiting 1000 ms before retrying"
When "http://127.0.0.1:8080/debug?port=5858" opened it shows the js files but breakpoint never hits.

**Comment by andrewjmead** [comment]
I'm using `mocha --debug-brk` and was running into this issue. Killed the process and things seem to be working. :+1:

**Comment by kidsil** [comment]
Also using mocha, keep getting this when running `meteor debug` for long enough.

**Comment by HelloKevinTian** [comment]
I also got the error "Failed to open socket on port 5858, waiting 1000 ms before retrying" with my cluster model  app.      I run app with this  "node --debug app.js".  

my node version: v0.10.21
//=====================================
function start() {
    var cluster = require('cluster');
    var numCPUs = require('os').cpus().length;
    if (cluster.isMaster) {
        // Fork workers.
        for (var i = 0; i < numCPUs; i++) {
            cluster.fork();
        }

        cluster.on('exit', function(worker, code, signal) {
            console.log('worker ' + worker.process.pid + ' died');
        });
    } else {
            server.start();
    }
};

**Comment by bajtos** [comment]
> I also got the error "Failed to open socket on port 5858, waiting 1000 ms before retrying" with my cluster model app. I run app with this "node --debug app.js".
> my node version: v0.10.21

This is a known problem of Node v0.10, see the following blog post for more details (and a solution):
https://strongloop.com/strongblog/whats-new-nodejs-v0-12-debugging-clusters/
