### ISSUE TITLE
"hide" js source files from the inspector

### ISSUE THREAD

**Issue by saveriocastellano** [node-inspector/node-inspector#21]
hi Danny, 
is there a way to prevent some specific source files to be visible in the inspector?

If I have a file I want to debug, say hello.js, that in turns depends (via "require") on several "library" files, I would like to find a way so that the library files will be hidden by the user that is debugging. 
This feature is very useful if you want to create a scripting environment and you want users to be able to run and debug their scripts in the environment without being able to see the "core" libraries..

**Comment by zwhitchcox** [comment]
Sorry, but how do you hide the core modules?

**Comment by bajtos** [comment]
> @zwhitchcox how do you hide the core modules?

Please open a new issue to discuss that.
