### ISSUE TITLE
Feature request: Debugger: Please implement search in all source files

### ISSUE THREAD

**Issue by gabrielschulhof** [node-inspector/node-inspector#234]
When you debug an application with node version 0.10.20 and node-inspector 0.5.0, and you press Ctrl+Shift+F to search in all files, after entering the search string and pressing Enter, you get a string of errors such as the following:

```
Debugger.searchInContent failed.
Error: Not implemented.
Debugger.searchInContent failed.
Error: Not implemented.
...
Page.searchInResource failed.
Error: Not implemented.
Page.searchInResource failed.
Error: Not implemented.
...
```

The fact that the Debugger object is the one that does not implement the functions lead me to not be sure if this pertains to node-inspector or to node itself. I'll file an issue against node as well, in case node-inspector has its part implemented.

**Comment by francisbyrne** [comment]
I'd definitely find this useful.

**Comment by marcominetti** [comment]
Hi @bajtos, I can definitely implement it in my weekends. :+1:

**Comment by metaford** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

z.lee@navercorp.com 님께 보내신 메일 <Re: [node-inspector] Feature request: Debugger: Please implement search in all source files (#234)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by bajtos** [comment]
test

**Comment by yoshiokatsuneo** [comment]
@marcominetti Is this already implemented ? I'm getting the same error message.

**Comment by marcominetti** [comment]
@yoshiokatsuneo yep but it's not yet landed in master branch... You can try it from pr #621...

**Comment by yoshiokatsuneo** [comment]
@marcominetti Ah, I see. I'm looking forward to be merged to master.

**Comment by a7madgamal** [comment]
yesssss we need this!

**Comment by alex-georgiou** [comment]
Very useful feature. Please merge...

**Comment by johnreitano** [comment]
I definitely need this feature. Please merge!

**Comment by kristopolous** [comment]
I'll second this!
