### ISSUE TITLE
Failed to open socket on port 5858, waiting 1000 ms before retrying

### ISSUE THREAD

**Issue by awiss** [node-inspector/node-inspector#246]
Its surprising that I have not found a solution with many other similar issues. But all of the other threads were closed before any actual solution was found. Does anybody know why the line "Failed to open socket on port 5858, waiting 1000 ms before retrying" logs over and over when I run node --debug app.js?

**Comment by skozz** [comment]
In my case the same error was caused by nginx (running in background). `sudo nginx -s stop`
