### ISSUE TITLE
Error: connect ECONNREFUSED Is node running with --debug port 5858?

### ISSUE THREAD

**Issue by magwitch** [node-inspector/node-inspector#248]
Hello.
I'm brand new to node-inspector having downloaded it for the first time today.

I got version 0.6.1 which is running under node version 0.10.21.

Having followed the instructions (about 10 times now)
`node-inspector` gives me

```
Node Inspector v0.6.1
   info  - socket.io started
Visit http://127.0.0.1:8080/debug?port=5858 to start debugging.
```

I then ran: 

```
$ node --debug app.js 
debugger listening on port 5858
```

if I then open Chrome version 31.0.1650.57
I just get the error message

```
Error: connect ECONNREFUSED
Is node running with --debug port 5858?
```

I don't really know where to start here.
I've tried reversing the order for `node-inspector` and `--debug app.js`
I've tried killing all the processes and starting again.
I've tried `node-inspector --web-port={port}`  to run it under a a different port.
Same error message all the time.
Would someone mind pointing me in the right direction please.

**Comment by sadtaco** [comment]
I'm getting this problem with the latest version.

    sudo node-inspector && sudo node --debug --no-preload -p 9362
    Node Inspector v0.11.1
    Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
And in chrome I get this error:

    Request with id = 10 failed. "ErrorNotConnected: Error: connect ECONNREFUSED. Is node running with --debug port 5858?"

**Comment by sadtaco** [comment]
It's not letting me edit, but I wanted to add that just using "node-debug app.js" has the app running, but it doesn't seem reachable.  The app doesn't behave correctly (can't connect), and I can't access the inspector, getting ERR_CONNECTION_REFUSED

    sudo node-debug app.js
    Node Inspector is now available from http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
    Debugging `app.js`

    Debugger listening on port 5858

**Comment by Riturajcse** [comment]
Hey i am founding this error on my Node


D:\howrah>ionic start project1 sidemenu
Creating Ionic app in folder D:\howrah\project1 based on sidemenu project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error Initializing app:  Error: tunneling socket could not be established, cause
=connect ECONNREFUSED
    at ClientRequest.onError (C:\Users\riturajcse\AppData\Roaming\npm\node_modul
es\ionic\node_modules\request\node_modules\tunnel-agent\index.js:174:17)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

Error: tunneling socket could not be established, cause=connect ECONNREFUSED
    at ClientRequest.onError (C:\Users\riturajcse\AppData\Roaming\npm\node_modul
es\ionic\node_modules\request\node_modules\tunnel-agent\index.js:174:17)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

tunneling socket could not be established, cause=connect ECONNREFUSED (CLI v1.6.
4)

Your system information:

Cordova CLI: 5.2.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Windows 8
Node Version: v0.12.7

**Comment by praveenrawat** [comment]
start request failed { [Error: connect ECONNREFUSED] 

I found my firewall is blocking this to run. Can somebody tell me how to allow this through firewall?

its blocking my jasmine test to run,

**Comment by soujanyamypala** [comment]
I have the same problem can some help please..??

Thanks in Advance.

**Comment by soujanyamypala** [comment]
[npm-debug.zip](https://github.com/node-inspector/node-inspector/files/318064/npm-debug.zip)
