### ISSUE TITLE
node-inspector blank screen on windows

### ISSUE THREAD

**Issue by helmus** [node-inspector/node-inspector#343]
I can't seem to get node-inspector to work on windows
I'm trying to debug this script:

app.js

```
console.log('HELLO WORLD');

debugger;

console.log('HELLO DEBUGGER');
setInterval(function () {
    debugger;
    console.log('HELLO');
}, 10000);
```

I tried following things, with and without elevated permissions:

```
node-debug app.js
//
node-inspector 
node --debug-brk app.js
```

In any event, 
If I navigate in chrome to `http://localhost:8080/debug?port=5858`  
I  just get a blank screen with an empty toolbar above and a grey toolbar below.

If I look into the devtools, it seems like chrome is waiting for the websocket to establish, the `ws://localhost:8080/ws?port=5858` keeps 'pending'

Versions:

```
Windows 7 Pro x64
node-inspector v0.7.3
node v0.10.26
chrome 33.0.1750.154 m
chrome 36.0.1930.0 canary
```

I'm running chrome with `--disable-extensions` 

I can't seem to find any error logs, so I'm not sure where to go from here.
How I can fix / debug this ?

Copy from:
http://stackoverflow.com/questions/22932748/node-inspector-blank-screen-on-windows

**Comment by rochal** [comment]
Getting same issue. don't have any funky plugins installed...
