### ISSUE TITLE
MAC: node-debug should not open with default browser if it is Firefox

### ISSUE THREAD

**Issue by rick-kilgore** [node-inspector/node-inspector#346]
If the user has set Firefox as their "default" browser, then your use of opener in node-debug to open the browser is a bad choice, since node-inspector doesn't work in Firefox.  It should be smart enough to choose Safari instead, or better yet, check try running Chrome, and if that fails, then run Safari, and if that fails then print an error message saying it couldn't find and run Chrome or Safari.

**Comment by bajtos** [comment]
See #528 for a better implementation (in progress).
