### ISSUE TITLE
Is there any way to debug gulp's build process using node-inspector?

### ISSUE THREAD

**Issue by chicoxyzzy** [node-inspector/node-inspector#348]
I have a huge gulpfile with complex logic and gulp fails on some of watch tasks. Is there any way to debug gulp's build process using node-inspector?

**Comment by aroc** [comment]
@chicoxyzzy's solution works for me. Thanks for that!

**Comment by k-funk** [comment]
@chicoxyzzy's solution works for me as well, but unfortunately if I `ctrl-c` while the browser was still at a breakpoint, the gulp process will hang *forever* and I'll have to `ps aux | grep gulp` `kill <p_id>`
