### ISSUE TITLE
debugger crashes when adding breakpoint to javascript file with Chinese file name

### ISSUE THREAD

**Issue by shuai-zh** [node-inspector/node-inspector#373]
At first, I was trying to use JetBrains WebStorm to debug cucumber-js step definitions, however when I added a breakpoint on javascripts with Chinese file names, the debugger crashes.

I think the WebStorm utilizes node-inspector to debug node applications, so I tried directly call 'node-debug' to debug my tests. The node-inspector crashes too when I add the same breakpoint.

Because we use Chinese to define our cucumber features, in order to match the feature file names, we must use Chinese for our javascript file names as well.

I think that would be an encoding issue, can anyone help me with this?

Thanks.

**Comment by JimiHFord** [comment]
Is [this](https://www.jetbrains.com/webstorm/help/run-debug-configuration-cucumber-js.html) what you're looking for?
