### ISSUE TITLE
Can't evaluate values on console at breakpoint

### ISSUE THREAD

**Issue by dminkovsky** [node-inspector/node-inspector#374]
Long time user, first time issue poster. Thanks very much for this wonderful application.

Lately I've not been able to evaluate expressions on the console during a breakpoint. I've been aware of and understand similar-feeling `Buffer`-related issues for some time, but lately I've not been able to evaluate any expression at all. The problem is similar in feel to the `Buffer` slowness, except the expressions never turn up at all, yet are available for inspection by hovering over the symbol in the code and in `Scope Variables` on the right:

![screen shot 2014-05-17 at 2 52 43 pm](https://cloud.githubusercontent.com/assets/218725/3005822/07b34efc-ddf5-11e3-9223-c770487cca37.png)

You see evaluating `path` in this screenshot did not produce any results. It's a primitive `string`.

Not sure at all how to debug this or what information I could provide to assist. I tried downgrading with no luck (0.7.3 -> 0.7.2). Searched this issue tracker and Google with no results.

Thank you.

**Comment by Multigence** [comment]
I know this issue has been closed, but I'm experiencing the same on node-inspector@0.12.6

Also my bar seems pretty messed up. 

I'm using Chrome on OSX to reach Node-debug. Not sure if I should check/decheck some filter 

![screen shot 2016-02-22 at 16 15 36](https://cloud.githubusercontent.com/assets/15122050/13222385/0c0a653e-d980-11e5-8c9d-6824beb6948e.png)
