### ISSUE TITLE
Can't get --hidden to work

### ISSUE THREAD

**Issue by dantman** [node-inspector/node-inspector#389]
I can't get --hidden to work, this is really problematic since I use Q promises which make stepping tricky without the ability to black box q.js itself.

Q is a direct dependency at `node_modules/q/q.js`.

I've tried running node-inspector like:

```
node-inspector --hidden '["(.*/)?node_modules/.*"]' --web-port 3001
node-inspector --hidden '["node_modules/q"]' --web-port 3001
node-inspector --hidden "node_modules/q" --web-port 3001
node-inspector --hidden '["q.js"]' --web-port 3001
```

I've even tried creating a `.node-inspectorrc` in my project folder:

```
{
    "web-port": 3001,
    "hidden": ["(.*/)?node_modules/.*"]
}
```

No matter what I use when I breakpoint and step through my project I still end up stepping into q.js.

**Comment by eyalw** [comment]
Still happens for me... node_modules appear in the sidebar in the inspector.
latest OS X
node v5.3.0
node-inspector: "0.12.5"

**.node-inspectorrc**
``` 
{
  "web-port": 9090,
  "debug-brk": false,
  "save-live-edit": false,
  "preload": false,
  "hidden": ["node_modules"]
}
```
