### ISSUE TITLE
Node-inspector not working with inline source map

### ISSUE THREAD

**Issue by adamloving** [node-inspector/node-inspector#401]
I'm not sure if this is a node-inspector issue, or a Webkit issue. I couldn't get node-inspector to work with inline source maps (using the ```sourceMappingURL=data:application/json;base64,...``` syntax)

Here's my test. The test file (*test.coffee*): 
```coffee
debugger
console.log 'Hello world'
```

From that, generate a map using...
```js
fs = require('fs');
CoffeeScript = require('coffee-script');

answer = CoffeeScript._compileFile('inline/test.coffee', true);
code = fs.readFileSync('inline/test.coffee', { encoding: 'utf-8' });

mapJSON = answer.sourceMap.generate({
  sourceFiles: ['test.coffee'],
  generatedFile: ['testjs'],
  inline: true
}, code)

console.log('map: ----------');
console.log(mapJSON);
console.log('base64: ----------');
console.log(Buffer(mapJSON).toString('base64'));
```

This makes a map that looks like
```
{
  "version": 3,
  "file": [
    "test.js"
  ],
  "sourceRoot": "",
  "sources": [
    "test.coffee"
  ],
  "names": [],
  "mappings": "AAAA;AAAA,WAAA;AAAA,EACA,OAAO,CAAC,GAAR,CAAY,aAAZ,CADA,CAAA;AAAA",
  "sourcesContent": [
    "debugger\nconsole.log 'Hello world'"
  ]
}
```

So the compiled file, with the base64 encoded sourceMappingURL looks like
```js
// Generated by CoffeeScript 1.7.1
(function() {
  debugger;
  console.log('Hello world');

}).call(this);

//# sourceMappingURL=ewogICJ2ZXJzaW9uIjogMywKICAiZmlsZSI6IFsKICAgICJ0ZXN0LmpzIgogIF0sCiAgInNvdXJjZVJvb3QiOiAiIiwKICAic291cmNlcyI6IFsKICAgICJ0ZXN0LmNvZmZlZSIKICBdLAogICJuYW1lcyI6IFtdLAogICJtYXBwaW5ncyI6ICJBQUFBO0FBQUEsV0FBQTtBQUFBLEVBQ0EsT0FBTyxDQUFDLEdBQVIsQ0FBWSxhQUFaLENBREEsQ0FBQTtBQUFBIiwKICAic291cmNlc0NvbnRlbnQiOiBbCiAgICAiZGVidWdnZXJcbmNvbnNvbGUubG9nICdIZWxsbyB3b3JsZCciCiAgXQp9
```

Then run
```bash
$ node-debug test.js
```

Sadly, there is no test.coffee anywhere to be found in the debugger.

![inline sourcemap broken](https://www.evernote.com/shard/s3/sh/890ab33d-c5a8-44df-b5e4-cc7c3f914d46/af0e55ebbc6bf5c08ce552f3179f8e36/res/11b4f845-311b-474d-90ad-45c516dfbbb6/skitch.png)

I'll commit this test code over here: https://github.com/adamloving/coffeescript-sourcemap-demo

**Comment by michaelBenin** [comment]
+1 - running into this issue using babel with inline source maps.

**Comment by mgmorcos** [comment]
:+1:

**Comment by ericvw** [comment]
I am using `node-inspector@0.12.3` and the inline source maps generated by `tsc` (i.e., TypeScript compiler) appear to work.  I also tested with `babel` and node-inspector is able to pick up the source map just fine.

`//# sourceMappingURL=data:application/json;base64,...` is what is generated for both `tsc` and `babel`.

**Comment by DylanPiercey** [comment]
https://github.com/jashkenas/coffeescript/pull/4111 would allow inline sourcemaps natively in coffeescript. I tested this with node inspector and it seems to work so this could probably be closed.

**Comment by michaelBenin** [comment]
Coffee & Babel?

**Comment by DylanPiercey** [comment]
@michaelBenin inline sourcemaps are already in babel and @ericvw has said that this works with node-inspector.

Unless i'm missing your meaning?

**Comment by michaelBenin** [comment]
Sorry I read that wrong. Ignore that.

**Comment by ericvw** [comment]
This can probably be closed.  There are some other issues with babel's inline sourcemap merging (i.e., babel/babel#2336), but I have been using inline sourcemaps for the past month now with no problems.

**Comment by bajtos** [comment]
Cool, I am glad inline source maps work for you folks. I am closing this issue per the comment above.

**Comment by michaelBenin** [comment]
![screen shot 2015-10-16 at 1 32 32 pm](https://cloud.githubusercontent.com/assets/521971/11005801/0378a9ae-848e-11e5-9fbe-c93052b657b0.png)

**Comment by damonmcminn** [comment]
I am also encountering the same (similar) issue as @michaelBenin i.e. the above image is exactly the same for me. Node Inspector 0.12.3, same result for Babel 5 and Babel 6.

The only thing I can think of is that the code is using `babel-core/register` rather than generating ES5 files. Is this likely to make a difference?

**Comment by amcdnl** [comment]
@damonmcminn I get the same thing.

**Comment by michaelBenin** [comment]
I've found that on my personal computer which is 5 years old I have this issue. On my work computer which was issued last year it works fine.
