### ISSUE TITLE
Question: Is a dark theme available or if not, how to add ?

### ISSUE THREAD

**Issue by nottoseethesun** [node-inspector/node-inspector#415]
Is a dark theme such as:

  https://github.com/mauricecruz/chrome-devtools-zerodarkmatrix-theme

available for node-inspector, or if not, how would one go about creating a theme for node-inspector ?

**Comment by vycb** [comment]
this is updated CSS for newer version of node-inspector https://raw.githubusercontent.com/vycb/redtreeoflife/test/blackdev.css
