### ISSUE TITLE
Could not debug coffee-script app

### ISSUE THREAD

**Issue by tonka3000** [node-inspector/node-inspector#446]
Hy,

i have troubles debugging a simple express-app written in coffeescript.

Here is the source:
![app coffee screentshot](https://cloud.githubusercontent.com/assets/3163807/4409515/13a1c50e-44de-11e4-8906-f1b220b7900e.png)

I start the script with **coffee --nodejs --debug app.coffee** and i can see the script in node-inspector, but the start of the script is different. It is not possible to set a break-point!

![app coffee in node inspector](https://cloud.githubusercontent.com/assets/3163807/4409521/1b2bcba8-44de-11e4-8187-5944b790dd5d.png)

If i compile the coffeescript to javascript with following command **coffee -c -m app.coffee** and start the generated js file with **node --debug app.js** everything works just fine.

Does anybody has the same problem? Or is that an limitation of node-inspector.

OS: Mac OS X Mavericks
node 0.10.30
node-inspector 0.7.4
coffee-script 1.8.0
express 4.0.0
body-parser 1.0.1

Greetings
Tonka

**Comment by TangMonk** [comment]
@bajtos ,Hi , I can not debug too, It just said: ```$ debugger listening on port 5858```, but actually nothing happened when I run ```$ coffee --nodejs --debug app.coffee```

**Comment by bajtos** [comment]
@TangMonk of course the chrome was not opened.

Steps to debug:

1. `$ node-inspector &`
2. `$ coffee --nodejs --debug app.coffee`
3. Manually load `http://127.0.0.1:8080/debug?port=5858` in your Chrome browser.

Note that you will see the transpiled javascript, not the original coffeescript sources - see #224.

**Comment by TangMonk** [comment]
@bajtos thanks ! :+1:

**Comment by webzepter** [comment]
@bajtos thanks a lot!
