### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by bajtos** [node-inspector/node-inspector#449]
The unit-tests are failing on Travis CI:

```
  1) InjectorClient works with commands. "before all" hook: setupInjector:
     Error: timeout of 5000ms exceeded
      at null.<anonymous> (/home/travis/build/node-inspector/node-inspector/node_modules/mocha/lib/runnable.js:157:19)
      at Timer.listOnTimeout (timers.js:133:15)
```

@3y3 I tried to run the test several times to ensure it is not a timing issue. Could you please look into this? It may be enough to increase the test timeout to something like 10s.

**Comment by 3y3** [comment]
Unit test are fixed for ios.
Some timeouts was increased
