### ISSUE TITLE
App (node-webkit) release?

### ISSUE THREAD

**Issue by stevenvachon** [node-inspector/node-inspector#452]
I'm currently building an app very similar to node-inspector, only does not open a browser window and also hooks to the shell.

https://github.com/stevenvachon/nodecon

![](http://oi57.tinypic.com/zvevtg.jpg)

It currently uses [weinre](http://people.apache.org/~pmuellr/weinre-docs/latest/) and am thinking that this library might be better suited. I'm digging through the code, but it seems very tightly knit to the CLI. Would it better to use your [v8-debug](https://npmjs.org/v8-debug) library instead?

Any assistance would be appreciated.

**Comment by bajtos** [comment]
@stevenvachon AFAIK, we there isn't going to be any "Node 0.12 release of node-inspector".

The discussion above seems to have two threads:
 - a request for assistance with using node-inspector in nodecon
 - a question about changes in Node debugger protocol

Your comment makes me believe you are referring to the debugger protocol changes.

First of all, there are no concrete plans for the new debugger protocol as far as I know. The development in joyent/node is pretty stale, most of the new stuff is happening in [iojs/io.js](https://github.com/iojs/io.js). You can read TC meeting minutes [here](https://github.com/iojs/io.js/tree/261706e2ef9f12131ddcf8ff40fd4c7823693e8d/doc/tc-meetings), there is no mention about reworking the debugger protocol.

Until there is a concrete plan for replacing the current V8 debugger protocol with something else, I am reluctant to worry about that in Node Inspector.
