### ISSUE TITLE
Simple problem - using basic command

### ISSUE THREAD

**Issue by the1mills** [node-inspector/node-inspector#458]
![image](https://cloud.githubusercontent.com/assets/2148448/4749593/84248a1a-5a86-11e4-9f9a-c0eb86b07c24.png)

I run "node-inspector" from the command line as I did above. 

The problem:

When open Chrome to <http://localhost:8080/debug?port=5858>, I get only a flicker of hope before something crashes, and developer tools and debugging console won't completely load (it appears to partially load). Node-inspector works on my other machine, but this problem occurs on my current machine which is a Windows 7 64 bit (node is installed as 64 bit version).

As you can see in the image below, you can see the horizontal bar of chrome debugger trying to load, but then it stops, and that's it.

![image](https://cloud.githubusercontent.com/assets/2148448/4749615/c8ee078e-5a86-11e4-8dae-1bc2c5169866.png)

Is this a known issue? Thanks -alex

**Comment by 3y3** [comment]
Fixed in 0.10.1. (ws module updated)

**Comment by the1mills** [comment]
thx it worked
