### ISSUE TITLE
Runtime.getProperties failed. ReferenceError: includeSource is not defined

### ISSUE THREAD

**Issue by WeeJeWel** [node-inspector/node-inspector#461]
I want to see the contents of `global` in the inspector. However, entering `global` in the console, it returns:

![screen shot 2014-10-28 at 16 32 51](https://cloud.githubusercontent.com/assets/319873/4811043/b67874f6-5eb7-11e4-80cc-8d8a83dd6ff3.png)

Entering `console.log(global)` returns undefined, but I see the contents of `global` in the terminal window that started the node process.

---

**This is a regression in Node.js v0.10.35, you should downgrade to v0.10.33.**

**Comment by vitaliks** [comment]
+1

**Comment by justsml** [comment]
+1

**Comment by bajtos** [comment]
FWIW, I have submitted a pull request to fix the problem in Node: https://github.com/joyent/node/pull/8973

**Comment by MWalid** [comment]
+1

**Comment by anatolpa** [comment]
+1

**Comment by dab00** [comment]
+1

**Comment by nvlbg** [comment]
+1

**Comment by bajtos** [comment]
Adding +1 in this thread is not helpful. Please bug the maintainers of Node and/or V8:

 - PR fixing the issue in node:  joyent/node#8973
 - Node issue reporting the problem: https://github.com/joyent/node/issues/8948
 - V8 issue: https://code.google.com/p/v8/issues/detail?id=3790

I am locking this thread to prevent comment spam.

**Comment by 3y3** [comment]
Fixed in 0.10.36
