### ISSUE TITLE
Installing on windows 8.1 Pro

### ISSUE THREAD

**Issue by abenhamdine** [node-inspector/node-inspector#484]
Hello,

node v0.10.31
npm 1.4.23

When I do : 

    npm install -g node-inspector

I get the following error : 

```
> v8-debug@0.3.0 install C:\Users\Arnaud\AppData\Roaming\npm\node_modules\node-i
nspector\node_modules\v8-debug
> node-gyp rebuild


C:\Users\Arnaud\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-
debug>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
gyp ERR! configure error de-gyp.js" rebuild \
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Arnaud\AppData\Roaming\npm\node_modules\node-inspector\nod
e_modules\v8-debug
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
 yp ERR! not ok/



> v8-profiler@5.1.1 install C:\Users\Arnaud\AppData\Roaming\npm\node_modules\nod
e-inspector\node_modules\v8-profiler
> node-gyp rebuild


C:\Users\Arnaud\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-
profiler>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\
node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Arnaud\AppData\Roaming\npm\node_modules\node-inspector\nod
e_modules\v8-profiler
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm ERR! v8-debug@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.3.0 install script.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! cwd C:\Mes Sites\RM_Web\RM_WEB_WEB\libs\covelys
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Mes Sites\RM_Web\RM_WEB_WEB\libs\covelys\npm-debug.log
npm ERR! not ok code 0
```

Any clue ?

**Comment by cihadturhan** [comment]
Hi, thanks for all the comments here. I've installed node-inspector 3 times without problems, but this time, I had the similar error log posted above. 

As you suggested, I've installed python 2.7.x and Visual Studio Express 2010 and now it's working but be aware that python and node doesn't add it's executable to path by default so you should click the checkbox during installation or add them to path manually after.

BTW, I've faced another issue after running `node-debug server.js`. It didn't serve the correctly which I thought it was about firewall. It turns out it was about node-inspector  and I resolved it by installing `npm install node-debug` so now it's working flawlessly. 

 - Node version: 0.10.34-x86
 - Python version: 2.7.9-x86

Hope these help someone. 

Cheers

**Comment by ekulabuhov** [comment]
Hi, had to reinstall node-inspector recently & faced the problem with Python missing (v8-profiler dependency?). Since I never had Python installed before and node-inspector was running fine, I was left scratching my head. 

Figured out that the problem exists with v0.8.0 & 0.8.1 of node-inspector, so tried running `npm install node-inspector@0.7.4 -g` which worked like a charm. I know it's a temp solution and prevents me from upgrading, but it might help somebody looking for a solution now.

Thanks.

**Comment by josmoi** [comment]
@ekulabuhov it works!  thanks a lot!

**Comment by bajtos** [comment]
@ekulabuhov could you please try to install the latest v0.8 version (v0.8.3 or later)? The comments in #496 makes me believe that the issue should be resolved there.

**Comment by verybigdog** [comment]
I've got same error as @abenhamdine, so installed python27 and now I got error message according to VCBuild.
Installing with "npm install node-inspector --save"


gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\me\WebstormProjects\iphonic\node_modules\node-inspector\
node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> v8-profiler@5.2.9 install C:\Users\me\WebstormProjects\iphonic\node_modules\
node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "C:\Users\me\WebstormProjects\iphonic\node_modules\node
-inspector\node_modules\v8-profiler\build\profiler\v5.2.9\node-v14-win32-x64\pro
filer.node" is installed via remote
npm WARN optional dep failed, continuing bufferutil@1.1.0

> v8-debug@0.4.6 install C:\Users\me\WebstormProjects\iphonic\node_modules\nod
e-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "C:\Users\me\WebstormProjects\iphonic\node_modules\node-in
spector\node_modules\v8-debug\build\debug\v0.4.6\node-v14-win32-x64\debug.node"
is installed via remote
node-inspector@0.10.1 node_modules\node-inspector
├── async@0.9.2
├── semver@4.3.6
├── rc@1.0.3 (ini@1.3.4, strip-json-comments@0.1.3, deep-extend@0.2.11, minim
ist@0.0.10)
├── strong-data-uri@1.0.1 (truncate@1.0.4)
├── which@1.1.1 (is-absolute@0.1.7)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once
@1.3.2, minimatch@2.0.8)
├── yargs@3.10.0 (decamelize@1.0.0, camelcase@1.1.0, window-size@0.1.0, cliui
@2.1.0)
├── biased-opener@0.2.6 (minimist@1.1.0, x-default-browser@0.3.0, browser-lau
ncher2@0.4.5)
├── ws@0.7.2 (options@0.0.6, ultron@1.0.1)
├── v8-profiler@5.2.9 (nan@1.8.4, node-pre-gyp@0.6.7)
└── v8-debug@0.4.6 (nan@1.8.4, node-pre-gyp@0.6.7)

**Comment by 3y3** [comment]
@verybigdog , but from your log I see what you have succesefully installed node-inspector (ignore unimportant error from ws module)

**Comment by verybigdog** [comment]
@3y3 Oh.. sorry i confused. Thanks

**Comment by 3y3** [comment]
This issue is very outdated and I think it was solved by lot of commits in node, v8-debug, v8-profiler and node-inspector.
If there still exist problems with node-inspector installation, please open new issue.
