### ISSUE TITLE
installation on windows 7

### ISSUE THREAD

**Issue by aashishiiita** [node-inspector/node-inspector#496]
'<node-gyp rebuild 2 > builderror.log  > || <exit 0>'
this error is coming constantly.

**Comment by cihadturhan** [comment]
See my explanation on #484, maybe it will help.

**Comment by 3y3** [comment]
Can anybody confirm error on 0.8.2?

**Comment by arbixy** [comment]
Installed 0.8.3 under (node: 0.10.33, npm: 1.4.28)  Ubuntu 14.04 x64 and under (node: 0.10.35 ) win10 Preview. Worked like a charm.

**Comment by bajtos** [comment]
@arbixy thanks for verifying the fix, I am closing this issue as resolved.
