### ISSUE TITLE
Console message location throws error

### ISSUE THREAD

**Issue by 3y3** [node-inspector/node-inspector#500]
Now, to receive message location, we throw error to receive call stack.

This is a bad strategy, because debugger stops on each console.log, if `pause on uncaught error` is enabled.
Also here is an error #497

So we can silently pause execution on console.log receive call stack from `exec_state` and resume execution.

**Comment by asselin** [comment]
Note that this change also fixes a bug where console.log() from inside an anonymous function throws an exception inside this function.  Root cause was because the old regexp didn't work in that case-- the URL was not surrounded by parens.

**Comment by stefek99** [comment]
I was using old version and searching for error message got me here.

```
node-inspector --version
Node Inspector v0.8.0
npm update -g node-inspector
...
```

Thank you for fixing that bug.
