### ISSUE TITLE
File Explorer Behavior - Directories

### ISSUE THREAD

**Issue by stonstad** [node-inspector/node-inspector#505]
Double-clicking opens a directory hierarchy in the file explorer.  Double-clicking again does not close the opened directory.  This is definitely a nice to have... would come in handy when a project has a large directory structure.

This was seen on Chrome - 39.0.2171.95 m.

**Comment by bajtos** [comment]
I am afraid this is a bug in Chrome Dev Tools, the version shipped in  39.0.2171.95 exhibits the same behaviour. Please report the issue in the Chromium project: http://crbug.com/
