### ISSUE TITLE
npm install -g node-inspector    v0.8  error!!!

### ISSUE THREAD

**Issue by robinxc** [node-inspector/node-inspector#516]
npm ERR! v8-profiler@5.2.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.2.1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-504.el6.x86_64
npm ERR! command "/home/node/v0.10.35/bin/node" "/home/node/v0.10.35/bin/npm" "install" "-g" "node-inspector"
npm ERR! cwd /home/Mages

**Comment by ekulabuhov** [comment]
Hey guys, apparently starting from v0.8.0 node-inspector added few additional dependencies. Could you try installing different version and see how it goes (see https://github.com/node-inspector/node-inspector/issues/484#issuecomment-69052229)?

**Comment by Tiendq** [comment]
FYI, I just installed it successfully with v0.7.4

**Comment by 3y3** [comment]
I added some fixes to v8-profiler and v8-debug. Also I added prebuild binaries for Linux and OSX.
Please try to reinstall node-inspector now.

**Comment by Tiendq** [comment]
@3y3 I got another error.

npm ERR! Error: shasum check failed for /tmp/npm-19331-IyJ-YIOw/registry.npmjs.org/v8-debug/-/v8-debug-0.3.2.tgz
npm ERR! Expected: d9a1fc3871aed1064b39c65a5a8c9b76eb23803e
npm ERR! Actual:   48f3ebba48073df23874c58b92af316a233efed0
npm ERR! From:     https://registry.npmjs.org/v8-debug/-/v8-debug-0.3.2.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! cwd /Users/tiendq/Temp/test
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by 3y3** [comment]
try `npm cache clean`

**Comment by Tiendq** [comment]
Got same error :)

**Comment by 3y3** [comment]
@Tiendq , google says that this is not a problem only of `v8-debug`.

**Comment by 3y3** [comment]
Original error resolver
