### ISSUE TITLE
node-inspector crashes with dyld error

### ISSUE THREAD

**Issue by hegemonic** [node-inspector/node-inspector#519]
I'm running:

+ Node.js 0.11.14
+ node-inspector 0.8.1
+ OS X Yosemite (10.10.1)

When I try to run my script with `node-debug`, I get the following error, and node-inspector exits immediately:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Script7CompileENS_6HandleINS_6StringEEEPNS_12ScriptOriginEPNS_10ScriptDataE
  Referenced from: /Users/jeffw/.nvm/v0.11.14/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.3/node-v14-darwin-x64/debug.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Script7CompileENS_6HandleINS_6StringEEEPNS_12ScriptOriginEPNS_10ScriptDataE
  Referenced from: /Users/jeffw/.nvm/v0.11.14/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.3/node-v14-darwin-x64/debug.node
  Expected in: dynamic lookup
```

**Comment by hegemonic** [comment]
I'm getting the same error after installing Node.js from the official 0.11.14 package and reinstalling node-inspector.

**Comment by 3y3** [comment]
This error is relative to prebuild binaries for unstable version.
Node Inspector doesn't have prebuild binaries for 0.11.14, only for 0.11.13 (reason - 0.11.14 have only nightly version for Win x64)

To resolve problem today you have some options for your selection:
1. Downgrade to 0.11.13
2. Reinstall manually `v8-debug` and `v8-profiler` like this:
```
cd node-inspector
npm install v8-debug --build-from-source
npm install v8-profiler --build-from-source
```

The second option is useful only if you have correct build enviroment (Visual C++, Python, etc.)

**Comment by hegemonic** [comment]
Downgrading to Node.js 0.11.13 fixed the problem. But Node.js 0.11.14 was released in September, so I think it's time to upgrade the prebuilt binaries. It looks like there's an official Win x64 build: http://nodejs.org/dist/v0.11.14/x64/

**Comment by 3y3** [comment]
> It looks like there's an official Win x64 build: http://nodejs.org/dist/v0.11.14/x64/

This dist was builded incorrectly, or specially marked as nightly. [node-pre-gyp issues](https://github.com/mapbox/node-pre-gyp/issues?q=v0.11.14+)

**Comment by hegemonic** [comment]
What fun. :/ Thanks for the added context!

**Comment by hegemonic** [comment]
Closing this issue, since it sounds like there's not a good solution until 0.11.15 is released.
