### ISSUE TITLE
CRLF in bin-scripts with bangs break *nix usage

### ISSUE THREAD

**Issue by aars** [node-inspector/node-inspector#521]
Like many other NPMs (apparently) node-inspector bin-script contains a CRLF. This breaks usage in linux/unix/mac.

On my mac with a freshly installed node-inspector, v0.8.2:

```
env: node\r: No such file or directory
```

On a linux box, same version:
```
: No such file or directory
```

Saving the files as unix fileformat fixes this (vim :set ff=unix). Not sure if that will break usage on windows though.

**Comment by aars** [comment]
It seems to happen a lot. https://github.com/npm/npm/issues/4607

**Comment by 3y3** [comment]
This is a very reasonable issue. Last version ewlwased from my Windows machine. I will work on 0.8.3 to fix this. I will wait your feedback after 0.8.3 release

**Comment by bajtos** [comment]
@3y3 you should configure your git to always use LF in the files - set `core.autocrlf=true` ([explanation](http://stackoverflow.com/a/1967986/69868)).

**Comment by aars** [comment]
Thanks!

**Comment by 3y3** [comment]
@bajtos , I prefer to also add `.gitattributes` file to project with `* text eol=lf`

**Comment by 3y3** [comment]
@aars , can you check 0.8.3 please

**Comment by aars** [comment]
``` sh
node-inspector
Node Inspector v0.8.3
Visit http://127.0.0.1:8080/debug?port=5858 to start debugging.
```

Works! Thanks!
