### ISSUE TITLE
Runtime.getProperties failed.

### ISSUE THREAD

**Issue by chevex** [node-inspector/node-inspector#522]
I've been using node-inspector for quite a while and it's always worked pretty well, until the most recent update. Now when I debug, all my objects say they have no properties (both on hover and in the watch window). In the node-inspector console I see the error `Runtime.getProperties` failed. The error occurs when I'm trying to view an object's properties so it seems pretty clear it's related.

If I try to manually navigate the object graph in the console I can do that just fine. I just have to know that the property is there first, which kind of defeats the purpose.

There's also a `ReferenceError: frame_index is not defined` and `ReferenceError: includeSource is not defined` that shows up periodically in the console. Not sure if that one is related to this issue or not though.

![image](https://cloud.githubusercontent.com/assets/874394/5722128/cbb7cfee-9af6-11e4-99d0-33dc4d5d9add.png)

You can see above when I type `req.url` in the console I am able to see the value. But the properties popover claims there are no properties on `req` and the console is filled with errors.

**Comment by 3y3** [comment]
Duplicate #461. Use node <=0.10.33 or wait 0.10.36

**Comment by chevex** [comment]
Sorry, I thought I searched the issue list well enough but apparently not. Thanks for the link.

**Comment by i5ting** [comment]
v0.10.35 有问题
