### ISSUE TITLE
Program hangs after launch

### ISSUE THREAD

**Issue by bajan64** [node-inspector/node-inspector#524]
After launching the program hangs - app initialization logging statements are not executed (or at least not displayed).

% node-inspector app.js 
Node Inspector v0.8.1
Visit http://127.0.0.1:8080/debug?port=5858 to start debugging.

When you connect the browser (it is not automatically invoked as before) you get the message

express deprecated res.sendfile: Use res.sendFile instead ../../../../../../../usr/local/lib/node_modules/node-inspector/lib/debug-server.js:17:7

Then nothing.

Same on two different systems:

Darwin Evelyn.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

Linux ip-172-31-35-98 3.14.26-24.46.amzn1.x86_64 #1 SMP Wed Dec 10 10:02:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

node v0.10.34

% npm list
├─┬ amazon-product-api@0.1.2
│ ├── es6-promise@1.0.0
│ └─┬ xml2js@0.4.4
│   ├── sax@0.6.1
│   └─┬ xmlbuilder@2.4.5
│     └── lodash-node@2.4.1
├─┬ async-replace@1.0.0
│ └── async@0.1.22
├─┬ bcrypt@0.8.0
│ ├── bindings@1.0.0
│ └── nan@1.3.0
├─┬ body-parser@1.10.0
│ ├── bytes@1.0.0
│ ├── depd@1.0.0
│ ├── iconv-lite@0.4.5
│ ├── media-typer@0.3.0
│ ├─┬ on-finished@2.1.1
│ │ └── ee-first@1.1.0
│ ├── qs@2.3.3
│ ├── raw-body@1.3.1
│ └─┬ type-is@1.5.4
│   └─┬ mime-types@2.0.4
│     └── mime-db@1.3.1
├── bootstrap@3.3.1 (git+https://github.com/twbs/bootstrap.git#6fe9cd9fef3e0960d0ef8484dea7aecd0880de84)
├── bufferlist@0.1.0
├─┬ compression@1.2.2
│ ├─┬ accepts@1.1.4
│ │ ├─┬ mime-types@2.0.4
│ │ │ └── mime-db@1.3.1
│ │ └── negotiator@0.4.9
│ ├── bytes@1.0.0
│ ├─┬ compressible@2.0.1
│ │ └── mime-db@1.3.1
│ ├─┬ debug@2.1.0
│ │ └── ms@0.6.2
│ ├── on-headers@1.0.0
│ └── vary@1.0.0
├── connect-flash@0.1.1
├── connect-logger@0.0.1
├─┬ connect-redis@2.1.0
│ └─┬ debug@1.0.4
│   └── ms@0.6.2
├─┬ cookie-parser@1.3.3
│ ├── cookie@0.1.2
│ └── cookie-signature@1.0.5
├─┬ emailjs@0.3.12
│ ├── bufferjs@1.1.0
│ ├─┬ mimelib@0.2.14
│ │ ├── addressparser@0.2.1
│ │ └─┬ encoding@0.1.11
│ │   └── iconv-lite@0.4.5
│ ├── moment@1.7.0
│ └── starttls@0.2.1
├─┬ errorhandler@1.3.0
│ ├─┬ accepts@1.1.4
│ │ ├─┬ mime-types@2.0.4
│ │ │ └── mime-db@1.3.1
│ │ └── negotiator@0.4.9
│ └── escape-html@1.0.1
├─┬ express@4.10.6
│ ├─┬ accepts@1.1.4
│ │ ├─┬ mime-types@2.0.4
│ │ │ └── mime-db@1.3.1
│ │ └── negotiator@0.4.9
│ ├── content-disposition@0.5.0
│ ├── cookie@0.1.2
│ ├── cookie-signature@1.0.5
│ ├─┬ debug@2.1.0
│ │ └── ms@0.6.2
│ ├── depd@1.0.0
│ ├── escape-html@1.0.1
│ ├─┬ etag@1.5.1
│ │ └── crc@3.2.1
│ ├── finalhandler@0.3.2
│ ├── fresh@0.2.4
│ ├── media-typer@0.3.0
│ ├── merge-descriptors@0.0.2
│ ├── methods@1.1.0
│ ├─┬ on-finished@2.1.1
│ │ └── ee-first@1.1.0
│ ├── parseurl@1.3.0
│ ├── path-to-regexp@0.1.3
│ ├─┬ proxy-addr@1.0.4
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@0.1.5
│ ├── qs@2.3.3
│ ├── range-parser@1.0.2
│ ├─┬ send@0.10.1
│ │ ├── destroy@1.0.3
│ │ └── ms@0.6.2
│ ├── serve-static@1.7.1
│ ├─┬ type-is@1.5.4
│ │ └─┬ mime-types@2.0.4
│ │   └── mime-db@1.3.1
│ ├── utils-merge@1.0.0
│ └── vary@1.0.0
├── express-cluster@0.0.3 extraneous
├─┬ express-session@1.9.3
│ ├── cookie@0.1.2
│ ├── cookie-signature@1.0.5
│ ├── crc@3.2.1
│ ├─┬ debug@2.1.0
│ │ └── ms@0.6.2
│ ├── depd@1.0.0
│ ├── on-headers@1.0.0
│ ├── parseurl@1.3.0
│ ├─┬ uid-safe@1.0.1
│ │ ├── base64-url@1.0.0
│ │ └─┬ mz@1.1.0
│ │   └── native-or-bluebird@1.1.2
│ └── utils-merge@1.0.0
├─┬ fbgraph@0.3.0
│ ├── qs@1.2.2
│ └─┬ request@2.40.0
│   ├── aws-sign2@0.5.0
│   ├── forever-agent@0.5.2
│   ├─┬ form-data@0.1.4
│   │ ├── async@0.9.0
│   │ ├─┬ combined-stream@0.0.7
│   │ │ └── delayed-stream@0.0.5
│   │ └── mime@1.2.11
│   ├─┬ hawk@1.1.1
│   │ ├── boom@0.4.2
│   │ ├── cryptiles@0.2.2
│   │ ├── hoek@0.9.1
│   │ └── sntp@0.2.4
│   ├─┬ http-signature@0.10.0
│   │ ├── asn1@0.1.11
│   │ ├── assert-plus@0.1.2
│   │ └── ctype@0.5.2
│   ├── json-stringify-safe@5.0.0
│   ├── mime-types@1.0.2
│   ├── node-uuid@1.4.2
│   ├── oauth-sign@0.3.0
│   ├── qs@1.0.2
│   ├── stringstream@0.0.4
│   ├─┬ tough-cookie@0.12.1
│   │ └── punycode@1.3.2
│   └── tunnel-agent@0.4.0
├─┬ goodreads@0.0.2
│ ├─┬ coffee-script@1.8.0
│ │ └── mkdirp@0.3.5
│ ├── oauth@0.9.12
│ └─┬ xml2js@0.4.4
│   ├── sax@0.6.1
│   └─┬ xmlbuilder@2.4.5
│     └── lodash-node@2.4.1
├─┬ grunt@0.4.5
│ ├── async@0.1.22
│ ├── coffee-script@1.3.3
│ ├── colors@0.6.2
│ ├── dateformat@1.0.2-1.2.3
│ ├── eventemitter2@0.4.14
│ ├── exit@0.1.2
│ ├─┬ findup-sync@0.1.3
│ │ ├─┬ glob@3.2.11
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.5.0
│ │ │   └── sigmund@1.0.0
│ │ └── lodash@2.4.1
│ ├── getobject@0.1.0
│ ├─┬ glob@3.1.21
│ │ ├── graceful-fs@1.2.3
│ │ └── inherits@1.0.0
│ ├─┬ grunt-legacy-log@0.1.1
│ │ ├── colors@0.6.2
│ │ ├── lodash@2.4.1
│ │ └── underscore.string@2.3.3
│ ├─┬ grunt-legacy-util@0.2.0
│ │ ├── async@0.1.22
│ │ ├── lodash@0.9.2
│ │ └── underscore.string@2.2.1
│ ├── hooker@0.2.3
│ ├── iconv-lite@0.2.11
│ ├─┬ js-yaml@2.0.5
│ │ ├─┬ argparse@0.1.16
│ │ │ ├── underscore@1.7.0
│ │ │ └── underscore.string@2.4.0
│ │ └── esprima@1.0.4
│ ├── lodash@0.9.2
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.5.0
│ │ └── sigmund@1.0.0
│ ├─┬ nopt@1.0.10
│ │ └── abbrev@1.0.5
│ ├── rimraf@2.2.8
│ ├── underscore.string@2.2.1
│ └── which@1.0.8
├─┬ grunt-contrib-concat@0.5.0
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ └─┬ source-map@0.1.40
│   └── amdefine@0.1.0
├─┬ grunt-contrib-copy@0.7.0
│ └─┬ chalk@0.5.1
│   ├── ansi-styles@1.1.0
│   ├── escape-string-regexp@1.0.2
│   ├─┬ has-ansi@0.1.0
│   │ └── ansi-regex@0.2.1
│   ├─┬ strip-ansi@0.3.0
│   │ └── ansi-regex@0.2.1
│   └── supports-color@0.2.0
├─┬ grunt-contrib-cssmin@0.10.0
│ ├─┬ chalk@0.4.0
│ │ ├── ansi-styles@1.0.0
│ │ ├── has-color@0.1.7
│ │ └── strip-ansi@0.1.1
│ ├─┬ clean-css@2.2.22
│ │ └── commander@2.2.0
│ └─┬ maxmin@0.2.2
│   ├─┬ chalk@0.5.1
│   │ ├── ansi-styles@1.1.0
│   │ ├── escape-string-regexp@1.0.2
│   │ ├─┬ has-ansi@0.1.0
│   │ │ └── ansi-regex@0.2.1
│   │ ├─┬ strip-ansi@0.3.0
│   │ │ └── ansi-regex@0.2.1
│   │ └── supports-color@0.2.0
│   ├── figures@1.3.5
│   ├─┬ gzip-size@0.2.0
│   │ ├─┬ browserify-zlib@0.1.4
│   │ │ └── pako@0.2.5
│   │ └─┬ concat-stream@1.4.7
│   │   ├── inherits@2.0.1
│   │   ├─┬ readable-stream@1.1.13
│   │   │ ├── core-util-is@1.0.1
│   │   │ ├── isarray@0.0.1
│   │   │ └── string_decoder@0.10.31
│   │   └── typedarray@0.0.6
│   └── pretty-bytes@0.1.2
├─┬ grunt-contrib-less@0.12.0
│ ├── async@0.2.10
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├─┬ less@1.7.5
│ │ ├─┬ clean-css@2.2.22
│ │ │ └── commander@2.2.0
│ │ ├── graceful-fs@3.0.5
│ │ ├── mime@1.2.11
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ ├─┬ request@2.40.0
│ │ │ ├── aws-sign2@0.5.0
│ │ │ ├── forever-agent@0.5.2
│ │ │ ├─┬ form-data@0.1.4
│ │ │ │ ├── async@0.9.0
│ │ │ │ └─┬ combined-stream@0.0.7
│ │ │ │   └── delayed-stream@0.0.5
│ │ │ ├─┬ hawk@1.1.1
│ │ │ │ ├── boom@0.4.2
│ │ │ │ ├── cryptiles@0.2.2
│ │ │ │ ├── hoek@0.9.1
│ │ │ │ └── sntp@0.2.4
│ │ │ ├─┬ http-signature@0.10.0
│ │ │ │ ├── asn1@0.1.11
│ │ │ │ ├── assert-plus@0.1.2
│ │ │ │ └── ctype@0.5.2
│ │ │ ├── json-stringify-safe@5.0.0
│ │ │ ├── mime-types@1.0.2
│ │ │ ├── node-uuid@1.4.2
│ │ │ ├── oauth-sign@0.3.0
│ │ │ ├── qs@1.0.2
│ │ │ ├── stringstream@0.0.4
│ │ │ ├─┬ tough-cookie@0.12.1
│ │ │ │ └── punycode@1.3.2
│ │ │ └── tunnel-agent@0.4.0
│ │ └─┬ source-map@0.1.40
│ │   └── amdefine@0.1.0
│ ├── lodash@2.4.1
│ └─┬ maxmin@0.1.0
│   ├─┬ chalk@0.4.0
│   │ ├── ansi-styles@1.0.0
│   │ ├── has-color@0.1.7
│   │ └── strip-ansi@0.1.1
│   ├─┬ gzip-size@0.1.1
│   │ ├─┬ concat-stream@1.4.7
│   │ │ ├── inherits@2.0.1
│   │ │ ├─┬ readable-stream@1.1.13
│   │ │ │ ├── core-util-is@1.0.1
│   │ │ │ ├── isarray@0.0.1
│   │ │ │ └── string_decoder@0.10.31
│   │ │ └── typedarray@0.0.6
│   │ └─┬ zlib-browserify@0.0.3
│   │   └─┬ tape@0.2.2
│   │     ├── deep-equal@0.0.0
│   │     ├── defined@0.0.0
│   │     └── jsonify@0.0.0
│   └── pretty-bytes@0.1.2
├─┬ grunt-contrib-stylus@0.20.0
│ ├── async@0.9.0
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├── lodash@2.4.1
│ └─┬ nib@1.0.4
│   └─┬ stylus@0.45.1
│     ├── css-parse@1.7.0
│     ├─┬ debug@2.1.0
│     │ └── ms@0.6.2
│     ├─┬ glob@3.2.11
│     │ ├── inherits@2.0.1
│     │ └─┬ minimatch@0.3.0
│     │   ├── lru-cache@2.5.0
│     │   └── sigmund@1.0.0
│     ├── mkdirp@0.3.5
│     └── sax@0.5.8
├─┬ grunt-contrib-uglify@0.6.0
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├── lodash@2.4.1
│ ├─┬ maxmin@1.0.0
│ │ ├── figures@1.3.5
│ │ ├─┬ gzip-size@1.0.0
│ │ │ ├─┬ browserify-zlib@0.1.4
│ │ │ │ └── pako@0.2.5
│ │ │ └─┬ concat-stream@1.4.7
│ │ │   ├── inherits@2.0.1
│ │ │   ├─┬ readable-stream@1.1.13
│ │ │   │ ├── core-util-is@1.0.1
│ │ │   │ ├── isarray@0.0.1
│ │ │   │ └── string_decoder@0.10.31
│ │ │   └── typedarray@0.0.6
│ │ └─┬ pretty-bytes@1.0.2
│ │   └── get-stdin@1.0.0
│ ├─┬ uglify-js@2.4.16
│ │ ├── async@0.2.10
│ │ ├─┬ optimist@0.3.7
│ │ │ └── wordwrap@0.0.2
│ │ ├─┬ source-map@0.1.34
│ │ │ └── amdefine@0.1.0
│ │ └── uglify-to-browserify@1.0.2
│ └── uri-path@0.0.2
├─┬ grunt-contrib-watch@0.6.1
│ ├── async@0.2.10
│ ├─┬ gaze@0.5.1
│ │ └─┬ globule@0.1.0
│ │   ├─┬ glob@3.1.21
│ │   │ ├── graceful-fs@1.2.3
│ │   │ └── inherits@1.0.0
│ │   ├── lodash@1.0.1
│ │   └─┬ minimatch@0.2.14
│ │     ├── lru-cache@2.5.0
│ │     └── sigmund@1.0.0
│ ├── lodash@2.4.1
│ └─┬ tiny-lr-fork@0.0.5
│   ├── debug@0.7.4
│   ├── faye-websocket@0.4.4
│   ├─┬ noptify@0.0.3
│   │ └─┬ nopt@2.0.0
│   │   └── abbrev@1.0.5
│   └── qs@0.5.6
├── imagemagick@0.1.3
├── isbn@0.2.0
├─┬ jade@1.8.2
│ ├── character-parser@1.2.1
│ ├── commander@2.5.1
│ ├─┬ constantinople@3.0.1
│ │ └─┬ acorn-globals@1.0.1
│ │   └── acorn@0.8.0
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ ├─┬ transformers@2.1.0
│ │ ├─┬ css@1.0.8
│ │ │ ├── css-parse@1.0.4
│ │ │ └── css-stringify@1.0.5
│ │ ├─┬ promise@2.0.0
│ │ │ └── is-promise@1.0.1
│ │ └─┬ uglify-js@2.2.5
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.2
│ │   └─┬ source-map@0.1.40
│ │     └── amdefine@0.1.0
│ ├── void-elements@1.0.0
│ └─┬ with@4.0.0
│   ├── acorn@0.8.0
│   └─┬ acorn-globals@1.0.1
│     └── acorn@0.8.0
├─┬ mailchimp@1.1.0
│ └── qs@0.5.6
├─┬ method-override@2.3.0
│ ├─┬ debug@2.1.0
│ │ └── ms@0.6.2
│ ├── methods@1.1.0
│ ├── parseurl@1.3.0
│ └── vary@1.0.0
├── mime@1.2.11
├── moment@2.8.4
├─┬ morgan@1.5.0
│ ├── basic-auth@1.0.0
│ ├─┬ debug@2.1.0
│ │ └── ms@0.6.2
│ ├── depd@1.0.0
│ └─┬ on-finished@2.1.1
│   └── ee-first@1.1.0
├─┬ multer@0.1.6
│ ├─┬ busboy@0.2.9
│ │ ├─┬ dicer@0.2.3
│ │ │ ├─┬ readable-stream@1.1.13
│ │ │ │ ├── core-util-is@1.0.1
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ └── string_decoder@0.10.31
│ │ │ └── streamsearch@0.1.2
│ │ └─┬ readable-stream@1.1.13
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├── mkdirp@0.3.5
│ └── qs@1.2.2
├─┬ node-linkedin@0.3.4
│ ├── lodash@2.4.1
│ ├── oauth@0.9.12
│ └─┬ request@2.31.0
│   ├── aws-sign2@0.5.0
│   ├── forever-agent@0.5.2
│   ├─┬ form-data@0.1.4
│   │ ├── async@0.9.0
│   │ └─┬ combined-stream@0.0.7
│   │   └── delayed-stream@0.0.5
│   ├─┬ hawk@1.0.0
│   │ ├── boom@0.4.2
│   │ ├── cryptiles@0.2.2
│   │ ├── hoek@0.9.1
│   │ └── sntp@0.2.4
│   ├─┬ http-signature@0.10.0
│   │ ├── asn1@0.1.11
│   │ ├── assert-plus@0.1.2
│   │ └── ctype@0.5.2
│   ├── json-stringify-safe@5.0.0
│   ├── mime@1.2.11
│   ├── node-uuid@1.4.2
│   ├── oauth-sign@0.3.0
│   ├── qs@0.6.6
│   ├─┬ tough-cookie@0.9.15
│   │ └── punycode@1.3.2
│   └── tunnel-agent@0.3.0
├── node-uuid@1.4.2
├─┬ passport@0.2.1
│ ├── passport-strategy@1.0.0
│ └── pause@0.0.1
├─┬ passport-facebook@1.0.3
│ └─┬ passport-oauth2@1.1.2
│   ├── oauth@0.9.12
│   ├── passport-strategy@1.0.0
│   └── uid2@0.0.3
├─┬ passport-goodreads@0.1.2
│ ├─┬ passport-oauth@0.1.15
│ │ ├── oauth@0.9.12
│ │ └─┬ passport@0.1.18
│ │   └── pause@0.0.1
│ ├── pkginfo@0.2.3
│ └─┬ xml2js@0.1.14
│   └── sax@0.6.1
├─┬ passport-google-oauth@0.1.5
│ ├─┬ passport-oauth@0.1.15
│ │ ├── oauth@0.9.12
│ │ └─┬ passport@0.1.18
│ │   └── pause@0.0.1
│ └── pkginfo@0.2.3
├─┬ passport-linkedin-oauth2@1.2.1
│ ├─┬ passport-oauth2@1.1.2
│ │ ├── oauth@0.9.12
│ │ ├── passport-strategy@1.0.0
│ │ └── uid2@0.0.3
│ └── underscore@1.7.0
├─┬ passport-local@1.0.0
│ └── passport-strategy@1.0.0
├─┬ passport-twitter@1.0.2
│ ├─┬ passport-oauth1@1.0.1
│ │ ├── oauth@0.9.12
│ │ ├── passport-strategy@1.0.0
│ │ └── utils-merge@1.0.0
│ └─┬ xtraverse@0.1.0
│   └── xmldom@0.1.19
├─┬ qr@0.2.3
│ ├── benchmark@1.0.0
│ └─┬ vows@0.8.1
│   ├── diff@1.0.8
│   ├── eyes@0.1.8
│   └─┬ glob@4.0.6
│     ├── graceful-fs@3.0.5
│     ├── inherits@2.0.1
│     ├─┬ minimatch@1.0.0
│     │ ├── lru-cache@2.5.0
│     │ └── sigmund@1.0.0
│     └─┬ once@1.3.1
│       └── wrappy@1.0.1
├── redis@0.12.1
├─┬ request@2.51.0
│ ├── aws-sign2@0.5.0
│ ├─┬ bl@0.9.3
│ │ └─┬ readable-stream@1.0.33
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├── caseless@0.8.0
│ ├─┬ combined-stream@0.0.7
│ │ └── delayed-stream@0.0.5
│ ├── forever-agent@0.5.2
│ ├─┬ form-data@0.2.0
│ │ ├── async@0.9.0
│ │ └─┬ mime-types@2.0.4
│ │   └── mime-db@1.3.1
│ ├─┬ hawk@1.1.1
│ │ ├── boom@0.4.2
│ │ ├── cryptiles@0.2.2
│ │ ├── hoek@0.9.1
│ │ └── sntp@0.2.4
│ ├─┬ http-signature@0.10.0
│ │ ├── asn1@0.1.11
│ │ ├── assert-plus@0.1.2
│ │ └── ctype@0.5.2
│ ├── json-stringify-safe@5.0.0
│ ├── mime-types@1.0.2
│ ├── oauth-sign@0.5.0
│ ├── qs@2.3.3
│ ├── stringstream@0.0.4
│ ├─┬ tough-cookie@0.12.1
│ │ └── punycode@1.3.2
│ └── tunnel-agent@0.4.0
├─┬ serve-favicon@2.1.7
│ ├─┬ etag@1.5.1
│ │ └── crc@3.2.1
│ ├── fresh@0.2.4
│ └── ms@0.6.2
├─┬ serve-static@1.7.1
│ ├── escape-html@1.0.1
│ ├── parseurl@1.3.0
│ ├─┬ send@0.10.1
│ │ ├── debug@2.1.0
│ │ ├── depd@1.0.0
│ │ ├── destroy@1.0.3
│ │ ├─┬ etag@1.5.1
│ │ │ └── crc@3.2.1
│ │ ├── fresh@0.2.4
│ │ ├── ms@0.6.2
│ │ ├─┬ on-finished@2.1.1
│ │ │ └── ee-first@1.1.0
│ │ └── range-parser@1.0.2
│ └── utils-merge@1.0.0
├─┬ stripe@3.0.2
│ ├── lodash@2.4.1
│ ├── qs@2.3.3
│ └── when@3.1.0
├─┬ stylus@0.49.3
│ ├── css-parse@1.7.0
│ ├─┬ debug@2.1.0
│ │ └── ms@0.6.2
│ ├─┬ glob@3.2.11
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.3.0
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ ├── mkdirp@0.3.5
│ ├── sax@0.5.8
│ └─┬ source-map@0.1.40
│   └── amdefine@0.1.0
├─┬ twit@1.1.18
│ └── oauth@0.9.9
└─┬ uploadfs@1.1.8
  ├── async@0.2.10
  ├─┬ gm@1.9.2
  │ ├── array-parallel@0.1.3
  │ ├── array-series@0.1.5
  │ ├── debug@0.7.0
  │ ├── stream-to-buffer@0.0.1
  │ └── through@2.3.6
  ├─┬ knox@0.8.10
  │ ├── debug@0.7.4
  │ ├── mime@1.2.11
  │ ├─┬ stream-counter@0.1.0
  │ │ └─┬ readable-stream@1.0.33
  │ │   ├── core-util-is@1.0.1
  │ │   ├── inherits@2.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ └─┬ xml2js@0.2.8
  │   └── sax@0.5.8
  ├── lodash@2.4.1
  ├── mkdirp@0.3.5
  ├─┬ request@2.12.0
  │ ├─┬ form-data@0.0.3
  │ │ ├── async@0.1.9
  │ │ └─┬ combined-stream@0.0.3
  │ │   └── delayed-stream@0.0.5
  │ └── mime@1.2.7
  └─┬ rimraf@2.0.3
    └── graceful-fs@1.1.14

**Comment by 3y3** [comment]
Use `node-debug app.js` instead of `node-inspector app.js`.
I recommend also to update to 0.8.3 (not related with your question)

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can provide any new information to help us with resolving the issue.
