### ISSUE TITLE
addStream does not reset haveNonRawStreams

### ISSUE THREAD

**Issue by msamblanet** [node-inspector/node-inspector#526]
If you dynamically add a stream to a logger using addStream, it does not reset haveNonRawStreams.  The result is if previously you only had raw streams, undefined is written to the new stream.

Work around is to add this after each call to addStream: logger.haveNonRawStreams = undefined; 

but would be nice if the logger did it automatically

**Comment by 3y3** [comment]
I'm not sure that this is node-inspector issue. Call me to reopen it, if I wrong here.

**Comment by msamblanet** [comment]
I'm sorry - I somehow posted this to the wrong git-hub repo...
