### ISSUE TITLE
Cannot get node-debug to mount to 0.0.0.0

### ISSUE THREAD

**Issue by duro** [node-inspector/node-inspector#538]
I am running my app inside a docker container. The Dockerfile is installing node-inspector. If I try and start my app using the following command:

```
node-debug --web-host 0.0.0.0 index.js
```

I get the following response

```
Node Inspector is now available from http://127.0.0.1:8080/debug?port=5858
Debugging `index.js`

debugger listening on port 5858
```

If I try using any other IP it works just fine.

**Comment by 3y3** [comment]
This is expected behavior for `node-debug` command
If you want to listen on `0.0.0.0` use `node-inspector` command [(uses `0.0.0.0` by default)](https://github.com/node-inspector/node-inspector#options).

```
$ node-inspector
$ node --debug-brk index.js
```

**Comment by tejasmanohar** [comment]
```
$ node-inspector --web-host 0.0.0.0
Node Inspector v0.12.6
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
```

maybe im doing something wrong? still says 127.0.0.1

**Comment by 3y3** [comment]
We can't propose to visit `http://0.0.0.0:8080/?port=5858` because it's an incorrect url for some (or all) browsers. But inspector should listen on `0.0.0.0` at this moment.

**Comment by tejasmanohar** [comment]
@3y3 Is it possible to bind the web server to 0.0.0.0 host even if we don't suggest the user to go there? In my case, this runs in a VM, and 0.0.0.0 is exposed at a public IP of the box so that I can access the server from my host machine, but the web server keeps binding to localhost- not 0.0.0.0.

**Comment by tejasmanohar** [comment]
To clarify, I'm fine with the node-inspector server binding to any port, but I'd like to bind the web server to 0.0.0.0 so that I can access it as it's exposed through the VM.

**Comment by 3y3** [comment]
@tejasmanohar , listening on 0.0.0.0 should work by design. Maybe it breaks somewhere in latest releases.
Can you submit that when you use
```
$ node-inspector --web-host 0.0.0.0
```
Node Inspector is not accessible on any host?
Can you also log for me `port` and `host` here https://github.com/node-inspector/node-inspector/blob/master/lib/debug-server.js#L135 ?

**Comment by sarancruzer** [comment]
I am running my app .If I try and start my app using the following command:

node --host 0.0.0.0 index.js
I can't access another machine
do you have any other solution


```
'use strict';
let app = require('express')();
let http = require('http').Server(app);
let io = require('socket.io')(http);

io.on('connection', (socket) => {
  console.log('The user is connected');

  socket.on('disconnect', function(){
    console.log('The user is disconnected');
  });

  socket.on('add-message', (message) => {
    io.emit('message', {type:'new-message', text: message});   
  });

  socket.on('add-record', (record) => {
    io.emit('getrecord', {type:'new-record', text: record});   
  });

});

//http.listen(5000, process.argv[2]);

http.listen(5000, () => {
  console.log('started on port 5000');
});
```

**Comment by hustxiaoc** [comment]
@sarancruzer , sorry I didn't get it, how does run `node --host 0.0.0.0 index.js` work ?
