### ISSUE TITLE
Installation hangs in Node 0.11.16

### ISSUE THREAD

**Issue by mzgol** [node-inspector/node-inspector#542]
```
$ node --version
v0.11.16
$ npm --version
2.5.0
npm -g install node-inspector  
 
> ws@0.4.32 install /Users/mgol/.nvm/v0.11.16/lib/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
```

At this point the process hangs forever.

I've tried with npm 2.4.1 - same. It works fine with Node 0.11.15.

**Comment by 3y3** [comment]
What?! I missed 0.11.16 release! Any way I've planned to close all compatibility questions (also io.js) on this weekend.

**Comment by cowabunga1** [comment]
hi 3y3, what about io.js support?

**Comment by bajtos** [comment]
io.js support: #523
Node v0.12 support: #554
Both platforms need #534 

I am closing this issue as a duplicate.
