### ISSUE TITLE
Crash when installing using node 0.12.0

### ISSUE THREAD

**Issue by jornare** [node-inspector/node-inspector#554]
My system is windows 8.1 x64 and the node-inspector installed fine on node 0.10.30.

I upgraded to node 0.12.0 and the installation now fails with the message
"Failed at the v8-profiler@5.2.3 install script 'node-pre-gyp install --fallback-to-build'"

I see from other posts that similar issues have existed before(https://github.com/node-inspector/node-inspector/issues/483) , and it seems to me you guys knows what it is an how to quickly fix it.

Let me know if you need further info.

**Comment by futurechan** [comment]
:+1:

**Comment by SpikedPunchVictim** [comment]
Also crashing when installing. Essentially not being able to find 'lstat' on a Windows machine. Here's more info if it helps:
....
10384 info preuninstall v8-debug@0.3.4
10385 info uninstall v8-debug@0.3.4
10386 verbose false,C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules,C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules\node-inspector\node_modules unbuild v8-debug@0.3.4
10387 info postuninstall v8-debug@0.3.4
10388 verbose about to build C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules\node-inspector
10389 info C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules\node-inspector unbuild
10390 info preuninstall node-inspector@0.8.3
10391 info uninstall node-inspector@0.8.3
10392 verbose true,C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules,C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules unbuild node-inspector@0.8.3
10393 verbose C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools,[object Object] binRoot
10394 info postuninstall node-inspector@0.8.3
10395 error Error: ENOENT, lstat 'C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules\lru-cache\test\foreach.js'
10395 error     at Error (native)
10396 error If you need help, you may report this *entire* log,
10396 error including the npm and node versions, at:
10396 error     <http://github.com/npm/npm/issues>
10397 error System Windows_NT 6.1.7601
10398 error command "C:\\ProgramData\\chocolatey\\lib\\nodejs.commandline.0.12.0\\tools\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm.1.4.9\\tools\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "node-inspector"
10399 error cwd C:\Jenkins\workspace\QE Reoccuring Front End Tests
10400 error node -v v0.12.0
10401 error npm -v 1.4.9
10402 error path C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules\lru-cache\test\foreach.js
10403 error fstream_path C:\ProgramData\chocolatey\lib\nodejs.commandline.0.12.0\tools\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules\lru-cache\test\foreach.js
10404 error fstream_type File
10405 error fstream_class FileWriter
10406 error code ENOENT
10407 error errno -4058
10408 error fstream_stack C:\ProgramData\chocolatey\lib\npm.1.4.9\tools\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
10408 error fstream_stack FSReqWrap.oncomplete (fs.js:99:15)
10409 verbose exit [ -4058, true ]

**Comment by alanhortz** [comment]
I have exactly  the same issue on OSX Yosemite running node 0.12

**Comment by Michael00767** [comment]
I seem have the sam problem in centos 7 && node 0.12
node-pre-gyp install --fallback-to-build

**Comment by burmisov** [comment]
Experiencing the same issue on both Win 8.1 and OSX Yosemite

**Comment by ChrisRus** [comment]
+1 on Debian (wheezy) attempting to configure joyent/node#v0.12.0-released + node-inspector/node-inspector#master

extract from npm-debug.log:

10763 info install express@4.11.2
10764 info postinstall express@4.11.2
10765 verbose unlock done using /root/.npm/_locks/express-6c41b0b03b8365ce.lock for /usr/local/lib/node_modules/node-inspector/node_modules/express
10766 verbose unsafe-perm in lifecycle false
10767 info postinstall ws@0.4.32
10768 verbose unlock done using /root/.npm/_locks/ws-198654e8e668eb7b.lock for /usr/local/lib/node_modules/node-inspector/node_modules/ws
10769 info v8-profiler@5.2.3 Failed to exec install script
10770 verbose unsafe-perm in lifecycle false
10771 verbose unlock done using /root/.npm/_locks/v8-profiler-28e1233ba4356e59.lock for /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
10772 info postinstall v8-debug@0.3.5
10773 verbose unlock done using /root/.npm/_locks/v8-debug-228c9e2afaa20658.lock for /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
10774 verbose about to build /usr/local/lib/node_modules/node-inspector
10775 verbose unlock done using /root/.npm/_locks/node-inspector-885d0a05b8e6718d.lock for /usr/local/lib/node_modules/node-inspector
10776 verbose stack Error: v8-profiler@5.2.3 install: `node-pre-gyp install --fallback-to-build`
10776 verbose stack Exit status 1
10776 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10776 verbose stack     at EventEmitter.emit (events.js:110:17)
10776 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10776 verbose stack     at ChildProcess.emit (events.js:110:17)
10776 verbose stack     at maybeClose (child_process.js:1008:16)
10776 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10777 verbose pkgid v8-profiler@5.2.3
10778 verbose cwd /home/cdr/devenv
10779 error Linux 3.2.0-4-amd64
10780 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "./node-inspector"
10781 error node v0.12.0
10782 error npm  v2.5.1
10783 error code ELIFECYCLE
10784 error v8-profiler@5.2.3 install: `node-pre-gyp install --fallback-to-build`
10784 error Exit status 1
10785 error Failed at the v8-profiler@5.2.3 install script 'node-pre-gyp install --fallback-to-build'.
10785 error This is most likely a problem with the v8-profiler package,
10785 error not with npm itself.
10785 error Tell the author that this fails on your system:
10785 error     node-pre-gyp install --fallback-to-build
10785 error You can get their info via:
10785 error     npm owner ls v8-profiler
10785 error There is likely additional logging output above.
10786 verbose exit [ 1, true ]
10787 verbose unbuild lib/node_modules/node-inspector/node_modules/v8-profiler
10788 info preuninstall v8-profiler@5.2.3
10789 info uninstall v8-profiler@5.2.3

I have the full log if useful. Thanks, Chris

**Comment by bajtos** [comment]
A possible workaround: downgrade to 0.7.x.

```
npm install -g node-inspector@0.7
```

**Comment by ChrisRus** [comment]
fwiw node 0.11.3 + node-inspector@0.7 seems to be working well for me. thanks!

**Comment by iliakan** [comment]
Wasn't that fixed for 0.9?

**Comment by geekf** [comment]
This worked for me (logged in as root):
npm install -g --unsafe-perm node-inspector

For me, the issue seems to be build step of ws library done by node-gyp

**Comment by joyeecheung** [comment]
Node v0.12.0 and Windows 8.1 here, also hanged when building ws. `npm install -g --unsafe-perm node-inspector` did the trick, thanks.

**Comment by 3y3** [comment]
Please try to reproduce this on node-inspector 0.10.1

**Comment by 3y3** [comment]
This issue is very outdated and I think it was solved by lot of commits in node, v8-debug, v8-profiler and node-inspector.
If there still exist problems with node-inspector installation, please open new issue.
