### ISSUE TITLE
Black boxing scripts in Chrome Dev tools

### ISSUE THREAD

**Issue by bmcminn** [node-inspector/node-inspector#555]
Chrome Version 40.0.2214.111 (64-bit)

---

Chrome dev tools lacks ability to black box scripts I don't wish to step through. Not sure if this is a flag lacking in the dev tools instance that node inspector invokes, however this is an inconvenience.

**Comment by bajtos** [comment]
Use the config option `--hidden`, see [README](https://github.com/node-inspector/node-inspector/blob/master/README.md#how-do-i-specify-files-to-hide) for more details.
