### ISSUE TITLE
Node v11 and v12 --debug-brk doesn't work

### ISSUE THREAD

**Issue by jaslo** [node-inspector/node-inspector#558]
With Node v0.11.x and Node v12 using node-debug or node-inspector as a separate process, --debug-brk doesn't break before the first statement, it starts running the node process immediately.

**Comment by compcj** [comment]
Got the same issue, for me, it seems that the breakpoint works until the node-inspector GUI is opened. Once the GUI is opened, the code is automatically continued.
My environment:
Node.js 0.12.0, node-inspector 0.8.3, CentOS 6.5 x64, browser is chromium 40 x64.

**Comment by dazhazit** [comment]
I think this might be a change in node causing the problem. "node debug <script>" works OK with a REPL.

**Comment by JoshuaToenyes** [comment]
**+1** – I'm experiencing the same issue.

**Comment by Wandalen** [comment]
+1

**Comment by sundeepnarang** [comment]
+1

**Comment by bORm** [comment]
+1

**Comment by 3y3** [comment]
Duplication of https://github.com/node-inspector/node-inspector/issues/534
