### ISSUE TITLE
Hangs on directory structures with infinite recursion

### ISSUE THREAD

**Issue by Alxandr** [node-inspector/node-inspector#565]
When building a tool that builds itself, I've set up symlinks from `$/node_modules/name` to `$`. This, means that I have infinite recursion in my filesystem. It all works fine and dandy, until I launch `node-debug name`. I've identified that the problem originates in `findAllApplicationScripts`, because by modifying that to always take the `_noPreload` path, the problem goes away (I just changed the `if` to `if (this._noPreload || true)`). For some reason, I'm unable to set this flag from the command line (tried `--no-preload`, `--preload=false` and others).

Anyways, my point is that the directory scanner should probably make sure that symlinks doesn't point back to a already scanned directory.

**Comment by bajtos** [comment]
This should have been fixed by https://github.com/node-inspector/node-inspector/pull/551 (released in v0.9.0).

Please reopen if the problem persists in the latest version.
