### ISSUE TITLE
Use Notification API on hitting breakpoints

### ISSUE THREAD

**Issue by wdbacker** [node-inspector/node-inspector#566]
A very handy feature would be that during debugging in Chrome, the browser automatically can activate the tab where node-inspector is running when e.g. a breakpoint is encountered in the code.

I found something to do this using a chromium extension:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/x36zW3QsF0g

Or from the docs in the Chrome tabs API:
https://developer.chrome.com/extensions/tabs#method-update

Do you think this would be possible to implement in node-inspector without a lot of coding?

**Comment by bajtos** [comment]
Hi @wdbacker, I am not familiar with Chrome extensions and tabs API enough to provide any meaningful advice. I am willing to accept this feature if somebody contributes the implementation though.

**Comment by wdbacker** [comment]
Hi @bajtos, I just tried out some possible solutions for this feature. I came across a very obvious solution: if the node-inspector page encounters an active breakpoint, the node-inspector's javascript code can just do an alert('breakpoint encountered'); in the javascript code, and the Chrome browser will automatically switch to the node-inspector tab!

Btw, it would be handy if you can enable/disable this alert with a config option e.g. in the settings.

**Comment by bajtos** [comment]
> If the node-inspector page encounters an active breakpoint, the node-inspector's javascript code can just do an alert('breakpoint encountered'); in the javascript code, and the Chrome browser will automatically switch to the node-inspector tab!

But then you have to close the alert window before you can continue your work, right? In my opinion, this would be very annoying, especially if the alert is raised even while the debugger tab is active.

**Comment by wdbacker** [comment]
Yes, you'll have to press "Enter" on the alert once. But you're right, we need one more thing - checking if the debugging window is hidden:

if (document.visibilityState && (document.visibilityState === 'hidden'))
  alert('breakpoint encountered');

Now the alert is triggered only once and will not be annoying anymore.

Btw, the visibility API is supported starting from Chrome 13:
https://developers.google.com/chrome/whitepapers/pagevisibility

**Comment by bajtos** [comment]
ok, the proposal looks reasonable now.

@3y3 what do you think?

**Comment by 3y3** [comment]
Be carefull - this realisation stuns websocket connection.
At first glance on current stage of our debugging protocol this will work safely.

The other thing  - this needs to be a configurable behavior.

**Comment by wdbacker** [comment]
Hi @bajtos @3y3, I found a much more elegant solution. As node-inspector needs Chrome or Opera in order to work, I found there is a new desktop notification API now.

Advantages:
- notification is much more discrete
- alert() blocks the javascript event loop, the new notification doesn't
- no configuration needed in node-inspector, user simply (dis)allows notification once

I made a small demo page with script code that can be used immediately for node-inspector too.

To see how this works, go to my demo page http://srm.stabe.be/ and click on the button. After 5 seconds, Chrome will ask once if you want to allow desktop notifications for this "website". If you press "allow", the notification will be displayed bottom-right.

Now push the same button a second time and immediately switch to another window/tab in Chrome. After 5 seconds, you'll see the notification bottom-right and you can click on it. You'll be taken immediately to the node-inspector tab!

What do you think?

**Comment by 3y3** [comment]
Notification API will be best solution! :+1: 

I saw it in work on Gitter - it's very useful.

@bajtos ?

**Comment by bajtos** [comment]
Sounds good.

**Comment by wdbacker** [comment]
@bajtos @3y3 Can you point me in the right direction in the Node Inspector's source code so that I can prepare a pull request for this notification functionality? Thx!

**Comment by johnrnelson** [comment]
Can I throw in a :+1: on this?

**Comment by 3y3** [comment]
Fixed in ca58013de3579665812dbeef403aae461ce7c08b

Well be released in 0.11.0
