### ISSUE TITLE
 Synchronous XMLHttpRequest on the main thread is deprecated.

### ISSUE THREAD

**Issue by zhoukekestar** [node-inspector/node-inspector#579]
In utilities.js
------------------------------->
function importScript(scriptName)
{
    if (_importedScripts[scriptName])
        return;
    var xhr = new XMLHttpRequest();
    _importedScripts[scriptName] = true;
    xhr.open("GET", scriptName, false);   --> Line No. 1297
<----------------------------------------

Chrome 40.0.2214.111 m, OS: windows xp
On my chrome's console, it shows:
utilities.js:1297 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

So, I got a problem.
UI doesn't load or doesn't work and refresh didn't help.
Yeah, i'm sure that i do have adblock disabled as well as any other content blocking scripts and plugins.
Does it matter?

**Comment by bajtos** [comment]
I believe the problem was already fixed on the master branch via #492. Please try `npm install -g node-inspector/node-inspector` and reopen the issue if the problem persists.
