### ISSUE TITLE
Cannot generate heap snapshot. Stuck on "building postorder index"

### ISSUE THREAD

**Issue by Zysen** [node-inspector/node-inspector#585]
After upgrading to 0.9.2 i can no longer generate heap snapshots. i get stuck on "building postorder index". 

Using node 0.11.16

![node-inspector-bug](https://cloud.githubusercontent.com/assets/1712244/6628423/42a53b86-c96a-11e4-9ded-ae6a7b6cf84b.png)

**Comment by bajtos** [comment]
Node Inspector did not support versions newer than v0.11.13 until recently. Please install from the latest master and reopen this bug if the problem still persists.

```
$ npm install -g node-inspector/node-inspector
```

**Comment by 3y3** [comment]
0.10.0 released. Try it.
