### ISSUE TITLE
Can't start mocha 2.2.0 with node-debug on Windows 7 (git bash) with old npm version

### ISSUE THREAD

**Issue by jakub-g** [node-inspector/node-inspector#587]
**I'm opening this issue for reference (maybe someone will face the same problem soon - feel free to close it immediately)**

I followed the advice from README on debugging mocha - I run `node-debug _mocha` for that

However there was a really weird issue happening for me (I used node 0.10.37 or 0.12 via nodist, npm 1.4.6, Windows 7)

Node Inspector works with mocha 2.1.0 but not 2.2.0 and it's really strange.

 **TL;DR if you're on Windows, update npm (using cmd, not git bash!) with `npm install -g npm`** 
--------------------------------------------

With 2.2.0 I get the following error:

```
$ node-debug _mocha
Node Inspector is now available from http://127.0.0.1:8080/debug?port=5858
Debugging `_mocha`

Debugger listening on port 5858
d:\bin\nodist\bin\_mocha.CMD:1
e, module, __filename, __dirname) { "%~dp0\node_modules\mocha\bin\_mocha"   %*
                                                                             ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)
    at Timer.listOnTimeout (timers.js:110:15)
```

Let's run the following commands to see the difference:
```
$ npm install -g mocha@2.1.0 --silent
$ cat $(npm get prefix)\\_mocha.cmd
$ npm install -g mocha@2.2.0 --silent
$ cat $(npm get prefix)\\_mocha.cmd
```

```
$ npm install -g mocha@2.1.0 --silent
D:\bin\nodist\bin\mocha -> D:\bin\nodist\bin\node_modules\mocha\bin\mocha
D:\bin\nodist\bin\_mocha -> D:\bin\nodist\bin\node_modules\mocha\bin\_mocha
mocha@2.1.0 D:\bin\nodist\bin\node_modules\mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

$ cat $(npm get prefix)\\_mocha.cmd
```

<pre><b>
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\mocha\bin\_mocha" %*
) ELSE (
  node  "%~dp0\node_modules\mocha\bin\_mocha" %*
)
</b></pre>

```
$ npm install -g mocha@2.2.0 --silent
D:\bin\nodist\bin\_mocha -> D:\bin\nodist\bin\node_modules\mocha\bin\_mocha
D:\bin\nodist\bin\mocha -> D:\bin\nodist\bin\node_modules\mocha\bin\mocha
mocha@2.2.0 D:\bin\nodist\bin\node_modules\mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── supports-color@1.2.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
$ cat $(npm get prefix)\\_mocha.cmd
```

<pre><b>
"%~dp0\node_modules\mocha\bin\_mocha"   %*
</b></pre>

It seems to be a weird bug of old npm versions in work. I updated to latest as of today, reinstalled mocha and it solved the issue.

**Comment by bajtos** [comment]
Thanks for sharing the problem and the solution. I am closing the issue as resolved.

Feel free to submit a patch if you think it will be useful to include some part of this info in README too.
