### ISSUE TITLE
Profiler output can not be exported

### ISSUE THREAD

**Issue by salomvary** [node-inspector/node-inspector#590]
Clicking save doesn't do anything:

![screenshot 2015-03-20 16 17 42](https://cloud.githubusercontent.com/assets/193923/6754448/e1f4d8ce-cf1c-11e4-9ff2-d47122fd0014.png)

Node Inspector v0.9.2
Node v0.11.13

**Comment by 3y3** [comment]
Fixed in `0.10.0` release. Reopen this bug if the problem still persists for you.
