### ISSUE TITLE
Problem with Node 0.12.0

### ISSUE THREAD

**Issue by IliaIdakiev** [node-inspector/node-inspector#592]
Not working with errors: 

`parseFile()` is deprecated. Use `parseString()` instead.
`parseString()` is deprecated. It's not actually async. Use `parse()` instead.

**Comment by bajtos** [comment]
Where do you see the errors? How can we reproduce the problem on our machines?

**Comment by 3y3** [comment]
I think this error related with globally installed `express`.
So I don't think that `^` modificator is a good strategy for `express` dependency.

**Comment by bajtos** [comment]
I installed the latest express and it does not print these warnings for me. Therefore I don't think this is related to `^` operator used in the express dependency version in node-inspector.

**Comment by 3y3** [comment]
Please try to reproduce this on node-inspector 0.10.1

**Comment by IliaIdakiev** [comment]
After I updated globally installed packages the error disappeared. Thanks.
