### ISSUE TITLE
Feature/idea: Color coding in console log

### ISSUE THREAD

**Issue by LiamKarlMitchell** [node-inspector/node-inspector#595]
Node Inspector v0.9.1
Node v0.12.0
Windows 7 64bit

For some outputs I am using console.log with '[31;1m' and various other ANSI escape sequences for formatting color.

````
console.log('[31;1mThis should be red:[0m')
````

It would be interesting if these could be used in the console on node-debug rather than outputing [31;1m as part of the string.

Could be done with span tags and inline css or a class.

I am tempted to do just the foreground and background colors.

Any advice/comments/objections?

**Comment by bajtos** [comment]
AFAIK, [debug](https://www.npmjs.com/package/debug) supports color output in browser console too, it may be a good source of inspiration.

**Comment by 3y3** [comment]
Duplicates #502

**Comment by LiamKarlMitchell** [comment]
Sure im happy for it to be a plugin feature :)

**Comment by bajtos** [comment]
Closing as a duplicate then.
