### ISSUE TITLE
Feature request: Node-inspector as an IDE

### ISSUE THREAD

**Issue by m1sta** [node-inspector/node-inspector#596]
node-inspector is one of very few application which support node.js debugging with sourcemaps. Would it be difficult to tweak it so that node-inspector can be used to actually *write* code (ie. as an IDE)?

**Comment by mrotaru** [comment]
Well there's `--save-live-edit`, which lets you save changes you make in node-inspector.

**Comment by bajtos** [comment]
We have hardly enough time to maintain the current set of features provided by Node Inspector, building a full IDE is way beyond our possibilities.
