### ISSUE TITLE
node-debug fails to stop on first line of code, v0.9.2 & 0.8.3 / node 0.12.1

### ISSUE THREAD

**Issue by mattkime** [node-inspector/node-inspector#597]
i'm unable to get it to break. anything i can do to supply more info?

thanks.

-- 

i should note that i had no trouble under node v0.10.21 and node-inspector v0.7.3

**Comment by mattkime** [comment]
resolved by reverting to node v0.11.13 and node-inspector v0.7.3

seems like there's a lot of discussion of this problem.

**Comment by 3y3** [comment]
Fixed in 0.10.1
