### ISSUE TITLE
The inspector not work if run with option "--debug-brk" 

### ISSUE THREAD

**Issue by BenBBear** [node-inspector/node-inspector#598]
origin question is here: [http://stackoverflow.com/questions/29371262/what-is-the-difference-between-node-debug-index-js-and-run-node-inspector-th](http://stackoverflow.com/questions/29371262/what-is-the-difference-between-node-debug-index-js-and-run-node-inspector-th) 

If run node with `--debug-brk` to attach to the inspector, then I could not set breakpoints and `debugger` being ignored.  

But if use `node --debug`, then the inspector works perfectly. :) 

The problem appears in osx 10.10.2.

**Comment by bajtos** [comment]
What is your Node.js version? There is a known issue #534 that `--debug-brk` does not work correctly in Node v0.12 and io.js 1.x.

**Comment by BenBBear** [comment]
my node is v0.12 :O

sorry for the duplicate issue :)





在 2015年4月1日 下午3:24:19, Miroslav Bajtoš (notifications@github.com) 写到:

What is your Node.js version? There is a known issue #534 that --debug-brk does not work correctly in Node v0.12 and io.js 1.x.

**Comment by bajtos** [comment]
No worries, I am closing this as a duplicate then.
