### ISSUE TITLE
problem with node 0.12.0

### ISSUE THREAD

**Issue by javie007** [node-inspector/node-inspector#602]
I use nvm to manage many node, but when I open the browser,it reports this problem:
	
	Your Node version (undefined) has a partial support of profiler.
	The stack frames tree doesn't show all stack frames due to low sampling rate.
	The profiling data is incomplete and may show misleading results.
	Update Node to 0.11.13 or newer to get full support.

	Error: Cannot find module '/Users/cmw/.nvm/v0.12.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.2/node-v11-darwin-ia32/debug.node'

**Comment by 3y3** [comment]
Fixed in `0.10.0` release.
