### ISSUE TITLE
Not stopping on first line

### ISSUE THREAD

**Issue by EmbeddedMike** [node-inspector/node-inspector#606]
I've just upgraded to Node Inspector v0.9.2  from version 0.7.4

I've also just upgraded from node 10.26 to 12.2

My command line is

`node-debug --web-host localhost --no-preload server.js`

It no longer stops on the first line

I've tried adding --debug-brk to the command, but it does not do anything

**Comment by 3y3** [comment]
Fixed in `0.10.0` release. Reopen this bug if the problem still persists for you.
