### ISSUE TITLE
Possible to preload .ts files so i can set breakpoints before require is executed ?

### ISSUE THREAD

**Issue by binarysqueeze** [node-inspector/node-inspector#607]
Hi,

I notice preloading is done on js files, would this be possible for ts (typescript) files?

When i first enter I see my main.js and my main.ts so this is great.

my main.js does a require on child,  child has 2 files .. ts (typescript) and js(compiled version).  child.js is displayed straight away but child.ts only comes into the source view when the require is executed.

I would like to point out, everything is working as expected with regards to debugging ts files with the sourcemaps, just the list on the left is not preloaded with ts files.

any ideas?

Thanks

**Comment by bajtos** [comment]
> child.js is displayed straight away but child.ts only comes into the source view when the require is executed.

This is a limitation of the current implementation of Chrome DevTools and Node.js (io.js), there isn't any easy way to fix this.

Workaround: set the breakpoint in the js file. IIRC, then UI will "move" the breakpoint to the "ts" file for you immediately after the js file is loaded.
