### ISSUE TITLE
Install fails on OS X Yosemite

### ISSUE THREAD

**Issue by exceptDefeat** [node-inspector/node-inspector#608]
Not sure if I should file this against npm or not, even though the output clearly say to.

MacBook-Pro:web_rtc joey$ npm install node-inspector
npm http GET https://registry.npmjs.org/node-inspector
npm http 304 https://registry.npmjs.org/node-inspector
npm http GET https://registry.npmjs.org/serve-favicon
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/rc
npm http GET https://registry.npmjs.org/strong-data-uri
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/biased-opener
npm http GET https://registry.npmjs.org/yargs
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/v8-profiler
npm http GET https://registry.npmjs.org/v8-debug
npm http GET https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/serve-favicon
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/rc
npm http 304 https://registry.npmjs.org/strong-data-uri
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/biased-opener
npm ERR! Error: No compatible version found: serve-favicon@'^2.1.1'
npm ERR! Valid install targets:
npm ERR! ["2.0.0","2.0.1","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4","2.1.5","2.1.6","2.1.7","2.2.0"]
npm ERR!     at installTargetsError (/usr/local/Cellar/node/0.10.12/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/local/Cellar/node/0.10.12/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/usr/local/Cellar/node/0.10.12/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.12/bin/node" "/usr/local/bin/npm" "install" "node-inspector"
npm ERR! cwd /absolute/path/to/web_rtc
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/v8-profiler
npm http 304 https://registry.npmjs.org/v8-debug
npm http 304 https://registry.npmjs.org/semver
npm http 200 https://registry.npmjs.org/yargs
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!  /absolute/path/to/web_rtc/npm-debug.log
npm ERR! not ok code 0

**Comment by fernandoneto** [comment]
@exceptDefeat try to update your node version and npm . 
take a look at [n](https://www.npmjs.com/package/n) or [nvm](https://github.com/creationix/nvm)

**Comment by 3y3** [comment]
This is a problem with npm itself. Update your npm version.
