### ISSUE TITLE
Error occurs but no meaningful stack or meta provided

### ISSUE THREAD

**Issue by cdaringe** [node-inspector/node-inspector#611]
This is could likely be due to the async nature of some promisy code, but consider the below screenshot:

![screen shot 2015-04-14 at 11 06 51 am](https://cloud.githubusercontent.com/assets/1003261/7143894/d44d110e-e296-11e4-9f00-0f53c512fd8a.png)

somewhere/sometime, an error occured.  node-inspector breaks here, which is doesn't leave the user with an indication of what has occurred or how to proceed.  perhaps some annotations or explanation in that block could be helpful?

**Comment by johnmarkos** [comment]
I'm not sure how to reproduce this. Is there publicly-available code on which this error occurs?

**Comment by cdaringe** [comment]
hi @johnmarkos, i posted one unreliable condition which produces this in the #613 thread.  the code that leads to that condition above isn't open-sourced yet, otherwise I would have slapped up a gist!  however, i will spend some more time trying to reproduce its conditions if #613 isn't sufficient

**Comment by 3y3** [comment]
#613 describe this error more verbose.
