### ISSUE TITLE
Roadmap or something?

### ISSUE THREAD

**Issue by iliakan** [node-inspector/node-inspector#614]
Hi,

There are quite serious issues with node-inspector on recent iojs/nodejs versions. Especially with iojs, it has problems with installation and debugging (debug-brk).

Node-inspector used to be my main instrument for debugging, and I kind of lack it. 

Dear devs, please tell us, what is going on? Is there any light ahead? Maybe you're refactoring things from the ground up? Or you're busy with other projects and we shouldn't await any changes soon?

Thanks for the great tool!

**Comment by 3y3** [comment]
Hello @iliakan .

So, today I merged new frontend and I wait some small changes from @marcominetti .
Now then we have new frontend, it is reasonable to extend our functionality by debugging promises, getters/setters and more other. This is a next big step. #450

From small steps:
There is a #560 , that fixes #597, and I hope, it will be merged on next week. (Can you test it and submit what it works?)

Released 0.12.0 with new debugger system is a big problem not only for node inspector, but also for node (I opened 3 issues in node iojs/io.js/issues/858, iojs/io.js/issues/781). We have some native features `v8-debug` and `v8-profiler` that already compatible with `iojs` on compilation stage, but breaks compatibility on running from `node-debug` command on windows (iojs/io.js/issues/751)

**Comment by 3y3** [comment]
Also we started discussion about new cli api and plugin system. #578 
We communicate with @marcominetti in plugin system feature. Long time we were blocked for new features by `updating frontend` pr.

In other words I work on node-inspector so intensively as it is possible - this is my main os project. Sometimes it has a higher priority than my main job =)

**Comment by iliakan** [comment]
@3y3 thanks, so great to hear that node-inspector will shine once again soon :+1:
