### ISSUE TITLE
node-inspector@0.9.2 --hidden broken

### ISSUE THREAD

**Issue by scitecwri** [node-inspector/node-inspector#619]
--hidden='["xxxxxxx"]' acts like /.*/ but for node-internal modules and the loaded module

**Comment by bajtos** [comment]
@scitecwri thank you for reporting the issue. I am afraid I don't understand the problem you are experiencing. Can you please add more details and describe steps how to reproduce the problem?

**Comment by 3y3** [comment]
No feedback for long time.
Feel free to reopen it.
