### ISSUE TITLE
FYI: Error message on exit ('Assertion failed') - did not affect session

### ISSUE THREAD

**Issue by colingoldberg** [node-inspector/node-inspector#623]
FYI:

With the new version 'Node Inspector v0.10.0'

I got an error message after I ran to the end of a script.

'Assertion failed: ((err) == (0)), function Stop, file ../deps/debugger-agent/src/agent.cc, line 164.'

It did not seem to affect the debugging session.

Colin G

**Comment by bajtos** [comment]
What is your Node (or io.js) version?

**Comment by colingoldberg** [comment]
$ node -v
v0.12.0

**Comment by bajtos** [comment]
Thanks. I believe this is a problem in Node itself, see [deps/debugger-agent/src/agent.cc#L164](https://github.com/joyent/node/blob/v0.12.0/deps/debugger-agent/src/agent.cc#L164). Please upgrade to a newer Node version, e.g. 0.12.2 and open an issue in Node's tracker if the problem persist.
