### ISSUE TITLE
redirects to broken URL (v0.10.0)

### ISSUE THREAD

**Issue by david-knipe-hp** [node-inspector/node-inspector#625]
When I try to run node-inspector v0.10.0, it gives me an HTTP 302: Moved Temporarily. It redirects to [object Object] , which of course isn't a real URL. v0.9.2 works fine.

**Comment by 3y3** [comment]
@david-knipe-hp , thanks for bug report. I pushed a commit that fixes this small bug, so this will be completely fixed in 0.10.1.

As a workaround you can use link that printed in node-inspector terminal on startup.

**Comment by 3y3** [comment]
Closed by 36c246acb36950aa08afa7599a1e21533cb94430
