### ISSUE TITLE
[0.10.0] WebSocket dependency 'ws' is way out of date

### ISSUE THREAD

**Issue by clintwood** [node-inspector/node-inspector#629]
Trying to figure why the WebSocket lib `ws` version in the dependencies is not being bumped from `"~0.4.31"` to latest `"^0.7.1"` for recent builds.

On Windows platform the older version has a build error while the later version works fine.

**Comment by 3y3** [comment]
Fixed in 0.10.1

**Comment by clintwood** [comment]
Magic!
