### ISSUE TITLE
Wrong version of node-darwin?

### ISSUE THREAD

**Issue by emburns** [node-inspector/node-inspector#632]
When I run `node-debug` on my app, I get the following error in the node-inspector console:

    Error: Cannot find module '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.1/node-v14-darwin-x64/debug.node'

Sure enough, the `node-v14-darwin-x64` folder doesn't exist, though I have a `node-v11-darwin-x64` folder.

Edit: I copied the darwin folder over to `node-v14-darwin-x64` just to see if that would work, but then I get the following error: `Error: Module did not self-register.`

**Comment by 3y3** [comment]
Please try to completely reinstall node-inspector. I think you use node 0.12.2.
I updated v8-debug version to `0.4.3` easterday. This version can solve your problem. (I see that your current installed version is 0.4.1)
I'm very wait feedback from you.

**Comment by emburns** [comment]
Awesome.  I think that got me farther.  Now I'm just getting that 'Error: Module did not self-register'.  I'm thinking that might be from one of the modules I'm including in my server?  Any idea what could be causing that?

**Comment by 3y3** [comment]
This is an error for native modules like v8-debug. I wonder to see stack trace for this error.

**Comment by emburns** [comment]
Do you have any advice on how I could get a stack trace for it?  Unfortunately, it just shows up in the log of node-inspector when it first loads.  It doesn't give me a line number or anything that would give me a hint of where to put a breakpoint.

**Comment by 3y3** [comment]
I think stack trace will not be helpful at current time.
Are you using
```
npm uninstall -g node-inspector
npm install -g node-inspector
```
for complete reinstallation of node-inspector? (Any way please try it again. I wonder to see install log, if reinstallation doesn't resolves problem)

Which is your current nodejs version?
Do you have installed iojs?

**Comment by i5ting** [comment]
node 0.12.2
 v8-debug 0.4.4

```
Runtime.getProperties failed.
Object #-3# not found
```

**Comment by i5ting** [comment]
```
➜  expressdemo          sudo npm uninstall -g node-inspector
unbuild node-inspector@0.10.0
➜  expressdemo  sudo npm install -g node-inspector
 
> v8-profiler@5.2.7 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
>  

 
> v8-debug@0.4.4 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
>  

 
> ws@0.4.32 install /usr/local/lib/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.5"})
/
> v8-debug@0.4.4 postinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.4/node-v14-darwin-x64/debug.node" is installed via remote

> v8-profiler@5.2.7 postinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.7/node-v14-darwin-x64/profiler.node" is installed via remote
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js
/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js
node-inspector@0.10.0 /usr/local/lib/node_modules/node-inspector
├── async@0.9.0
├── semver@3.0.1
├── yargs@1.3.3
├── debug@1.0.4 (ms@0.6.2)
├── strong-data-uri@0.1.1 (truncate@1.0.4)
├── rc@0.5.5 (strip-json-comments@0.1.3, deep-extend@0.2.11, ini@1.3.3, minimist@0.0.10)
├── which@1.1.1 (is-absolute@0.1.7)
├── serve-favicon@2.2.0 (fresh@0.2.4, ms@0.7.0, parseurl@1.3.0, etag@1.5.1)
├── glob@4.5.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.7)
├── express@4.12.3 (merge-descriptors@1.0.0, cookie-signature@1.0.6, utils-merge@1.0.0, methods@1.1.1, cookie@0.1.2, fresh@0.2.4, escape-html@1.0.1, range-parser@1.0.2, content-type@1.0.1, finalhandler@0.3.4, vary@1.0.0, parseurl@1.3.0, serve-static@1.9.2, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.1, qs@2.4.1, debug@2.1.3, etag@1.5.1, proxy-addr@1.0.8, on-finished@2.2.1, send@0.12.2, accepts@1.2.7, type-is@1.6.2)
├── ws@0.4.32 (tinycolor@0.0.1, options@0.0.6, commander@2.1.0, nan@1.0.0)
├── biased-opener@0.2.5 (opener@1.4.1, minimist@1.1.0, x-default-browser@0.3.0, browser-launcher2@0.4.5)
├── v8-debug@0.4.4 (nan@1.8.4, node-pre-gyp@0.6.7)
└── v8-profiler@5.2.7 (nan@1.8.4, node-pre-gyp@0.6.7)
➜  expressdemo  
```

**Comment by 3y3** [comment]
@emburns , if your problem doesn't solved please read https://github.com/node-inspector/node-inspector/issues/631

**Comment by emburns** [comment]
@3y3 another uninstall/reinstall seems to have fixed the problem.  Thank you very much!

**Comment by mschipperheyn** [comment]
I have a similar problem. I see the error 
Cannot find module '/Users/ms/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.3/node-v47-darwin-x64/debug.node' but the installed directory is 
 /Users/ms/.nvm/versions/node/v6.1.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.3/node-v48-darwin-x64/

I reinstalled nvm, node, node-inspector and v8-debug

**Comment by wzr1337** [comment]
+1 for @mschipperheyn .. same here:

node-v11-darwin-x64 found, node-v47-darwin-x64 expected

node 5.5.0

**Comment by dadakoko** [comment]
after 
>npm cache clean
>npm uninstall -g node-inspector
>npm i -g node-inspector

node-v46-darwin-x64 found but node-v48-darwin-x64 is expected...

i m using node 6.0.0.
Node Inspector v0.12.8

It results that when node-inspector is running any request to my node app is hanging forever...

thx for any feedback.

**Comment by tankala** [comment]
Hi,

I got the similar problem but with v8-profiler.
"Error: Cannot find module './build/profiler/v5.7.0/node-v48-linux-x64/profiler.node' on 5.7.0
After spending some time with that figured out that I am using **node v7.10.1** at the time of installation and at the time of running the application I am using **node v6.11.4**.

I uninstalled v8-profiler and used **node v6.11.4** using **nvm** then installed v8-profiler again. Problem solved.
