### ISSUE TITLE
Layout Breaking up when Select Console tab

### ISSUE THREAD

**Issue by felipekm** [node-inspector/node-inspector#635]
Not sure if it is only happening to me but when I hit "console" the screen gets like this below making hard to select the other tabs (Profiles, Sources)

![image](http://i.imgur.com/MtB3MIc.gif)

Thanks

**Comment by 3y3** [comment]
Emm. Do you have any extension, which can modify styles?

**Comment by felipekm** [comment]
Sure not, my chrome is basically naked on that

**Comment by 3y3** [comment]
There https://github.com/node-inspector/node-inspector/issues/630 is a screen of how to should look upper panel.
Maybe you have low resolution? 800x600? =)

**Comment by felipekm** [comment]
Here is Windows 7 and my screen is 1080p. Actually two screens with 1080p.

**Comment by 3y3** [comment]
Ok. I reproduced your problem.
To solve it, you need to clear localStorage and cache for inspector tab.

**Comment by felipekm** [comment]
Yup, I did it and it works after clear all localStorages keys.
