### ISSUE TITLE
Console truncates long strings

### ISSUE THREAD

**Issue by fetis** [node-inspector/node-inspector#636]
Hello, we're logging HTTP requests in console and view them through node-inspector. But console output truncates long urls. For example
```
RESPONSE widget from /en-us/fooooooooo/bar/widget?view=fooooobar/person/&p... (length: 99) 200
```

I have no idea why it works this way. It makes logging useless sometimes.  Standard Chrome console nether act this way. Is it possible to fix?

**Comment by 3y3** [comment]
Fixed in 0.10.2.
Feel free to reopen this issue, if I'm wrong here.
