### ISSUE TITLE
Runtime.getProperties failed. Error: No scopes

### ISSUE THREAD

**Issue by i5ting** [node-inspector/node-inspector#638]
- mac 10.9.4
- on node v0.12.22
- Node Inspector v0.10.0
- issue

Runtime.getProperties failed.
Error: No scopes

**Comment by 3y3** [comment]
Can you provide some small example of code?

**Comment by mrgamer** [comment]
Also getting that with:
  * windows x64
  * io.js 2.0.0
  * Node Inspector v0.10.0

Will try and provide a more complete report

**Comment by 3y3** [comment]
ping @i5ting

**Comment by mrgamer** [comment]
I am sorry, after cleaning `npm`, `npm-cache` and rebuilding everything with io.js 2.0.1
I could not reproduce this.

I was trying to get a clean environment, free of version conflicts, and .. it made this vanish :-/

**Comment by i5ting** [comment]
@3y3 


my final solution:

- nvm 0.25.1
- node v0.10.38
- Node Inspector v0.10.0

only this can work well

**Comment by mrgamer** [comment]
I am able to reproduce stably a similar error, `Object #-{ Number }# not found`

Here's a full screencast to reproduce it.
![nodeinspector-bug](https://cloud.githubusercontent.com/assets/2657230/8166676/9d82b866-1399-11e5-88a5-170ba525fe65.gif)

Funny detail: if I don't use F8, but click "play" icon with mouse, this does not appear.

**Comment by 3y3** [comment]
@mrgamer , thank you for screencast. I can work with this issue now.

**Comment by i5ting** [comment]
@mrgamer thanks

**Comment by rafis** [comment]
Issue still exists:

```
Runtime.getProperties failed.
Object #99# not found
```

Node.js v6.3.1
Node Inspector v0.12.8
