### ISSUE TITLE
node-debug _mocha fails with "ECONNRESET" on node 0.12.2

### ISSUE THREAD

**Issue by murdockcrc** [node-inspector/node-inspector#640]
Hi,
My system is running nodejs 0.12.2 with node-inspector 0.10. When I run the command "node-debug _mocha", the chrome browser is opened but the debugging sessions immediately crashes with the following error message:

Debugging `_mocha`

Debugger listening on port 5858
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

Just wondering if this is a known issue and if there are any workaround to debug mocha tests with node-debug.

**Comment by 3y3** [comment]
Please try to reproduce this on node-inspector 0.10.1

**Comment by murdockcrc** [comment]
@3y3 it does not crash anymore, thanks for the tip.

**Comment by 3y3** [comment]
Good news!
