### ISSUE TITLE
HeapProfiler.takeHeapSnapshot failed. Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request

### ISSUE THREAD

**Issue by TehNrd** [node-inspector/node-inspector#646]
Using node v0.12.2 with node-inspector v0.10.1 I am unable to perform any type of profiling. The browser opens fine but when I try to Take Snap Heapshot the following error is displayed in the console:

```
HeapProfiler.takeHeapSnapshot failed.
Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request
```

Similar errors also occur for CPU Profile:
```
Profiler.start failed.
Error: Unknown command "Profiler.start" in request
```
...and Record Heap Allocation:
```
HeapProfiler.startTrackingHeapObjects failed.
Error: Unknown command "HeapProfiler.startTrackingHeapObjects" in request
```

I'm not sure where to look to provide more debug/detailed information but if someone can point me in the right direction I can provide more information.

**Comment by 3y3** [comment]
Is this happens in `--debug-brk` mode or in any mode?

I can expect this behavior if you started debugging like this:
`node-debug test.js`
and you tried to take snapshot immediately after browser opening. (In other words you don't press `continue` button in source tab)

**Comment by TehNrd** [comment]
Gosh....yup that was it. Didn't realize it paused on start. Selecting resume script button fixed this issue.

![screen shot 2015-05-20 at 12 54 34 pm](https://cloud.githubusercontent.com/assets/1007085/7731628/aa830584-feef-11e4-9498-aa5f4f9fb63e.png)

**Comment by galblank** [comment]
One more thing I had to do:
1. Attaching to the running process it shows it as running but you need to "pause" and hit "Resume" again.
2. After hitting "Resume" you need to refresh the browser, wait  until the source code comes up and then you can take heap snapshots etc...
This is working on our AWS EC2 Instances.

**Comment by 3y3** [comment]
@galblank , this is actual solution for NI 0.12.2 ?
I'm discouraged by step 1...
