### ISSUE TITLE
Assertion failed is logged for all assertions

### ISSUE THREAD

**Issue by jackquack** [node-inspector/node-inspector#653]
For each and every assertion I make (e.g. ```console.assert(foobar === true, 'foobar is not true')```), I'm seeing a log message that my assertion failed even when the assertion did not fail.

You can see a perfect example of this in the screenshot where it says that ```true``` failed the assertion.

![screen shot 2015-05-25 at 7 34 50 pm](https://cloud.githubusercontent.com/assets/554881/7803104/4eba5890-0315-11e5-807e-a0a3015e51cf.png)
![screen shot 2015-05-25 at 7 35 02 pm](https://cloud.githubusercontent.com/assets/554881/7803105/4ebcdbc4-0315-11e5-87ec-ee1642c99849.png)

**Comment by jackquack** [comment]
This also seems to be causing some major slowness for me. Maybe it's the large amount of logging that happening because of this (though IMHO it isn't that much logging).

Anyway, for now to get around this weird failing assertion business, I have set the assert function to an empty function ```console.assert = function(){};```.

**Comment by 3y3** [comment]
Fixed in 0.10.2.
Feel free to reopen this issue, if I'm wrong here.

**Comment by jackquack** [comment]
Okay thanks! Do you think that your fix addresses the slowness issue? I haven't tested the fix yet.

**Comment by 3y3** [comment]
> Do you think that your fix addresses the slowness issue?

No, there is no fixes for slowness issue. (I need more info about this issue, if it is critical for you)

**Comment by jackquack** [comment]
Looks like it was fixed. It was probably only due to the failing-ish-ness of the assertions.
