### ISSUE TITLE
Verbose logging mode

### ISSUE THREAD

**Issue by jcrben** [node-inspector/node-inspector#666]
Lots of programs have verbose modes which can help debugging and allow for informed bug reports. For example, ssh -vvv (super verbose), or npm set config loglevel={silent to silly}. Node itself has a fair number of logging options. Is there a verbose mode? Would it make sense to have one? 
##

**Comment by 3y3** [comment]
We use `debug` module in node inspector for extended logging.
Are you want something like [this](https://github.com/node-inspector/node-inspector/wiki/Debug-logs)?

**Comment by jcrben** [comment]
Sorry for the delay, I wandered over to WebStorm for my server-side debugging for a bit. This is exactly what I'm looking for, although I can't get it to run. Could you provide an actually running example? I tried:

1. First, I tried the example: `DEBUG=node-inspector* node-debug notify.js`. I received feedback (`Node Inspector is now available from http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
Debugging notify.js`) but when I loaded that up I just got a blank page.
2. I guessed around a bit and tried `DEBUG=node-inspector* node-inspector notify.js` and I was able to get the log, but I'm getting the error: `node-inspector:protocol:devtools backend: {"id":10,"error":"ErrorNotConnected: Error: connect ECONNREFUSED. Is node running with --debug port 5858?"} +2ms`

Also, what do you think about featuring this more prominently, such as the front page or contributing section? I think a reporting issues section in the front-page README which points this out and suggests posting a gist with the log could be helpful.

**Comment by jcrben** [comment]
Not worth looking into this I think... also I lean towards focusing on chrome devtools node debugger https://github.com/node-inspector/node-inspector/issues/977
