### ISSUE TITLE
node-inspector redirects to localhost

### ISSUE THREAD

**Issue by david-knipe-hp** [node-inspector/node-inspector#667]
When I start node-inspector using `./bin/inspector.js --web-port=8092` and then navigate to myserver:8092/debug?port=6677 from a remote machine, it redirects me to http://127.0.0.1:8092/debug?ws=127.0.0.1:8092&port=5858 . This makes remote debugging impossible.

I'm using node v0.10.32, node-inspector 0.10.1. It last worked properly in node-inspector 0.9.2. In 0.10.0 it redirected to [Object object] (issue #625). node-inspector is running in an Ubuntu VM; the client is in Windows 7.

**Comment by 3y3** [comment]
Will be fixed in 0.10.2 or 0.11.0

As workaround you can use:
`./bin/inspector --web-port=8092 --web-host=myserver`
