### ISSUE TITLE
WIn 8 : Node-inspector url https://127.0.0.1:8080/debug?ws=127.0.0.1:8080&port=5858 doesnt work on chrome

### ISSUE THREAD

**Issue by govind22** [node-inspector/node-inspector#674]
I am struggling with an issue for firing up the node inspector url.

I did npm update , npm -g install node-inspector  and everything worked fine

now when I start node-debugger then it says visit https://localhost:8080/debug?ws=localhost:8080&port=5858 to start debugging 

when I visit the url on chrome it says "Webpage is not available"
![nodeinspector](https://cloud.githubusercontent.com/assets/1595233/8116241/bca1e026-1035-11e5-8284-c6c842274614.JPG)

![nodeinspector2](https://cloud.githubusercontent.com/assets/1595233/8116249/c6a1e68e-1035-11e5-8d6b-d22f7eb0c959.JPG)

**Comment by 3y3** [comment]
Have you any internet connection in time when you launch node-inspector?
Or you use it on isolated machine?
Issue can be related with problems in node `dns` module.
I have no other idea here...

**Comment by 3y3** [comment]
Try connect directly to 127.0.0.1 instead of localhost
