### ISSUE TITLE
node-inspector error

### ISSUE THREAD

**Issue by sundyxfan** [node-inspector/node-inspector#678]
Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v0.11.13-darwin-x64/debug.node'   

how to solve？

**Comment by 3y3** [comment]
Have you strict reason to use 0.11.13?

You have some ways to solve this issue:
1. Switch to other node version, which supports prebuild binaries (latest 0.10.*, latest 0.11.*, 0.12.*, 1.*, 2.*)
2. Or install full environment to build native modules [read this article](https://github.com/TooTallNate/node-gyp#installation)

**Comment by jakedsouza** [comment]
Facing a similar issue on Mac OSX 

Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v44-darwin-x64/debug.node'

$ node -v 
v0.12.2
$ node-inspector -v
Node Inspector v0.10.2
$npm -v
2.10.1

**Comment by 3y3** [comment]
@jakedsouza , can you go to this path and check that there is no `node-v44-darwin-x64` folder.
Maybe any other folder exists instead of this one?

**Comment by jakedsouza** [comment]
@3y3, I do not have the ```node-v44-darwin-x64``` folder but I do have a ```node-v43-darwin-x64``` folder 
```
 /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v43-darwin-x64/debug.node 
```

**Comment by 3y3** [comment]
Is it possible what you install node-inspector using iojs 1.* and then update iojs to 2.*?

**Comment by jakedsouza** [comment]
@3y3 I am not using iojs. I uninstalled and reinstalled node-inspector with different versions of node 0.11.xx and 0.12.xx with similar error. 

Switched to ```iojs 2.2.1``` reinstalled node-inspector and the error goes away

**Comment by 3y3** [comment]
I ask because:
- `node-v11-darwin-x64` - for 0.10.*
- `node-v14-darwin-x64` - for 0.12.*
- `node-v43-darwin-x64` - for 1.*
- `node-v44-darwin-x64` - for 2.*

Node Inspector choses automatically which file it should download from amazon S3.

**Comment by jakedsouza** [comment]
So it looks like Node Inspector chose the wrong one for node 0.12. Ill take a look at ```node-pre-gyp```

**Comment by thejones** [comment]
I had this issue as well which may be related to using NVM. NPM install was successful and installed into: 
```/Users/ajones/.nvm/versions/node/v0.12.3/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v14-darwin-x64/debug.node```

Error from node inspector was looking for it at: 
```/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v43-darwin-x64/debug.node ```

Unsure if this is helpful or not just what I noticed when trying a "fresh" install today.

**Comment by tsm91** [comment]
@thejones yeah, i had the same problem this is the step to avoid `nvm reinstall-packages 0.12.5`

install all your global packages manually and everything will work

**Comment by wyattbiker** [comment]
Hi I am having this same problem. Ive reinstalled. But I still get this message:

Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.0/node-v44-darwin-x64/debug.node'

However I only have node-v14-darwin-x64 instead of v44.  How do I fix this? Thanks!

**Comment by rainabba** [comment]
Having a similar issue, but the cause of the error is clear. `\build\debug\v0.4.6` doesn't exist, but `\build\debug\v0.5.2 does`. Why is it looking for 0.4.6?

**Comment by ftcosta** [comment]
Error: Cannot find module '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.2/node-v46-linux-x64/debug.node'

```shell
~ $ node -v
v4.0.0
~ $ node-inspector -v
Node Inspector v0.12.3
~ $ npm -v
2.14.2
```

Quite similar error here.

How to fix it?

**Comment by ivanmanolov90** [comment]
same issue with node -v 4.1.1

**Comment by trevorhutt** [comment]
I found the "node-v46-linux-x64" folder and debug.node file did not exist.  Creating the missing folder and copying the debug.node file from the /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v11-linux-x64 folder into the new "node-v46-linux-x64" has work.

**Comment by derwaldgeist** [comment]
I've installed the latest node 4.1.1 for MacOS, but am only getting the following error messages:
```
Your Node version (v0.10.36) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to v0.11.13 or newer to get full support.
Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v11-darwin-x64/debug.node'
```
Strange thing is that it reports node's version as v.0.10.36, although a node -v shows 4.1.1

**Comment by cold-logic** [comment]
Not sure if this is a totally valid fix but I was able to work around this issue by opening the `/usr/local/lib/node_modules/babel-node-debug/node_modules/v8-debug` in my terminal and running the `npm run install` command. That generated the missing build/debug/... directories and I'm not seeing that error anymore.

**Comment by bunterWolf** [comment]
does not fix the problem for me :(

**Comment by spamguy** [comment]
@cold-logic pointed me in the right direction, though I don't know where `babel-node-debug` came from.

1. Enter `/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler`
2. Run `npm run install`
3. Enter /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug`
4. Run `npm run install`

No errors after that.

**Comment by echorohit** [comment]
I have ```node-v14-linux-x64 folder``` inside 
```/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6 ```

**Comment by echorohit** [comment]
@trevorhutt  error in my case
``` Error: Module version mismatch. Expected 46, got 14. ```

**Comment by ShirajG** [comment]
@spamguy Thanks, that worked perfectly

**Comment by echorohit** [comment]
@ShirajG your node version?

**Comment by nickperkinslondon** [comment]
Thanks @spamguy, that fixed it!

**Comment by brunettdan** [comment]
Thanks @spamguy worked fined for me!
Node v5.0.0
Npm v3.3.7
Node-inspector v0.12.3

**Comment by thiagodebastos** [comment]
Same issue here guys
Node v5.1.0
npm v3.3.12
Node Inspector v0.12.3
@spamguy 's fix didn't seem to do it, in the browser I am still getting:

``` bash
Your Node version (v0.10.36) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to v0.11.13 or newer to get full support.


Error: Cannot find module '/Users/username/.nvm/versions/node/v5.1.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v11-darwin-x64/debug.node'
```

**Comment by jjrasche** [comment]
I've got a work around based on @3y3 and @jakedsouza discussion above. 
Grab the expected files from S3 and add them to the desired location.
for Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.1/node-v11-darwin-x64/debug.node'
1) Get valid file from https://node-inspector.s3.amazonaws.com/debug/v0.5.1/node-v11-darwin-x64.tar.gz
2) decompress and place in /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.1/

when I restarted, I got a similar error for 'node-v11-darwin-x64/profiler.node', used the same process, restarted, and it all appears to be working. First time using the application so take it with a grain of salt.

find whatever node-inspector version you need here https://node-inspector.s3.amazonaws.com/

**Comment by VoidVolker** [comment]
@jjrasche Thanks! Your solution is works for me. XUbuntu 14/16, Fedora 22.

**Comment by ShirajG** [comment]
@echorohit I was using 4.0.0 at the time, but via NVM

**Comment by 3y3** [comment]
Try to install 0.12.5. This version includes prebuilt binaries for all actual node versions from the box.
Feel free to reopen this issue if it still exist.

**Comment by natew** [comment]
I tried installing node-inspector:

```
node-debug --version
Node Inspector v0.12.5
```

Running into this issue:

```
Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v47-darwin-x64/debug.node'
```

Node 5.2.0

**Comment by 3y3** [comment]
@natew , I see that you try to install outdated version of v8-debug. I can't understand how this can happen, but NI 0.12.5 requires `v8-debug` 0.7.0

Maybe `npm cache clean` will be helpful

**Comment by riceian** [comment]
It's a hack but ... worked for me
cd /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug
ln -s v0.7.1 v0.5.0

**Comment by dilongl** [comment]
reinstall node-inspector helpful for me

**Comment by nandofalcao** [comment]
@spamguy Tks!

**Comment by uncledu** [comment]
@spamguy Thanks, it work!
