### ISSUE TITLE
Console hides underscore character

### ISSUE THREAD

**Issue by fetis** [node-inspector/node-inspector#680]
I have value for property named `in_progress` but it shows in console as `in progress`. I spent about an hour to realize that this's console problem and not transformation in my code. Very confusing.

How it looks
![console1](https://cloud.githubusercontent.com/assets/577042/8181209/deac134e-142c-11e5-9f9d-371835f2b45c.PNG)

What really value is
![console2](https://cloud.githubusercontent.com/assets/577042/8181282/594282e6-142d-11e5-87d9-ba69fd3755bc.png)

**Comment by 3y3** [comment]
I think you have `110%` (or other not equal to `100%`) pixel ratio on inspector page.
Play with `ctrl +` and `ctrl -`.

**Comment by fetis** [comment]
I have 125%, on 110% is same. 100% is fine but font is too small.
Is it problem of node-inspector or Chrome itself?

**Comment by 3y3** [comment]
This is problem of Chrome itself
