### ISSUE TITLE
Node Inspector url port issue

### ISSUE THREAD

**Issue by wdbacker** [node-inspector/node-inspector#685]
First of all: my sincere thanks to the whole team for implementing the web notifications feature (issues #566 and #654), great work! Works like a charm!

A small startup issue: when you launch the Node Inspector url, the debug port passed in the url is not taken into account. Can this be fixed easily in the startup code of the Node Inspector UI?

E.g.: if my web port is 8083 and the debug port 5860 and you open the url 
  http://localhost:8083/?port=5860
it redirects with a HTTP 302 response to 
  http://localhost:8083/?ws=localhost:8083&port=5858

Here you see a Chrome network trace clearly showing what's going on:

20319: URL_REQUEST
http://localhost:8083/?port=5860
Start Time: 2015-06-19 09:10:01.009

t=3940 [st=  0] +REQUEST_ALIVE  [dt=313]
t=3941 [st=  1]    URL_REQUEST_DELEGATE  [dt=0]
t=3941 [st=  1]    URL_REQUEST_START_JOB  [dt=0]
                   --> load_flags = 2638848 (BYPASS_DATA_REDUCTION_PROXY | MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                   --> method = "GET"
                   --> priority = "HIGHEST"
                   --> url = "http://localhost:8083/?port=5860"
t=3941 [st=  1]   +URL_REQUEST_START_JOB  [dt=307]
                   --> load_flags = 2638848 (BYPASS_DATA_REDUCTION_PROXY | MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                   --> method = "GET"
                   --> priority = "HIGHEST"
                   --> url = "http://localhost:8083/?port=5860"
t=3941 [st=  1]      URL_REQUEST_DELEGATE  [dt=0]
t=3941 [st=  1]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=3941 [st=  1]      HTTP_CACHE_OPEN_ENTRY  [dt=1]
t=3942 [st=  2]      HTTP_CACHE_ADD_TO_ENTRY  [dt=0]
t=3942 [st=  2]      HTTP_CACHE_READ_INFO  [dt=0]
t=3942 [st=  2]      URL_REQUEST_DELEGATE  [dt=0]
t=3942 [st=  2]     +HTTP_STREAM_REQUEST  [dt=302]
t=4244 [st=304]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                       --> source_dependency = 20322 (HTTP_STREAM_JOB)
t=4244 [st=304]     -HTTP_STREAM_REQUEST
t=4244 [st=304]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=0]
t=4244 [st=304]        HTTP_TRANSACTION_SEND_REQUEST_HEADERS
                       --> GET /?port=5860 HTTP/1.1
                           Host: localhost:8083
                           Connection: keep-alive
                           Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                           User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
                           Referer: http://localhost:8081/ewd/ewdMonitor/index.html
                           Accept-Encoding: gzip, deflate, sdch
                           Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
t=4244 [st=304]     -HTTP_TRANSACTION_SEND_REQUEST
t=4244 [st=304]     +HTTP_TRANSACTION_READ_HEADERS  [dt=3]
t=4244 [st=304]        HTTP_STREAM_PARSER_READ_HEADERS  [dt=3]
t=4247 [st=307]        HTTP_TRANSACTION_READ_RESPONSE_HEADERS
                       --> HTTP/1.1 302 Moved Temporarily
                           X-Powered-By: Express
                           Location: http://localhost:8083/?ws=localhost:8083&port=5858
                           Vary: Accept
                           Content-Type: text/html; charset=utf-8
                           Content-Length: 164
                           Date: Fri, 19 Jun 2015 07:10:01 GMT
                           Connection: keep-alive
t=4247 [st=307]     -HTTP_TRANSACTION_READ_HEADERS
t=4247 [st=307]      HTTP_CACHE_WRITE_INFO  [dt=0]
t=4247 [st=307]      HTTP_CACHE_WRITE_DATA  [dt=0]
t=4247 [st=307]      HTTP_CACHE_WRITE_INFO  [dt=0]
t=4247 [st=307]      URL_REQUEST_DELEGATE  [dt=0]
t=4247 [st=307]     +URL_REQUEST_DELEGATE  [dt=1]
t=4247 [st=307]        DELEGATE_INFO  [dt=1]
                       --> delegate_info = "AsyncResourceHandler"
t=4248 [st=308]     -URL_REQUEST_DELEGATE
t=4248 [st=308]      URL_REQUEST_REDIRECTED
                     --> location = "http://localhost:8083/?ws=localhost:8083&port=5858"
t=4248 [st=308]   -URL_REQUEST_START_JOB
t=4248 [st=308]    URL_REQUEST_DELEGATE  [dt=0]
t=4248 [st=308]    URL_REQUEST_START_JOB  [dt=1]
                   --> load_flags = 2638848 (BYPASS_DATA_REDUCTION_PROXY | MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                   --> method = "GET"
                   --> priority = "HIGHEST"
                   --> url = "http://localhost:8083/?ws=localhost:8083&port=5858"
t=4249 [st=309]   +URL_REQUEST_START_JOB  [dt=3]
                   --> load_flags = 2638848 (BYPASS_DATA_REDUCTION_PROXY | MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                   --> method = "GET"
                   --> priority = "HIGHEST"
                   --> url = "http://localhost:8083/?ws=localhost:8083&port=5858"
t=4249 [st=309]      URL_REQUEST_DELEGATE  [dt=0]
t=4249 [st=309]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=4249 [st=309]      HTTP_CACHE_OPEN_ENTRY  [dt=0]
t=4249 [st=309]      HTTP_CACHE_ADD_TO_ENTRY  [dt=0]
t=4249 [st=309]      HTTP_CACHE_READ_INFO  [dt=0]
t=4249 [st=309]     +HTTP_STREAM_REQUEST  [dt=0]
t=4249 [st=309]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                       --> source_dependency = 20330 (HTTP_STREAM_JOB)
t=4249 [st=309]     -HTTP_STREAM_REQUEST
t=4250 [st=310]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=0]
t=4250 [st=310]        HTTP_TRANSACTION_SEND_REQUEST_HEADERS
                       --> GET /?ws=localhost:8083&port=5858 HTTP/1.1
                           Host: localhost:8083
                           Connection: keep-alive
                           Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                           User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
                           Referer: http://localhost:8081/ewd/ewdMonitor/index.html
                           Accept-Encoding: gzip, deflate, sdch
                           Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
                           If-None-Match: W/"295-1063222368"
                           If-Modified-Since: Tue, 16 Jun 2015 11:59:46 GMT
t=4250 [st=310]     -HTTP_TRANSACTION_SEND_REQUEST
t=4250 [st=310]     +HTTP_TRANSACTION_READ_HEADERS  [dt=2]
t=4250 [st=310]        HTTP_STREAM_PARSER_READ_HEADERS  [dt=2]
t=4252 [st=312]        HTTP_TRANSACTION_READ_RESPONSE_HEADERS
                       --> HTTP/1.1 304 Not Modified
                           X-Powered-By: Express
                           Accept-Ranges: bytes
                           Date: Fri, 19 Jun 2015 07:10:01 GMT
                           Cache-Control: public, max-age=0
                           Last-Modified: Tue, 16 Jun 2015 11:59:46 GMT
                           ETag: W/"295-1063222368"
                           Connection: keep-alive
t=4252 [st=312]     -HTTP_TRANSACTION_READ_HEADERS
t=4252 [st=312]      HTTP_CACHE_WRITE_INFO  [dt=0]
t=4252 [st=312]      URL_REQUEST_DELEGATE  [dt=0]
t=4252 [st=312]   -URL_REQUEST_START_JOB
t=4252 [st=312]    URL_REQUEST_DELEGATE  [dt=1]
t=4253 [st=313]    HTTP_CACHE_READ_DATA  [dt=0]
t=4253 [st=313]    HTTP_CACHE_READ_DATA  [dt=0]
t=4253 [st=313] -REQUEST_ALIVE

**Comment by 3y3** [comment]
@wdbacker , thank you for bug report. I added it to main work line.

**Comment by wdbacker** [comment]
Hi @3by3, I found the cause of the problem in lib/debug_server.js, the debugPort in function debugAction must be set by _getDebuggerPort() instead of setting the port from the config:

```javascript
function debugAction(req, res) {
  if (!req.query.ws) {
    var urlParts = req.headers.host.split(':'),
      //debugPort = this._config.debugPort;
      debugPort = this._getDebuggerPort(req.url);

    var newUrl = buildUrl(urlParts[0], urlParts[1], debugPort, null, this._isHTTPS);
    return res.redirect(newUrl);
  }
  res.sendFile(path.join(WEBROOT, 'inspector.html'));
}
```
