### ISSUE TITLE
Linux / Ubuntu 14.04. Hangs. Browser blank. "Cannot send response - there is no front-end connection."

### ISSUE THREAD

**Issue by tecfu** [node-inspector/node-inspector#697]
### Issue

Terminal 1: 
```
node-inspector
```

Terminal 2
```
node --debug-brk script.js
````

Browser:
```
http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
```
And the browser does nothing. Blank. 

If you are <b>lucky</b>, you'll notice that that node-inspector logs the following message to the console while the browser interface fails to load:

<h3>"Cannot send response - there is no front-end connection."</h3>

You'll search that message on Google, find this issue ticket, and apply the fix you see below.

If you are <b>unlucky</b>, you'll find yourself staring at an empty browser window, waiting for something to happen and observing that nothing does. You'll use nvm to change node versions and upgrade/downgrade chrome or chromium trying to figure out why node-inspector broke. 

### node-inspector versions
- 0.10.0 - 0.11.1 

### OS
- Ubuntu 14.04

### Browsers 
- Chrome Version 43.0.2357.134
- Chrome 34.0.1847.137-1

### See also

http://stackoverflow.com/questions/29929811/node-inspector-doesnt-start

**Comment by simeonpanayotov** [comment]
Another way to fix this is to run node-inspector with the `--no-preload` option. I'm testing this with Node Inspector v0.12.3 and it works.

**Comment by hilarudeens** [comment]
`--no-preload` works for me

**Comment by mk0x9** [comment]
Excuse me, but this doesn't resolve problem. Although `--no-preload` works fine, yeah.
