### ISSUE TITLE
Version > 0.11.0 is slow, has hight cpu for long time while loading node_modules

### ISSUE THREAD

**Issue by chk-** [node-inspector/node-inspector#706]
I have the same issue #699 with 0.11.2 as well as 0.11.1. Also at some point* of loading (node --debug-brk myapp.js) the garbage collector is busy for 90 seconds hitting ~97% cpu, which for that time it's not useable and I must wait. I downgraded to 0.11.0 and encountered no issues on Win7 with node 0.12.7. 
*At this point 20 node_modules related to a webserver (expressjs, socketio, morgan, multer, etc.) have to get loaded.

Also the starting-point (node --debug-brk myapp.js) is not the beginning of myapp.js, instaed it's line 460 of some file named module.js which path I can't determine.

**Comment by 3y3** [comment]
> Also the starting-point (node --debug-brk myapp.js) is not the beginning of myapp.js, instaed it's line 460 of some file named module.js which path I can't determine.

Will be fixed in next release.

> the garbage collector is busy for 90 seconds hitting ~97% cpu

Which `gc` you mean?
1. app
2. node-inspector
3. frontend

**Comment by 3y3** [comment]
How about `node-debug --no-preload myapp.js`?

**Comment by chk-** [comment]
gc of node-inspector profiled by google chrome.

I will feedback about using --no-preload.

**Comment by 3y3** [comment]
Please try also `node-debug --hidden node_modules myapp.js`

**Comment by chk-** [comment]
``node-debug --no-preload myapp.js`` has the same bad behavior, but
``node-debug --hidden node_modules myapp.js`` the app starts fast, like
``node-debug myapp.js`` @v0.11.0 does.

**Comment by 3y3** [comment]
0.11.0 does'n work correctly.
This is a fix that changes behavior to slow (but correct) work - 85ac310a1b7316eb3e42e395d39c2603614453ee

So, `hidden` is correct solution for your situation.

**Comment by chk-** [comment]
But ``hidden`` is not practicable since it doesn't show me the node_modules in the Sources treeview, in which I'm also interested in.
I understand your point of view. From mine there's v0.11.0 I can work with, the later ones not.
