### ISSUE TITLE
Enhancement: node-inspector connecting to a distributed (remote) Node server instance

### ISSUE THREAD

**Issue by ncv-dev** [node-inspector/node-inspector#710]
It would be great if `node-inspector` can be configured to connect to a `Node` server that is running in a remote system.  That is, the developer need not run node-inspector on the same system as the Node server that is to be debugged.  Below diagram illustrates the purpose - 
![node-inspector_accessing_remote_node_server](https://cloud.githubusercontent.com/assets/8929835/8980081/c5007c2a-36cb-11e5-8c46-a7d8b5c18e93.png)

Questions:
* Are there any technical constraints that will not allow for having such a setup with an enhancement in node-inspector?
* Can `node-inspector` take the IP of node server as a parameter and use it in `lib/debugger.js` while initiating a TCP connection:
```javascript
//line: 35
Debugger.prototype._setupConnection = function() {
  //var connection = Net.createConnection(this._port),
  var connection = Net.createConnection(this._port, this._host),
```

**Comment by 3y3** [comment]
I think sometimes about this feature, but this is hard to make it:
1. We collect sources tree using fs. And it isn't good idea to evaluate this code on app side.
2. We inject some features in app using `require`. We can't be sure that on app side was installed expected module.

So, at current time `ScriptManager.js`, `ScriptFileStorage.js` and `InjectorClient.js` are main blockers for this feature - it would be costly to recompose current logic and to maintain new logic.
For example - how to inject console API with new architecture:
1. Create new folder on app side
2. Download from Amazon S3 compiled binaries for `v8-debug` and `v8-profiler` for os used on app side
3. Upload `v8-debug` and `v8-profiler` binaries to app side
4. Some way delete this binaries after unexpected app crashing

**Comment by ncv-dev** [comment]
Thanks for the response.
It indeed looks like a non-trivial task with impact on node-inspector Architecture :worried:
