### ISSUE TITLE
TypeError: Property 'stack' of object Error is not a function

### ISSUE THREAD

**Issue by scarabdesign** [node-inspector/node-inspector#717]
Inspector: v0.12.1,
Node: v0.10.38,
OS: Debian GNU/Linux 7.8 (wheezy)

Looks like there is a call to "stack" property as if it's a function. File VM234. Not sure why the original error is occurring, but the following doesn't give me a usable stack trace.

      function wrapHttpRequests() {
    http.ClientRequest.prototype.onSocket = function(socket) {
      var isUnixSocket = this.socketPath,
          options = null;

      if (!isUnixSocket) {
        options = debug.getFromFrame(1, 'options');

        if (!options || !(options instanceof Object)) {
          console.error(
            'Unexpected state in node-inspector network profiling.\n' +
            'Something wrong with request `options` object in frame #1\n' +
            'Current stackstace:', new Error().stack()
          );
        } else {
          handleHttpRequest.call(this, {
            host: options.host,
            port: options.port,
            path: this.path
          });
        }

        options = null;
      }

      return onSocket.apply(this, arguments);
    };
  }

**Comment by 3y3** [comment]
Omg... I hoped to never enter in this block =(

Can you change this line to correct `new Error().stack`, and provide me final error?

**Comment by scarabdesign** [comment]
Ok, corrected in node-inspector/lib/Injections/NetworkAgent.js 
It happens if I have a break point set while running my code. It pauses on the break just fine, but when I resume it dumps this error in the console:

	Something wrong with request `options` object in frame #1
	eval at WRAPPED_BY_NODE_INSPECTOR (/home/node/nvm/v0.10.38/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:95:15):365 Unexpected state in node-inspector network profiling.

	Current stackstace: Error
	at ClientRequest.http.ClientRequest.onSocket (eval at WRAPPED_BY_NODE_INSPECTOR (/home/node/nvm/v0.10.38/lib/node_modules/node-inspector/node_modules/v8-debug/v8-debug.js:95:15), <anonymous>:368:36)
		at Agent.<anonymous> (http.js:1239:35)
		at Agent.emit (events.js:106:17)
		at Socket.onFree (http.js:1300:10)
		at Socket.emit (events.js:92:17)
		at http.js:1723:14
		at process._tickCallback (node.js:448:13)

**Comment by scarabdesign** [comment]
Also, it may be important to note also that the issue only seems to happen on one of my services, the one that has debugger attached on a master process on 5858 and one worker at 5859.

**Comment by 3y3** [comment]
Please try node-inspector 0.12.2

**Comment by scarabdesign** [comment]
Seems to fix it. Thanks!
