### ISSUE TITLE
A potential global require

### ISSUE THREAD

**Issue by jkrems** [node-inspector/node-inspector#718]
Found while playing around and thought it might be interesting for node-inspector as well: https://github.com/buggerjs/bugger-v8-client/pull/6

**Comment by 3y3** [comment]
@jkrems , thank you for idea. We use the same strategy now, but we are searching a native `require` function in `process.emit` func [link](https://github.com/node-inspector/node-inspector/blob/master/lib/InjectorClient.js#L5-L8)

This strategy has some side effects - we need to pause debugger and filter this break event on NI stage. It is more complicated than your solution - we need to `step out` for find a `require` in previous frame.

So it may be reasonable to update this part with your solution. Can you provide information about compatibility between node versions?

**Comment by jkrems** [comment]
Yep, another advantage of `NativeModule` is that it doesn't pollute the dependency graph (parent/child) of the module you extract `require` from.

So far it's just a "random late-night idea". Didn't fully test it on even one node version. Just wanted to note it down in case I don't get around to it.

**Comment by jkrems** [comment]
After being fully awake and looking up some older code of mine: It looks like it would already be a big improvement for node-inspector to use `process.mainModule.require` when it exists. `process.mainModule` works for all node versions at least back to 0.8 and is available unless the node instance is evaluating (repl, `-e`, `-p`) instead of having an actual entry script.

**Comment by jkrems** [comment]
The [latest code](https://github.com/buggerjs/bugger-v8-client/pull/6/files#diff-3241451967337fddfdf647cd1f81dd91R1) was tested with all combinations of:

* node 0.8, 0.10, 0.12; iojs 1.x, 2.x, 3.x
* `node --eval` and `node some-script.js`
* Running at the time of being called, paused at the time of being called

There's a small gotcha for the last part: When combined with `node --eval`, the solution still has to `suspend` briefly so that the mirror cache is preserved. With an entry script that should never happen.

**Comment by 3y3** [comment]
@jkrems , thank you again for code snippet. I'll use this experience some later - at current time there is some critical features which I need to implement (es6 structures debugging). I keep this issue opened to don't loose this idea.

Now when you implemented this entry point, you may be interested in NI's magic - [v8-debug](https://github.com/node-inspector/v8-debug)
