### ISSUE TITLE
node-inspector debug interface not loading, looking for debug\v0.4.6 for Node 0.12.0

### ISSUE THREAD

**Issue by rainabba** [node-inspector/node-inspector#719]
Running Windows 8.1 Pro

```
\node -v
v0.12.0
\npm -v
2.13.4
\node-inspector -v
Node Inspector v0.12.2
```

When I access the debugger in browser, it fails to load and in console I see:

`...Your Node version (v0.10.36) has a partial support of profiler...`
and
`Error: Cannot find module 'C:\Users\myusername\AppData\Roaming\nvm\v0.12.0\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v11-win32-ia32\debug.node'`

`\build\debug\v0.4.6` doesn't exist, but `\build\debug\v0.5.2` does and it contains `node-v14-win32-ia32`.

During `npm install -g node-inspector` I see: `[v8-debug] Success: "C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.2\node-v14-win32-ia32\debug.node" is installed via remote`

I don't see anything in my environment variables that would confuse things and so far I can't figure out why the reference to 0.4.6 is happening (still researching v8-debug and it's use in node-inspector though).

Issue appears similar to https://github.com/node-inspector/node-inspector/issues/678

**Comment by rainabba** [comment]
After lots of experimenting, I now have: `Error: A dynamic link library (DLL) initialization routine failed.
C:\Users\michael.COMPTEKNET\AppData\Roaming\nvm\v0.12.0\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.2\node-v14-win32-ia32\debug.node` and I do have the `v0.5.2\node-v14-win32-ia32` folder, but I'm running x64 node so I think that makes sense. Am I forced to run 32bit node or do I need to do something to get node-inspector working with x64 node?

I may be entirely off there too because after using nvm to switch to a 32bit release then `npm uninstall -g node-inspector; npm cache clean; npm i -g node-inspector; node-inspector`, I get the same linker error.

**Comment by 3y3** [comment]
So, after `npm uninstall -g node-inspector; npm cache clean; npm i -g node-inspector; node-inspector`

node-inspector was installed for `win32-ia32`? 

Can you also describe how you fix your initial error ?
> ...Your Node version (v0.10.36) has a partial support of profiler...

**Comment by rainabba** [comment]
@3y3 I have `nvm\v0.12.0\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.2\node-v14-win32-ia32\debug.node` and this is provided during the `npm install -g node-inspector` execution. If I `npm uninstall -g node-inspector`, this folder is removed.

Not sure how I got the 0.4.6 reference to change to 0.5.2 for sure, but it seemed to resolve after I created a an 0.4.6 folder manually then used a junction to link the expected filename in that to the existing one in 0.5.2. With the linker error, I quickly deleted that junction and folder (figuring the version difference was the reason for the linker error), but the linker error persists and I'm willing to bet the underlying reason is the same one (what ever that is).

**Comment by rainabba** [comment]
Something just occurred to me and I decided to try in another Chrome profile and in that one, node-inspector loads (though doesn't appear to be attaching). I actually have a handful of profiles so I tried a 3rd and it also had the same issue as the 1st then I tried an incognito session and it ALSO had the issue. If each profile was running either as system admin or not, might that explain this behavior somehow?

**Comment by rainabba** [comment]
In trying to get the debugger to attach, I restarted node-inspector with --no-preload, refreshed the browser and now I'm looking at the same error condition.

```
Your Node version (v0.10.36) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to v0.11.13 or newer to get full support.
Error: A dynamic link library (DLL) initialization routine failed.
C:\Users\myusername\AppData\Roaming\nvm\v0.12.0\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.2\node-v14-win32-ia32\debug.node
Network.loadResourceForFrontend failed.
Error: ENOENT, open 'C:\Program Files (x86)\Adobe\Adobe Creative Cloud\CCLibrary\js\UGLIFY_SOURCE_MAP_TOKEN'
```

I can't imagine how that last error is related, but I don't see how it would end up there otherwise so I'm including it now (it was in the other instances as well).

**Comment by rainabba** [comment]
Also, restarting the incognito session (which by design should remember and retain nothing), the condition persists so it seems that this isn't specific to browser sessions entirely (though maybe a variable in the session has an effect on node-inspector and the issue persists).

**Comment by rainabba** [comment]
I just manually did some cleanup of nvm and updated my system to node 0.12.7 and so far it appears that I've got node-inspector working again.

Before, I it was telling me to use: `http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858`

Not it's telling me to use: `http://127.0.0.1:8080/debug?port=5858`

What does that indicate?

**Comment by rainabba** [comment]
After encountering a similar issue on my laptop, something got me thinking about the npm version which eventually led to me realizing that "npm install -g" uses a different location for each user (including Admin) on Windows and those are independent STILL from the actual NPM install location (which is likely made even more complicated by NVM). By doing `cd C:\Program Files (x86)\nodejs>` then installing `npm install node-inspector -g` there AND uninstalling from the user locations (working from my project directory and doing `npm uninstall -g`, I have things working again, though still the prompt that includes `?ws=127.0.0.1`.

So, I'm up and running again, but it seems with slighting different environments in each case and without a completely clear picture as to why the trouble came about, but it seems to be a version conflict from having different "global" node_modules folders.

**Comment by rainabba** [comment]
Figured out why I was seeing 2 different debugger URLs and this raised another question that's already been asked in another issue (and not answered).

One case is node-inspector 0.7.4 (which can do break-on-uncaught-exceptions-only) and the other is 0.12.2, which cannot; at least not with the same UI approach and I don't see how otherwise.

I think that pretty well explains everything going on with my "issue" and I hope all this helps someone else in the future.
