### ISSUE TITLE
node-inspector crashes when using 'eval()' or 'vm.runInContext()'

### ISSUE THREAD

**Issue by phdunham** [node-inspector/node-inspector#723]
My project runs code inside a VM in Node JS for security reasons. When I use node-inspector on the code inside the VM, node-inspector crashes in a variety of ways. I have created a simple program to show a typical crash using both the vm.runInContext() and the eval() statements.

I am using node v0.12.7 and node-inspector v0.12.2. To reproduce, run node-inspector, run the code below, then step through the code 5 times. On the 5th step, you get the error listed here. If you use the vmCode() function instead of the evalCode() function, it will show the same error.

**Node Inspector command and error dump**
> node-inspector
Node Inspector v0.12.2
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
/usr/local/lib/node_modules/node-inspector/lib/BreakEventHandler.js:60
      this._frontendClient.sendLogToConsole('error', err);
                          ^
TypeError: Cannot read property 'sendLogToConsole' of undefined
    at /usr/local/lib/node_modules/node-inspector/lib/BreakEventHandler.js:60:27
    at BreakEventHandler.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/BreakEventHandler.js:154:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/CallFramesProvider.js:27:11)
    at /usr/local/lib/node_modules/node-inspector/lib/DebuggerClient.js:136:7
    at Object.create.processResponse.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:23:20)
    at Debugger._processResponse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:95:21)
    at Protocol.execute (_debugger.js:137:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)<

**Sample code**
var script = 'function stop() {debugger;}\nstop();\nvar a = 0;\nvar b=a+1;\n';

function evalCode() {
    eval(script);
}

function vmCode() {
    var vm = require('vm'),
        sandbox = vm.createContext(),
        vmScript = new vm.Script(script);
    vmScript.runInContext(sandbox);
}

setTimeout(function() {
    evalCode();
    //vmCode();
}, 5000);

**Comment by navinSing** [comment]
getting this

```

Debugger.setBreakpoint failed.
Error: Not implemented.
```

real blocker for us .. any workarounds.

**Comment by smulikHakipod** [comment]
For me, evalCode() is working fine, but vmCode() is totally ignored. Any updates?
