### ISSUE TITLE
Cannot read property '__inspector_ID__' of undefined

### ISSUE THREAD

**Issue by bobef** [node-inspector/node-inspector#726]
This happens sometimes when I set a breakpoint and run the script in order to reach the breakpoint. But it doesn't reach it but crashes instead.

```
TypeError: Cannot read property '__inspector_ID__' of undefined 
    --> at ClientRequest.handleSocket (/Applications/node/lib/node_modules/node-inspector/lib/Injections/NetworkAgent.js:258:37)
    --> at ClientRequest.Object.defineProperty.value (/Users/bobi/Dev/logging-node/node_modules/Prototype/Function.js:214:14)
        at ClientRequest.g (events.js:199:16)
        at ClientRequest.emit (events.js:129:20)
        at tickOnSocket (_http_client.js:493:7)
        at _http_client.js:504:7
        at process._tickDomainCallback (node.js:381:11)
        at Module.runMain [as _onTimeout] (module.js:503:11)
        at Timer.listOnTimeout (timers.js:119:15)
```

Versions:
OS X 10.10.5
```
↪ npm -v node-inspector
2.11.3
↪ node -v
v0.12.7
```

**Comment by 3y3** [comment]
Looks like an uncompatibility with prototype.js

**Comment by bobef** [comment]
Possibly, but I don't think because of the line in the stack trace: https://github.com/Perennials/prototype-js/blob/master/Function.js#L214

It just replaces the `Function.bind()` with JS version.

**Comment by bobef** [comment]
I think it only happens in this case - node domains and then some error happens inside the on('error') handler for the domain, so it causes infinite "on error" loop and then this problem appears. It doesn't appear most of the time.

**Comment by bobef** [comment]
I commented the custom `Function.bind()` and I don't get this error anymore.
