### ISSUE TITLE
Cannot find module with path 'node-v44-darwin-x64'

### ISSUE THREAD

**Issue by JiaJiaJiang** [node-inspector/node-inspector#737]
Run node-debug with iojs(2.3.4) [mac os]
Then an error printed in chrome:
``````
Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.2/node-v44-darwin-x64/debug.node'
``````

I entered '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.2',only found a directory 'node-v14-darwin-x64'.

The same problem with v8-profile,and in linux too.

**Comment by JiaJiaJiang** [comment]
Image of errors
![image](https://cloud.githubusercontent.com/assets/4150781/9637702/d96bf17a-51d4-11e5-9d56-c90b5dc337bc.png)
the 1st line is the error mentioned above,
the following line are errors that occured after some profiler actions.

**Comment by 3y3** [comment]
Is it possible that you have two node versions installed on your machine?

**Comment by JiaJiaJiang** [comment]
@3y3 does this module support iojs?

**Comment by 3y3** [comment]
Yes, iojs < 3 completely supported

**Comment by JiaJiaJiang** [comment]
@3y3 thank you
