### ISSUE TITLE
node exits randomly

### ISSUE THREAD

**Issue by SEAPUNK** [node-inspector/node-inspector#744]
node-inspector version: `Node Inspector v0.12.3`
node version: `v4.0.0`
OS: `Windows 7 Professional SP1, 32-bit`

For some reason, when I try to take heap snapshots (or finish recording one), if I get unlucky enough, the program (and the debugger) will completely exit, with no further output. What's causing that to happen?

The command I use is `node-debug index.js`

**Comment by 3y3** [comment]
Can you provide small example of code to reproduce this problem?

**Comment by SEAPUNK** [comment]
The code I'm running the debugger on basically calls the API continuously to get data updates from ChannelAdvisor. The majority of the code that runs [is in this library](https://github.com/SEAPUNK/channeladvisor-localdb).

---

I'll see if I can write a program that more-or-less reproduces the issue.

**Comment by SEAPUNK** [comment]
I can't seem to reproduce with code other than mine. I'll look into it, and figure out what might be causing that.

I did notice that during snapshotting, it pauses execution of code, so that might have something to do with it pausing the code in the middle of a web request or a mysql transaction.

**Comment by 3y3** [comment]
Snapshot is a common synchronous operation, I don't think that mysql transaction can be a problem.
Please try to start node-inspector and app in different shells:
First shell
```
node-inspector
```
Second shell
```
node --debug-brk index.js
```

Any new error logs after this operation?

**Comment by SEAPUNK** [comment]
Nope. This is what I did:

1. started node-inspector
2. started the program: `node --debug-brk=5858 index.js`
3. opened up the debugger page
4. pressed the "play" button on the source
5. went to Profiles and started "Record Heap Allocations"
6. while it was doing some web requests via the node-soap library, I pressed the "Stop Record" button, and the program just exited out. No errors, no nothing. node-inspector is still operational.

![](http://puu.sh/kbqUN/4f77b96bdc.png)

**Comment by SEAPUNK** [comment]
...now that I think about it, the other times it exited out were during web requests as well. Maybe that's the problem?

**Comment by SEAPUNK** [comment]
I'll close this issue for now since I am not really pursuing this problem; if someone else is having the same issue, they could open up their own issue.

On a side note, it might have to do with a confirmed node bug, that 3y3 himself posted: https://github.com/nodejs/node/issues/781
