### ISSUE TITLE
v0.5.3/node-v46-linux-x64/debug.node

### ISSUE THREAD

**Issue by QuinDennis** [node-inspector/node-inspector#745]
i'm confused, the latest node version seems to be v0.10.40.   debug.node is in v0.5.3/node-v11-linux-x64, not ...v46-linux...

**Comment by 3y3** [comment]
Are you using nvm?
I think you have two node versions installed on your machine.

**Comment by CoreSoft2** [comment]
I have tried on OSX, docker on centos, it is pointing to 64 bit issue. If you have 64bit versions installed (NPM, node), you are likely to have problems installing node-inspector.

**Comment by 3y3** [comment]
@QuinDennis , v46 is not a version of node. It is an ABI for detecting used V8 version.

**Comment by 3y3** [comment]
Try to install 0.12.5. This version includes prebuilt binaries for all actual node versions from the box.
Feel free to reopen this issue if it still exist.
