### ISSUE TITLE
Installing node-inspector with node 4.x

### ISSUE THREAD

**Issue by Tonallynx** [node-inspector/node-inspector#749]
Hi, I am not able to install node-inspector.  I am not sure if this is the cause, but I just upgraded node to 4 and node-inspector crashes in the browser.  I would post the error message I got in the browser, but since trying to re-install with npm it does not recognize node-inspector, so I don't remember what that error was.  I would appreciate any help.  Here is my error log when trying to npm install:

C:\Users\Arkodeb\Documents\Work\Redfish\RedfishAdmin>npm install -g node-inspector --unsafe-perm

> v8-debug@0.5.4 preinstall C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
>

> v8-profiler@5.3.1 preinstall C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
>

npm WARN optional dep failed, continuing default-browser-id@1.0.2

> utf-8-validate@1.2.1 install C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
 ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

-
C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.0","npm":"2.14.3"})
npm WARN optional dep failed, continuing bufferutil@1.2.1
|
> v8-debug@0.5.4 install C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.4\node-v46-win32-x64\debug.node" is installed via remote

> v8-profiler@5.3.1 install C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64 )  else (node  configure --fallback-to-build --module=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Arkodeb\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.3.1\\node-v46-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\Arkodeb\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.3.1\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arkodeb\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\Arkodeb\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.3.1\node-v46-win32-x64' (1)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector" "--unsafe-perm"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.3.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Arkodeb\Documents\Work\Redfish\RedfishAdmin\npm-debug.log

C:\Users\Arkodeb\Documents\Work\Redfish\RedfishAdmin>

**Comment by jamescostian** [comment]
It clearly says several times:

> Error: Can't find Python executable "python", you can set the PYTHON env variable.

Please see the [node-gyp installation](https://github.com/nodejs/node-gyp#installation). Some other helpful resources include [this comment](https://github.com/nodejs/node-gyp/issues/736#issuecomment-141640079) and [this comment](https://github.com/ncb000gt/node.bcrypt.js/issues/340#issuecomment-141660762). Also, if you install VS, you may not have a C++ compiler, in which case you may get an error about "CL.exe" not being found. To fix that, open VS, create a "New Project", choose something under the Visual C++ category, and then you'll see options to install a C++ compiler (which you should go with). After all of that, you might as well just do a full reboot, and then it should all work like a charm.

**Comment by Tonallynx** [comment]
Hi @jamescostian,

I saw that error and suspected it might be the issue.  I probably should have dug a little deeper before posting an issue on here.  However, I do appreciate your reply.  I followed your steps and after installing python, node-gyp, VS and C++ compiler, I have node inspector up and running again.  Many thanks!
