### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Chris911** [node-inspector/node-inspector#759]
I just updated to node-inspector latest (0.12.3) through grunt-node-inspector (0.3.0) and I'm getting the following error when files are loaded: 

<img width="316" alt="screen shot 2015-10-01 at 5 50 41 pm" src="https://cloud.githubusercontent.com/assets/1198196/10234756/fa2c89e6-6864-11e5-8b51-e4125d58a081.png">
 
I'm also getting the following error when I try to do any kind of profiling: 

<img width="370" alt="screen shot 2015-10-01 at 5 51 45 pm" src="https://cloud.githubusercontent.com/assets/1198196/10234779/1be8309e-6865-11e5-8749-30e7e56986a9.png">

I tried with both node 0.12.7 and node 4.1.1. With node-inspector 0.7.4 everything was fine. I can help debugging if you need more info.

**Comment by 3y3** [comment]
Can you give me simple code example there this happens?

**Comment by 3y3** [comment]
You also can try to use node-inspector from master branch, there exists one commit which can solve this issue.

**Comment by Chris911** [comment]
Actually I think this might be an issue with `grunt-node-inspector` because I just got everything to work by running node-inspector on it's own.
