### ISSUE TITLE
console.log({a:1}) error

### ISSUE THREAD

**Issue by bhevesi** [node-inspector/node-inspector#791]
Hi,

I would be grateful for Your investigation of an error when I use console.log for an object.
See: console.log({a:1})
Thank You!

Node version: v5.2.0
Node Inspector: v0.12.4
Chrome Version 47.0.2526.73 (64-bit)

**Comment by dimonnwc3** [comment]
the same problem.

**Comment by bhevesi** [comment]
Looks this issue related with node.js segmentation fault after console.log (https://github.com/nodejs/node/issues/4261)
Node v5.3.0 has the same problem as well.
I'm going to close this issue and hope the Node.js developers will solve the problem as soon as they can.
