### ISSUE TITLE
After Upgrading to node v5.2.0 I got an debug error

### ISSUE THREAD

**Issue by Attrash-Islam** [node-inspector/node-inspector#797]
Error: Cannot find module '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.0/node-v47-linux-ia32/debug.node'.

I have seen something looks like that. But it doesn't resolved for you.
##

**Comment by abenhamdine** [comment]
nearly the same error for me, for node 5.5.0, on Windows 7 :  

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.5.2\node-v47-win32-x64\debug.node'

**Comment by abenhamdine** [comment]
I just reinstall node-inspector whith npm install -g node-inspector and now everything works perfectly

**Comment by Attrash-Islam** [comment]
No longer relevant for me
