### ISSUE TITLE
debugger ignores breakpoints when running tests with mocha

### ISSUE THREAD

**Issue by ernie58** [node-inspector/node-inspector#810]
I try to debug a mocha test script
I have a breakpoint in my API-controller function (locomotive-js)
I use `npm run test-debug` which translates to:

    node-debug --web-port 3020 --web-host 192.168.255.254 --debug-port 13002  ./node_modules/mocha/bin/mocha -R spec --delay test/flows/*.js

Test are running inside a vagrant box (Debian wheezy) with 
  - node v4.2.5
  - mocha 2.3.4
  - node-inspector v0.12.5

The problem is my breakpoints are completely ignored.

The test is halted on the first line of the script, but when I resume it, additional breakpoints in my code get ignored. I'm sure that code is reached because my console.log statements get executed

Is this a bug are am I doing this the wrong way?

**Comment by 3y3** [comment]
Please try to start `./node_modules/mocha/bin/_mocha` instead of `./node_modules/mocha/bin/mocha`
It may be helpful

**Comment by ernie58** [comment]
Thx @3y3 , it helped!
