### ISSUE TITLE
Extremely slow startup

### ISSUE THREAD

**Issue by tamlyn** [node-inspector/node-inspector#820]
I've used node-inspector in the past but today it's taking 3+ minutes to hit the first line of a file containing only `console.log('hello');`. During this time node is running at 100% on one core and Chrome is showing the dev tools but with no files shown.

I'm using v0.12.5 on node v4.2.6 (installed via nvm) on OS X 10.10.5 on a latest generation Macbook Pro. I've tried uninstalling and reinstalling node-isnpector. I've also tried switching to node v0.12. Same thing. Adding `--no-preload --hidden='node_modules/'` makes no difference. What else can I try?

**Comment by azellsworth** [comment]
Hey Tamlyn! I've noticed the same thing on a couple projects, especially when there are a lot of dependencies (e.g. a packed node_modules folder). 

The `--no-preload` flag on the node-inspector often fixes this, but will sometimes throw the following error when you load the inspector in your browser: `Uncaught SyntaxError: Unexpected end of input` . When this happens, none of your sources will load, making the inspector kind of useless.

You can check for this error when loading node-inspector by opening the dev-tools and looking for this error in the console. For the time being, I've gotten around this by just reloading the page until the error doesn't show up. Haven't been able to identify a source of this issue yet, but it seems to happen a bit randomly.

**Comment by 3y3** [comment]
Should be solved in `node-inspector` 0.12.6
Now `hidden node_modules` will work as expected.

**Comment by tamlyn** [comment]
Instant startup! 👍
