### ISSUE TITLE
Make '--no-preload' argument and 'preload' option consistent

### ISSUE THREAD

**Issue by superclarkk** [node-inspector/node-inspector#829]
Could someone explain why the same nomenclature isn't used for both the node-debug argument and the node-inspector options?  There may be a good reason but, if not, it may be worth changing the "--no-preload" argument to "preload" in order to make it more consistent and intuitive.

**Comment by 3y3** [comment]
You feel free to use `preload=false` everywhere. `--no-` prefix is only syntax sugar from `yargs` arguments parser.

**Comment by superclarkk** [comment]
oh, I see. So, `reload=true` is the default, which is why there is only the need for the `--no-preload` argument (eg. `node-debug --no-preload app`).  Now that I think about it, this seems reasonable. 

Apologies - I'll close this ticket.
