### ISSUE TITLE
Passing function arguments to console.log() breaks debugger

### ISSUE THREAD

**Issue by joshjung** [node-inspector/node-inspector#830]
Not sure if this is an appropriate place to put this bug, but I figured we can move it if needed.

The following code breaks the debugging process completely:

    function someFunction() {
      var args = Array.prototype.slice.call(arguments);
      debugger; // Debugger appropriately stops here
      console.log('Function arguments:', args);
      debugger; // Debugger never reaches this point
    }

The arguments that I was passing look like this:

    [ 'debug',
      'appdynamics not enabled for env: %s',
      'development',
      { _meta: {}, topic: 'app:boot:appdynamics', options: {} } ]

Ironically, the console.log() does work and completes successfully but the debugger refuses to hit any subsequent breakpoints.

    Joshuas-MacBook-Pro:~ jjung$ node -v
    v5.5.0
    Joshuas-MacBook-Pro:~ jjung$ npm -v
    3.3.12
    Joshuas-MacBook-Pro:~ jjung$ node-inspector -v
    Node Inspector v0.12.6

**Comment by 3y3** [comment]
This is a bug of some node versions.
Should be fixed in latest versions of node.
