### ISSUE TITLE
node-inspector lead to memory leakage when use keep-alive http agent.

### ISSUE THREAD

**Issue by Chunlin-Li** [node-inspector/node-inspector#836]
when use http **keep alive agent** to send request, the node inspector's injection of network agent will leads to a **EventEmitter memory leak**. as the running time pass, the heap memory and non-heap memory will still increase, I guess the increase speed depend on the retain memory size of the closure, which hold by the socket connect event listener.

### versions:

* nodejs version: 4.3.1
* node-inspector version: 0.12.7  ( 0.12.5 also has this issue )
* os: ubuntu 15.10 / 14.04, x86_64, core: 4.2.0-30-generic

### **duplication:**

use the following code : [https://gist.github.com/Chunlin-Li/20ca5aa62cafed15d31b](https://gist.github.com/Chunlin-Li/20ca5aa62cafed15d31b)

* start up server.js as normal
* use `node-debug -b=false client.js` run client.js
* observing the output memoury info of client, you will see the increase obviously
* use profile tool dump the heap snapshot, you will find the main increase result from buffer and string.
* following picture show the memory change, and the object area show the path of leakage point.

![screenshot from 2016-03-05 17-25-48](https://cloud.githubusercontent.com/assets/6926291/13546916/59b30496-e2f7-11e5-9fe3-d8a6e2204efd.png)

> I tried use default http.globalAgent (no keepAlive), then the issue not occur.       
> I run code with out node-inspector, the socket in agent sockets pool has no any connect event listener. but use node-inspector, the connect event listener lead the memory leakage.     

-----------------------

### other info

```
(node) warning: possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Console.WRAPPED_BY_NODE_INSPECTOR [as trace] (/home/chunlin/develop/nodev423/lib/node_modules/node-inspector/lib/Injections/ConsoleAgent.js:95:19)
    at Socket.addListener (events.js:239:17)
    at Socket.Readable.on (_stream_readable.js:665:33)
    at Socket.once (events.js:265:8)
    at ClientRequest.handleSocket (/home/chunlin/develop/nodev423/lib/node_modules/node-inspector/lib/Injections/NetworkAgent.js:267:12)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:484:7)
    at onSocketNT (_http_client.js:496:5)
```

**Comment by 3y3** [comment]
Can you test your node-inspector with next modification.

lib/Injections/NetworkAgent.js
```js
  function handleSocket(requestInfo, socket) {
    socket.__inspector_ID__ = socket.__inspector_ID__ || '' + lastConnectionId++;

    this.__inspector_timing__.dnsEnd().connectStart();

    if (socket.writable)
      handleSocketConnect.call(this);
    else
      socket.once('connect', handleSocketConnect.bind(this));

    sendRequestWillBeSent(requestInfo);
  }

  function handleSocketConnect() {
      this.__inspector_timing__.connectEnd().sendStart();
      setImmediate(this.__inspector_timing__.sendEnd.bind(this.__inspector_timing__));
  }
```

**Comment by Chunlin-Li** [comment]
@3y3 Thank you very much! 

I test it with my test case, it fixed the issue. the connect event of socket disappeared. memory usage back to normal.   

So, does it mean the bug will fixed in next release of node-inspector?

**Comment by 3y3** [comment]
> So, does it mean the bug will fixed in next release of node-inspector?

Yes! Thank you for test.
I start to prepare next release.
