### ISSUE TITLE
'node-inspector' is not recognized as an internal or external command operable program or batch file

### ISSUE THREAD

**Issue by dsdsdsdsd** [node-inspector/node-inspector#840]
hello ...

I am new to node ... I am following along in the book: Practical Node.js (Azat Marden).

I installed node-inspector using `npm install -g node-inspector --save` .... it took a couple of minutes but it appears successful.

Then I went to start node-inspector, but got the error message:  > 'node-inspector' is not recognized as an internal or external command operable program or batch file

- any thoughts? ... thanks ...

**Comment by 3y3** [comment]
Are you using nvm?

**Comment by dsdsdsdsd** [comment]
not nvm ... npm ... I understand that nvm is a versioning 'module' (?), but I do not have it installed

**Comment by 3y3** [comment]
Hm... Are you trying to install any other modules globally?
In your case you don't have a directory with globally installed binaries in PATH.
Or maybe `--save` flag affects global installation. That you expect then use `--save` flag in your command?

**Comment by dsdsdsdsd** [comment]
I have installed some others globally ... for instance I installed 'modernizr' globally ... and you're right ... when I attempt to call/start 'modernizr' from the command prompt ($ modernizr), I got the same error ... so it must not be node-inspector, but rather some issue with my nodejs installation ...

- thanks ...

**Comment by dsdsdsdsd** [comment]
I was doing `--save` because I read that it will ensure that the relevant package.json file will be updated with the module id ...
