### ISSUE TITLE
Promise Inspector

### ISSUE THREAD

**Issue by 2color** [node-inspector/node-inspector#845]
Is there any plan to incorporate the Promise Inspector which was recently introduced to chrome developer tools?

If so is there anyway I can help?

**Comment by 3y3** [comment]
This is very hard.
In current time I prepare Node Inspector 1.0-alfa with most part of current DevTools features. (you can watch a progres in `next` branch)
But Promise Inspector and Async Stacktrace is out of scope of this release.

Maybe I see a way to implement this features, but this will be Node Inspector 2.0

**Comment by 2color** [comment]
Thanks for all the great work and efforts.
