### ISSUE TITLE
new console.Console() constructs the wrong thing

### ISSUE THREAD

**Issue by greim** [node-inspector/node-inspector#851]
### Versions

node-inspector version: 0.12.8
node.js version: 4.4.2
OS name and version: OSX 10.11.4

### Description

In my app I'm logging by doing:

```js
const logger = new console.Console(outStream, errStream);
```

Then I export the logger to the rest of my app. This works just fine, until I try to run using node-inspector, and the app crashes because `logger.log()` and `logger.error()` are undefined. Setting a breakpoint, my logger is a `WRAPPED_BY_NODE_INSPECTOR` object which doesn't implement any of the [expected console methods](https://nodejs.org/dist/latest-v4.x/docs/api/console.html).

### Screenshot

![image](https://cloud.githubusercontent.com/assets/317786/14398295/42e0dc70-fda0-11e5-8166-db7a3b7b773d.png)

### Workaround

Doing some tests, I tried this

```js
console.log(console.constructor === console.Console);
// running normally, logs `true`
// running with node-inspector, logs `false`
```

Thus I'm able to workaround the error by changing my code to:

```js
const logger = new console.constructor(outStream, errStream);
```

But it seems hackish, so I thought I'd create an issue.

**Comment by 3y3** [comment]
Would be fixed in next version.
Fix in master branch now.
