### ISSUE TITLE
Connecting to debug port on remote host

### ISSUE THREAD

**Issue by else** [node-inspector/node-inspector#858]
We recently run into a situation where it would have been handy to be able to let node-inspector connect against a remote instead of local host for the debug connection (so no proxying is required). I had a look at the code and it looks like a no-brainer to implement.

Is there a specific reason why this is not possible? If not, would you be willing to accept a PR implementing this feature?

**Comment by 3y3** [comment]
Are you want to start debugged process on one machine and node-inspector on one other?
Or only to connect to remote machine where are placed app and node-inspector?

The second case should work now.

**Comment by else** [comment]
Hi Yury, we are looking for the latter use case: we need to connect to the Debug Port on a remote machine with a locally running node-inspector. Does that make it clear?

**Comment by mdhume** [comment]
@3y3 @else we too would be interested in the former use case - debugging a remote node process while running node-inspector locally. Is that a feature which you are working on already or would be willing to add?

**Comment by fredleger** [comment]
+1

**Comment by markjbyrne81** [comment]
+1

**Comment by lucasyvas** [comment]
+1

**Comment by aleclofabbro** [comment]
+1
That's a feature i would really like! 

I tried with ssh port 5858 forwarding, but node process rejects connection from my local node-inspector

**Comment by hustxiaoc** [comment]
This feature was implemented on `node-inspector@1.1.0`
