### ISSUE TITLE
Install errors with Node v5.11.0

### ISSUE THREAD

**Issue by pei-han** [node-inspector/node-inspector#862]
Environment

Ubuntu 14.04LTS 32bit with 3.19.0-25-generic
node v5.11.0
npm 3.8.6
python 2.7.6
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

Execute "npm install -g node-inspector"

Log

npm WARN lifecycle v8-profiler@5.6.1~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.1 node -e 'process.exit(0)' /usr/npm-global/lib/node_modules/.staging/v8-profiler-82ee13f0
npm WARN lifecycle v8-debug@0.7.3~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.3 node -e 'process.exit(0)' /usr/npm-global/lib/node_modules/.staging/v8-debug-7024e75a
/usr/npm-global/bin/node-inspector -> /usr/npm-global/lib/node_modules/node-inspector/bin/inspector.js
/usr/npm-global/bin/node-debug -> /usr/npm-global/lib/node_modules/node-inspector/bin/node-debug.js

> v8-profiler@5.6.1 install /usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/.node-gyp"
make: Entering directory `/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
make: *** No rule to make target `../.node-gyp/5.6.0/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32/profiler.node" "--module_name=profiler" "--module_path=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32"
gyp ERR! cwd /usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/node-v5.6.0-linux-x86/bin/node /usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32/profiler.node --module_name=profiler --module_path=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/npm-global/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.19.0-25-generic
node-pre-gyp ERR! command "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/npm-global/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v5.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok 
Failed to execute '/usr/node-v5.6.0-linux-x86/bin/node /usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32/profiler.node --module_name=profiler --module_path=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32' (1)
/usr/npm-global/lib
└── (empty)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/node-v5.6.0-linux-x86/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.6.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

**Comment by 3y3** [comment]
If you want to install inspector from root, then use `npm install -g --unsafe-perm node-inspector`

**Comment by pei-han** [comment]
change to root user,then execute below command
npm install -g --unsafe-perm node-inspector

Log


root@ubuntu:~# npm install -g node-inspector --unsafe-perm

> v8-profiler@5.6.1 preinstall /usr/npm-global/lib/node_modules/.staging/v8-profiler-82ee13f0
> node -e 'process.exit(0)'


> v8-debug@0.7.3 preinstall /usr/npm-global/lib/node_modules/.staging/v8-debug-7024e75a
> node -e 'process.exit(0)'

/usr/npm-global/bin/node-inspector -> /usr/npm-global/lib/node_modules/node-inspector/bin/inspector.js
/usr/npm-global/bin/node-debug -> /usr/npm-global/lib/node_modules/node-inspector/bin/node-debug.js

> v8-profiler@5.6.1 install /usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

make: Entering directory `/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
make: g++: Command not found
make: *** [Release/obj.target/profiler/src/profiler.o] Error 127
make: Leaving directory `/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32/profiler.node" "--module_name=profiler" "--module_path=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32"
gyp ERR! cwd /usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/node-v5.6.0-linux-x86/bin/node /usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32/profiler.node --module_name=profiler --module_path=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/npm-global/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.19.0-25-generic
node-pre-gyp ERR! command "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/npm-global/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v5.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok 
Failed to execute '/usr/node-v5.6.0-linux-x86/bin/node /usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32/profiler.node --module_name=profiler --module_path=/usr/npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.1/node-v47-linux-ia32' (1)
/usr/npm-global/lib
└── (empty)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/node-v5.6.0-linux-x86/bin/npm" "install" "-g" "node-inspector" "--unsafe-perm"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.6.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
