### ISSUE TITLE
Install errors with windows 10

### ISSUE THREAD

**Issue by Timer00** [node-inspector/node-inspector#871]
OS: Windows 10.0.10240 Education 64 bits
Node.js: v6.1.0

Execute "npm install -g node-inspector"

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Theo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! path C:\Users\Theo\AppData\Roaming\npm\node_modules\.staging\v8-profiler-ea053891
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\Theo\AppData\Roaming\npm\node_modules\.staging\v8-profiler-ea053891'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Theo\AppData\Roaming\npm\node_modules\.staging\v8-profiler-ea053891\npm-debug.log

> v8-debug@0.7.7 preinstall C:\Users\Theo\AppData\Roaming\npm\node_modules\.staging\v8-debug-f6363cac
> node -e 'process.exit(0)'

C:\Users\Theo\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Theo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.6.3 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 4294963214
npm ERR!
npm ERR! Failed at the v8-profiler@5.6.3 preinstall script 'npm install node-pre-gyp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Theo\Dropbox\Programação e web\Web\JavaScript\Server learning\myApps\console\npm-debug.log
npm ERR! code 1

**Comment by PeterWoodITG** [comment]
I forked node-inspector and set the v8-profiler explicitly to 5.6.1 (from ~5.6.0) 

That fixed my problems in Windows 7. I haven't done extensive debugging, but it appears to be working.

It's here: https://github.com/PeterWoodITG/node-inspector

**Comment by Timer00** [comment]
@PeterWoodITG Sorry to ask, but how do you install this specific version that you have linked?

**Comment by cosmosb** [comment]
@Timer00 npm install git+https://github.com/PeterWoodITG/node-inspector.git -g

**Comment by Timer00** [comment]
Great! It works, thank you @cosmosb and @PeterWoodITG
