### ISSUE TITLE
Error: Cannot find module "node-v46-win32-x64\debug.node"

### ISSUE THREAD

**Issue by oodboo** [node-inspector/node-inspector#879]
OS: Windows 10
node: v4.4.3
node-inspector: v0.12.8
nvm-windows: v1.1.0

```
Error: Cannot find module 'C:\Users\...\AppData\Roaming\npm\node_modules\v8-debug\build
\debug\v0.7.7\node-v46-win32-x64\debug.node'
```

Inside of the folder **v8-debug\build\debug\v0.7.7\**
There is only v47 there is no v46 ... **node-v47-win32-x64**

**Comment by oodboo** [comment]
I have found the issue when nvm is run, v8-debug version will vary depending on currently selected version of node in NVM...
Although it would have be nice if we could somehow choose which environment/s we want to add ...

**Comment by robinxc** [comment]
re install
