### ISSUE TITLE
Debugger does not stop on first line

### ISSUE THREAD

**Issue by adalbertolv** [node-inspector/node-inspector#895]
When using **node-debug --debug-brk app.js** instead of stopping on app.js first line it stops on Line 409 of module.js:

**return compiledWrapper.apply(this.exports, args);**

**Comment by anpaul0615** [comment]
so do i  :((((((

**Comment by bochen2014** [comment]
I think it's the default behaviour. you can always bypass it by explicitly setting the breakpoint at your app.js
shouldn't be a problem ;-)

**Comment by starpit** [comment]
i'm seeing this too. i'm not sure what changed, but now node-inspector always opens to the above-mentioned line in module.js.

perhaps it is worth noting that, when using the CLI debugger (i.e. `node debug app`), the initial breakpoint is in the expected place.

**Comment by hustxiaoc** [comment]
Try `node-inspector@1.1.0` please, should work ok now.
