### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by derakhshanfar** [node-inspector/node-inspector#915]
when i want to debug promise method i get this error ...
node 5.3.0
node-inspector 0.12.8
chrome 52.0
I'm using promises 'blubird'

**Comment by derakhshanfar** [comment]
i still have this problem and i find better libary for debuging node application... iron-node ...its great

**Comment by igorescobar** [comment]
Same here...

**Comment by hustxiaoc** [comment]
The issue has been resolved, try `node-inspector@1.0.0` please!

**Comment by derakhshanfar** [comment]
thank dear @hustxiaoc for your response.. i downgrade my node version to 4.8.1.. but i will check it on 5.3.0
