### ISSUE TITLE
Is node running with --debug port 5858? 

### ISSUE THREAD

**Issue by yipingshui** [node-inspector/node-inspector#92]
Hello dannycoates! 
    when I ran "node-inspector &", it was Ok
    Then "node --debug myapp.js", it said"debugger listening on port 5858", it was Ok too

   Then I opened the chrome15 and input "127.0.0.1:8080", it said "Is node running with --debug port 5858?"
   When I went to script panel, it display "you need to enable debugging before you can use scripts panel "  
    I don't known Why?

```
Thanks!!

my node V0.6.10.
```

**Comment by girishkumar517** [comment]
Hi yipingshui ,

                   Iam also facing same issue,

when I ran "node-inspector &", it was Ok
Then "node --debug myapp.js", it said"debugger listening on port 5858", it was Ok too

Then I opened the chrome15 and input "127.0.0.1:8080", it said "Is node running with --debug port 5858?"

It is giving Error  Connection Refused :Connect in my chrome
