### ISSUE TITLE
No changes since Apr.

### ISSUE THREAD

**Issue by sparkleholic** [node-inspector/node-inspector#930]
@bajtos, @3y3
First of all, thank you for this brilliant project which is very useful for developing node.js app.
But it seems to be no changes over 6 months since Apr.
I'm curious if this repo is not maintained anymore ?

**Comment by bajtos** [comment]
Frankly, I haven't been actively involved with Node Inspector for a year or two by now. All credit and thanks for keeping up with the maintenance goes to @3y3 🙇 

Personally, I use `node --inspect` these days and don't need Node Inspector any more. The debugger was added to Node v6 this summer, see https://github.com/nodejs/node/pull/6792 for more details.

**Comment by sparkleholic** [comment]
@bajtos Thanks for replying.
Yes you're right. I'm also noticed that the recent node v6.4 is supporting `inspect` option. It's really good news. 
But in my case, I'm using the node in the embedded device which is pretty old version(v0.12.0). So unfortunately I can't use `inspect` option there. :(

**Comment by naholyr** [comment]
Plus, `node --inspect` does not include profiles tab :( which is the only reason I use `node-inspector` (daily debugging is done faster with old-fashioned log messages or editor integration).

**Comment by graingert** [comment]
@naholyr node 7 --inspect supports the profiles tab

**Comment by sparkleholic** [comment]
I'd like to use this node-inspector to debug node.js remotely, But the latest code looks it needs to run node-inspector on the same machine running on the local machine.
Even though I submitted a PR (https://github.com/node-inspector/node-inspector/pull/919) regarding this but it just supports only source viewing and break point.
In order to support other tabs like console, profile and etc, it seems like it should inject some modules to the running nodejs process via getting console object.

@bajtos 
In the case that the running nodejs process doesn't have console object because it substitutes for the other, node-inspect cannot inject modules into.
If injection is not available, the node-inspector cannot support forwarding console output, tabs functions like profile/console/etc.
But I'd like to use this project only for view source and setting break-point except other features.
So may I distribute this as another project name ? (maybe `node-inspector-remote` ?)
I just want to do this through forking the old node-inspect branch.
Please take a look at this (https://github.com/sparkleholic/node-inspector/commit/ef554d8ac26826d74e1113ba7cbe14c47ee4fe65)

**Comment by bajtos** [comment]
> @sparkleholic  But I'd like to use this project only for view source and setting break-point except other features. So may I distribute this as another project name ? (maybe node-inspector-remote ?)

Of course! Just make sure to give credit to the original project, this is usually done via `NOTICE` file in project root. See e.g. https://github.com/strongloop/loopback-datasource-juggler/blob/80d2264bc940e764bb8eb0aa3fa12f4ac770fb0d/NOTICE. (Just keep in mind that node-inspector has a different license than the projects mentioned by loopback-datasource-juggler.)

> I just want to do this through forking the old node-inspect branch. Please take a look at this (sparkleholic@ef554d8)

What branch would you like to target? [0.7.4](https://github.com/node-inspector/node-inspector/commit/6b147d968bb7dfd0967665b1d85ee2b64559e999) is the last version I am familiar with. If you like, I can create a long-lived branch `0.7.x` from `v0.7.4` and release `v0.7.5` with your patch. That way you don't have to fork.

**Comment by junilking** [comment]
Thanks @bajtos for the fast response.

> What branch would you like to target? 0.7.4 is the last version I am familiar with. If you like, I can create a long-lived branch 0.7.x from v0.7.4 and release v0.7.5 with your patch. That way you don't have to fork.

`0.7.x branch` would be nice :) 
If you do so, I don't have to fork as you mentioned.
I am going to make a PR into the 0.7.x branch. :)
Thanks for your kind feedback.

**Comment by sparkleholic** [comment]
Thanks @bajtos for the fast response.

> What branch would you like to target? 0.7.4 is the last version I am familiar with. If you like, I can create a long-lived branch 0.7.x from v0.7.4 and release v0.7.5 with your patch. That way you don't have to fork.

`0.7.x branch` would be nice :) 
If you do so, I don't have to fork as you mentioned.
Would you let me know when 0.7.x branch is made so that I can make a PR into it. :)
Thanks for your kind feedback.

**Comment by bajtos** [comment]
@sparkleholic excellent, here is the branch: https://github.com/node-inspector/node-inspector/tree/0.7.x

**Comment by sparkleholic** [comment]
@bajtos I've just made a PR(https://github.com/node-inspector/node-inspector/pull/956) into `0.7.x branch`.
I'll be appreciated if you review it. 
Thanks.
