### ISSUE TITLE
Console will not execute commands, goes to newline instead

### ISSUE THREAD

**Issue by Elliot128** [node-inspector/node-inspector#937]
Has this problem shown up for anyone else? It has been working fine for almost a year and I didn't make any changes to bring about this bug.
Restarting inspector/node doesn't fix. 
Running 0.12.8

Console is effectively broken for me right now. Any solutions?

**Comment by ac9** [comment]
This is a duplicate of https://github.com/node-inspector/node-inspector/issues/903

**Comment by iamfrontender** [comment]
Look for workaround at #942

**Comment by a7madgamal** [comment]
someone close this issue to focus on #903

**Comment by hustxiaoc** [comment]
Resolved in https://github.com/node-inspector/node-inspector/commit/841ffc11f00d1c76b54c73480bef45fdbe89d52d
