### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lovemybb** [node-inspector/node-inspector#948]
![image](https://cloud.githubusercontent.com/assets/5569015/20201160/df9dfa98-a7f0-11e6-891b-9fce5fb58af6.png)
this is a bug.

![image](https://cloud.githubusercontent.com/assets/5569015/20201267/a92ec6da-a7f1-11e6-9bc6-0661dc16f355.png)

**Comment by venkateshilango7** [comment]
#905 
#907
#928
#931

**Comment by hustxiaoc** [comment]
The issue has been resolved, try `node-inspector@1.0.0` please!
