### ISSUE TITLE
TypeError: Cannot read property 'ref' of undefined

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [node-inspector/node-inspector#949]
Node v6.9.1
Windows 10 x64

app.js:
```javascript
var i = 0;

setInterval(function () {
  console.log(i++);
}, 1000);
```

cmd:
```
C:\localhost\taxi>node-debug app.js

Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `app.js`

Debugger listening on [::]:5858
C:\Users\my\AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111
      cb(error, NM[0].ref);
                     ^

TypeError: Cannot read property 'ref' of undefined
    at InjectorClient.<anonymous> (C:\Users\my\AppData\Roaming\npm\node_modules\node-inspector\lib\InjectorClient.js:111:
22)
    at C:\Users\my\AppData\Roaming\npm\node_modules\node-inspector\lib\DebuggerClient.js:121:7
    at Object.value (C:\Users\my\AppData\Roaming\npm\node_modules\node-inspector\lib\callback.js:23:20)
    at Debugger._processResponse (C:\Users\my\AppData\Roaming\npm\node_modules\node-inspector\lib\debugger.js:95:21)
    at Protocol.execute (_debugger.js:121:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
```

**Comment by jamesjjk** [comment]
+1

**Comment by StreetStrider** [comment]
I'm using `node@4`, have the same issue.

**Comment by uMaxmaxmaximus** [comment]
Node v6.5 have the same error.

**Comment by EricFortin** [comment]
Me too with 6.9.1 on Linux.

**Comment by Tony-Rafferty-LogicNow** [comment]
Same with 6.9.1 on windows

**Comment by sunilw** [comment]
Also getting this with 6.9.1 on Linux.

**Comment by harihar** [comment]
6.9.1 in mac - same issue

**Comment by harihar** [comment]
Anyone has any info on this issue? It seems to be affecting many people.

**Comment by GeorgeChackungal** [comment]
Same here. Node 6.5

**Comment by goodmanlu** [comment]
same

**Comment by br14** [comment]
This looks the same as [#905](https://github.com/node-inspector/node-inspector/issues/905)

That issue thread has a couple of suggestions for "commenting out" the offending code, though the impact of that action isn't clear. Several posts suggest debugging can continue.

Doesn't look as though this module is being maintained regularly. Unless I misread the history there have been no commits since April.

**Comment by gpresland** [comment]
Same issue. Windows 10, x64, Node v6.9.1, node-inspector v 0.12.8.

**Comment by nwwells** [comment]
This is fixed in the PR #914

**Comment by borislemke** [comment]
Works with `5.4.1` but I need `6+` for ES6 in my express app. Not essential but would be very helpful if this worked.

**Comment by DevWurm** [comment]
Same issue with `6.9.2` on Linux

**Comment by davidgatti** [comment]
Just installed v0.12.8, and I have this issue.

**Comment by roysG** [comment]
Any update?

**Comment by yaacovk** [comment]
When you install node-inspector locally to you project this problem is soled.

**Comment by dublinus** [comment]
I get the same error message, even when I install locally and run with `node_modules/node-inspector/bin/node-debug.js app.js`.

**Comment by mujicadiazr** [comment]
Windows 10 x64
Node v6.10.0
The same error!

**Comment by hustxiaoc** [comment]
try this https://github.com/node-inspector/node-inspector/pull/983

**Comment by tryer3000** [comment]
```bash
➜  ~ git:(frontdev) ✗ npm list -g --depth 0 | grep node-inspector
├── node-inspector@1.0.0
```
Ubuntu 16.04
Node v6.10.0
