### ISSUE TITLE
How to run node-inspector along with nodemon to enable live reload?

### ISSUE THREAD

**Issue by wzup** [node-inspector/node-inspector#958]
Doesn't work in my Windows 10 Pro 64. Do you have any standard default way of integration?

`node-inspector` is running ok, but doesn't display anything in Devtool. A screenshot:

![127 0 0 1_8088__port 5859 - google chrome 2016-12-10 18 32 30](https://cloud.githubusercontent.com/assets/3880497/21072730/5d73cb6e-bf07-11e6-98dc-cb9749760152.png)

My steps how I start them both:
1. At first I start `node-inspector` in a separate terminal window:
```
$ node-inspector
Node Inspector v0.12.8
Visit http://127.0.0.1:8088/?port=5859 to start debugging.
```
2. Then I start `nodemon` with `--debug` option in a separate terminal window:
```
$ nodemon --debug index.js
[nodemon] 1.9.1
[nodemon] reading config C:\Users\user\app\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage C:\Users\user\app\node_modules/**/* routes/___*.js routes/___*.html
[nodemon] watching: *.*
[nodemon] watching extensions: js,dust,html,css,scss,rb,json,htpasswd
[nodemon] starting `node --debug index.js`
[nodemon] child pid: 11008
[nodemon] watching 3 files
Debugger listening on [::]:5858
```

3. Then I open UI for `node-inspector` in Chrome `http://127.0.0.1:8088/?port=5859`. 
And there is nothing in Chrome console. Devtools are empty, see a screenshot above.

My config for `nodemon`:
```
{
    "restartable": "rs",
    "verbose": true,
    "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*"
    },
    "ignore": ["routes/___*.js", "routes/___*.html"],
    "debug": true,
    "ext": "js dust html css scss rb json"
}
```

Config for `node-inspector`:
```
{
    "debug-port": 5859,
    "web-port": 8088,
    "debug-brk": true,
    "save-live-edit": true,
    "preload": false,
    "hidden": ["\\test\\.js$", "node_modules\\"]
}
```

**Comment by wzup** [comment]
Solved it

**Comment by necevil** [comment]
@wzup How did you get this working? About to try to dockerize the same situation and can use all the help I can get.  Any tips / suggestions are much appreciated.

**Comment by guynimni382** [comment]
@wzup how did you solve it?
