### ISSUE TITLE
Console doesn't work in node-inspector browser UI. How to enable? [SOLVED]

### ISSUE THREAD

**Issue by wzup** [node-inspector/node-inspector#959]
SOLVED here https://github.com/node-inspector/node-inspector/issues/951#issuecomment-262441472

----------------------------------------------

Here is how to reproduce. The simplest example possible.

1. Filename is `index.js` and its contents:
```
'use strict';

debugger;
let a = 10;
```

2. Run `node-debug` against the file.
```
$ node-debug index.js
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `index.js`

Debugger listening on [::]:5858
```

3. It opens UI in Chrome and the execution is stopped on `debugger` line.
Set a watch variable `process` in a `Watch Expression` section. As you can see, it is possible to examine it easily here. But only here, in `Watch Expression` section.

![process_index js - google chrome 2016-12-11 13 17 07](https://cloud.githubusercontent.com/assets/3880497/21078290/85517116-bfa4-11e6-83b9-050cc0f6ac02.png)

4. Now try to examine `process` variable in console. It doesn't work. You can type a variable, but hitting `[Enter]` key doesn't reveal `process` variable. It just adds new lines:

![process_index js - google chrome 2016-12-11 13 25 46](https://cloud.githubusercontent.com/assets/3880497/21078317/9a10768c-bfa5-11e6-9397-6cee36ec1844.png)

What behavior is this? How to make it work?

**Comment by Jameskmonger** [comment]
How did you solve this @wzup ?

**Comment by elranu** [comment]
yes. Any way to solve this issue? @wzup @Jameskmonger
