### ISSUE TITLE
How to completely uninstall node-inspector?  What am I missing?

### ISSUE THREAD

**Issue by mpint** [node-inspector/node-inspector#962]
Hello,

I'm trying to move my Node v7.x application away from node-inspector but it won't go away.  I've taken the following steps.

```
npm uninstall -g node-inspector
remove any instances of node-inspector from application's package.json
npm cache clean
rm .node-inspectorrc
```

I've killed every instance of node-inspector I'm aware exists, yet my project still tries to install it when I `npm i`, and I'm getting the common error that everyone seems to be having:

```> v8-debug@0.7.7 install /Users/michael/Code/web-seraph/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp)
```

Anyone know how to stop node-inspector from installing itself?  What am I missing?

**Comment by mariusc23** [comment]
Is it listed in the project's `package.json`? It could also be a dependency of some other module.

Try `npm ls` and see where it's coming from.
