### ISSUE TITLE
Unable install on mac OS

### ISSUE THREAD

**Issue by maheshambiga** [node-inspector/node-inspector#966]
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.3.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/mambig/.node-gyp/7.3.0/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was
      not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mambig/.node-gyp/7.3.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was
      not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mambig/.node-gyp/7.3.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was
      not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mambig/.node-gyp/7.3.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.

**Comment by kibbled** [comment]
Same error here: macOS Sierra 10.12.2 (16C67) with Node version v7.4.0, NPM v4.0.5 & 4.1.1

**Comment by mlarcher** [comment]
anyone found a way around this issue yet ?

**Comment by kibbled** [comment]
I later realized that this project is no longer maintained by the guys who started it. Sounds like people are using other solutions now.

**Comment by bhouser** [comment]
I have the same problem on OSX 10.11.6

**Comment by rmakarov94** [comment]
Try downgrade node version to 6x
```
n lts
```
that's work for me

**Comment by lfx** [comment]
My workaround is to use Visual Studio Code, built in debugger works flawlessly. 
Tutorial - https://hansrwindhoff.wordpress.com/2015/05/05/debugging-task-runner-tasks-like-gulp-with-visual-studio-code-editordebugger/ 
Just `"program"` path should be from `$(which grunt)`

**Comment by hustxiaoc** [comment]
Try `node-inspector@1.0.0` please.

**Comment by kibbled** [comment]
I can confirm that this now installs on Mac without specifying the version. Thanks guys

`npm install -g node-inspector`
