### ISSUE TITLE
Undefined `ref` property

### ISSUE THREAD

**Issue by gmahomarf** [node-inspector/node-inspector#968]
node-inspector version: 0.12.8
node version: 6.9.1
OS: Windows 10 x64

See code at https://github.com/node-inspector/node-inspector/blob/master/lib/InjectorClient.js#L108-L111

```javascript
if (!NM.length)
   error = new Error('No NativeModule in target scope');

cb(error, NM[0].ref);
```
if `NM.length` is zero, `NM[0]` is undefined and node-inspector crashes with `TypeError: Cannot read property 'ref' of undefined`.

**Comment by SunilWang** [comment]
Me too.

**Comment by onagiba** [comment]
I also get this error:
- node-inspector version: 0.12.8
- node version: 6.9.3
- OS: Windows 10 x64

**Comment by Corey600** [comment]
also get this error.
I think it's same as #949 .
here is a PR https://github.com/node-inspector/node-inspector/pull/914
but it is still open.

**Comment by biluochun** [comment]
+1

**Comment by aschulz01** [comment]
+1

**Comment by jobe451** [comment]
+1

**Comment by bmeritter** [comment]
when you see `Cannot read property 'ref' of undefined` , just modify 
``` 
if (!NM.length){
    error = new Error('No NativeModule in target scope');
    return cb(error);
}

cb(error, NM[0].ref);
```
 to 
```
if (!NM.length){
    error = new Error('No NativeModule in target scope');
    return cb(error);
}
if (NM.length > 0) {
 cb(error, NM[0].ref);
}
```
then the problem will be solve .

**Comment by stigrv** [comment]
+1

**Comment by jukben** [comment]
+1

macOS
node lts

**Comment by looptrader** [comment]
same problem here on windows 10

**Comment by langjt** [comment]
+1

**Comment by gwalls** [comment]
+1

**Comment by QiaoyuanMaxDeng** [comment]
+1

**Comment by junchaotalk** [comment]
+1

**Comment by mujicadiazr** [comment]
+1

**Comment by jonnyt886** [comment]
Upgrade to Node Inspector 0.12.10 and this is fixed. For some reason I needed to do `rm -r node_modules/node-inspector && npm install`, otherwise it wouldn't pick the new version up.

**Comment by sillypencil** [comment]
also get this error:
node-inspector version: 0.12.10
node version: 6.9.5
OS: Windows 10 x64
