### ISSUE TITLE
Return key just adds newlines in watch or console windows 

### ISSUE THREAD

**Issue by JeffML** [node-inspector/node-inspector#970]
version 0.12.8, Mac OS X Yosemite

Return key in watch expressions just adds a newline in the variable name pane. If I click outside the pane, then the variable is accepted and I get a value.

In the console, same behavior except clicking outside the console window doesn't help; I am unable to evaluate anything in the console.

**Comment by gabmontes** [comment]
@JeffML this is a duplicate of #903.
