### ISSUE TITLE
[TypeError: Cannot read property 'toString' of undefined]

### ISSUE THREAD

**Issue by adam-gregory** [node-inspector/node-inspector#971]
I get the error:

sudo node ./node_modules/.bin/sequelize db:migrate

Sequelize [Node: 5.10.0, CLI: 2.5.1, ORM: 3.30.0]

Loaded configuration file "config/config.json".
Using environment "development".
== 20170126130223-create-scan: migrating =======
**[TypeError: Cannot read property 'toString' of undefined]**
scan.js:
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Scan = sequelize.define('Scan', {
    ScanDate: DataTypes.NOW,
  }, {
    classMethods: {
      associate: function(models) {
            Scan.belongsTo(models.Employee);
            Scan.belongsTo(models.Scan);
            Scan.belongsTo(models.Operation);
            Scan.belongsTo(models.Project);
            Scan.BelongsTo(models.ProjCategories);
        }
    }
  });
  return Scan;
};

migration script (###-create-scan.js):

'use strict';
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('Scans', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      ScanDate: {
        type: Sequelize.DATETIME
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: function(queryInterface, Sequelize) {
    return queryInterface.dropTable('Scans');
  }
};

**Comment by Premier** [comment]
What is the solution?
