### ISSUE TITLE
Point people to Chrome Devtools node debugger?

### ISSUE THREAD

**Issue by jcrben** [node-inspector/node-inspector#974]
Development of this seems to be a constant struggle. Every time I've used it, I've given up after facing bugs. There are significant issues reported right now, e.g. [Unable install on mac OS](https://github.com/node-inspector/node-inspector/issues/966) and [Cannot Install node-inspector in Windows 10](https://github.com/node-inspector/node-inspector/issues/965).

As of node `v6.3.0`, Chrome Devtools can debug node. See [Debugging Node.js with Chrome DevTools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.g9zxav79h).

Perhaps it's time to point people to the Chrome Devtools debugger and retire this project?

I also use the Jetbrains Webstorm debugger. I'm not sure what others exist.

**Comment by liquidbrains** [comment]
Chrome DevTools and WebStorm debugger might nice alternatives, but neither of those can show me the network requests that is made by the NodeJS server (i.e. the missing Neworks tab).  I had so much hope for [DevTools](https://github.com/Jam3/devtool) but it doesn't support it either.

**Comment by snowinferno** [comment]
I've found the `network` tab feature from node-inspector invaluable. I use it frequently when something stops working because an upstream service changed their response schema without notice.

I haven't found any IDE, including the v6 Chrome DevTools debugging, that includes the network details.
