### ISSUE TITLE
Is this project still relevant/maintained?

### ISSUE THREAD

**Issue by marcbachmann** [node-inspector/node-inspector#977]
Now that there's `node --inspect`,  do you still plan to maintain this tool?
I'm seeing a lot of confused people because everybody is talking about `node --inspect` but new people accidentally check out `node-inspector`, which is a completely different tool and has a few issues.

So what's the current state?
It would be nice to have a deprecation messagein the readme and maybe a link to a tutorial with `node --inspect`. e.g. https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.jtswxc8y7

**Comment by frankcortes** [comment]
@marcbachmann Since most of the smart TV providers are using this tool for their browsers and they won´t update their node versions (so we won´t be able to use `node --inspect`), this is the only way that people who develop with TVs can debug properly (the alternative is weinre, which is a really old-fashioned tool in these times).

For these reasons, I think that this project is still relevant.

**Comment by mckoss** [comment]
It might be helpful to do detection of the node version - and if --inspect is supported, print a deprecation warning to the console.

**Comment by tylik1** [comment]
Have the same question. This is the best tool available to debug node apps. Would be good to get some feedback, from people who developed this addon. The main problem is that i was able to make it work properly only on node version >= 4 && < 5

**Comment by hustxiaoc** [comment]
@tylik1  It supports node6 and node7 now, please try `node-inspector@1.0.0`

**Comment by Muzietto** [comment]
node --inspect is an alpha-version. It is still way behind node-inspector. I do wish this project to keep going.
And please can any expert contributor have a look at [issue 993](https://github.com/node-inspector/node-inspector/issues/993)?

**Comment by hustxiaoc** [comment]
OK, Is this project still relevant/maintained?  The answer is YES.
