### ISSUE TITLE
In node5.6.0, cannot find module

### ISSUE THREAD

**Issue by ougwen1235** [node-inspector/node-inspector#984]
I follow the following steps:

1. node inspcetor
2. node --debug-brk myJs

When I open the url on the browser,an error occurred:  
Error: Cannot find module '/Users/ougwen1235/.nvm/versions/node/v5.6.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v47-darwin-x64/debug.node'

**Comment by hustxiaoc** [comment]
Please reinstall it again.
