### ISSUE TITLE
Error: No NativeModule in target scope

### ISSUE THREAD

**Issue by whitesnow9291** [node-inspector/node-inspector#985]
I build Expressjs project using express-generator npm plugin.
so it start up bin/www first.
I installed node-inspector correctly and run "node-debug bin/www"
It opens "http://127.0.0.1:8080/?port=5858" automatically and load all code files I created.
But there is one error like the title of issue.
**Error: No NativeModule in target scope**
What am I missing?

**Comment by 823639792** [comment]
+1

**Comment by hustxiaoc** [comment]
try this https://github.com/node-inspector/node-inspector/pull/983

**Comment by GuoChen-WHU** [comment]
+1

**Comment by LukerSpringtree** [comment]
+1

**Comment by melaniaandrisan** [comment]
+1

**Comment by zuchuanzhang** [comment]
+1

**Comment by taoyangaiai** [comment]
I use v6.10.1 still has the issue

**Comment by hustxiaoc** [comment]
Try `node-inspector@1.0.0` please.
