### ISSUE TITLE
How to debug and step into the code "module.exports = function(router) {}" ?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [node-inspector/node-inspector#989]
I execute the command "node --debug-brk src/middleware/permissionHandler.js &", and the command "node-inspector &", then I access it using "http://101.37.36.41:8080/?port=5858". Then, I can find the "permissionHandler.js" file.
Next, I open another tab and access formio "http://101.37.36.41:3005/". But, when I debug the permissionHandler.js, the cursor always skip the code "module.exports = function(router) {}".
So, when the code "module.exports = function(router) {}" in permissionHandler.js file will be called
 and how to debug it? Could you pls give me some suggestions? Thanks!
![d7c875f4-0e3f-11e7-8c0a-2ce54e004bd1](https://cloud.githubusercontent.com/assets/25890017/24138035/8fc9e0e6-0e51-11e7-90c7-d44fe5335e0c.png)

**Comment by hustxiaoc** [comment]
The code `module.exports = function(router) {}`  is a assignment express and the function is not called at the frame, so there is nothing to step into.
