### ISSUE TITLE
Debugger not break at beginning when use --debug-brk

### ISSUE THREAD

**Issue by PrinC** [node-inspector/node-inspector#993]
Node version 7.8.0
node-inspector version 1.0.0

When I use --debug-brk, with web debugger open,  js continue executing .
If I don't open node-inspector,  js executing will pause when using --debug-brk option

**Comment by PrinC** [comment]
When I open node inspector web interface, console will report error with "Error: Debugger: Failed to resolve value by handle, ' #131# not found"

**Comment by Muzietto** [comment]
Same as you, with node 6.9.4. It just started a couple of days ago. 
In my case the failed handle value is #3#

**Comment by Muzietto** [comment]
If I completely kill the node.js cmd window and start a new one, then node-inspector 99% of the times works perfectly __for une run__.
This means that I have to kill the cmd window after each debugging run.

**Comment by Muzietto** [comment]
Similar thing with intellij IDEA. __The first time__ I start a npm script containing a `node-debug --debug-brk` instruction, node-inspector works fine.
After that node-inspector again gives me the  "Error: Debugger: Failed to resolve value by handle, ' #3# not found" error.
But if I restart IDEA, the first run is gonna be OK.

**Comment by Muzietto** [comment]
When an I get an error "Error: Debugger: Failed to resolve value by handle, ' #3# not found", I obviously kill the Chrome window with the red upper-right button.

- Most of the times, the node.js cmd window does not take notice, and I have to kill the running node process with a double CTRL-C; in those cases I know that node-inspector will fail at the next attempt.
- A few times, when I kill the Chrome window, the cmd window writes: "Error: This socket has been ended by the other party" and terminates my node app. __In this case, the next run with node-inspector will show no error__.

**Comment by Muzietto** [comment]
__This problem is slowing down my development and has the highest priority in my agenda.
If any expert committer wants to take care of it, I am ready to give my full attention in providing testcases and trying solutions.__

**Comment by hustxiaoc** [comment]
Sorry for the trouble, I'll fix it ASAP!

**Comment by Muzietto** [comment]
__Great!!!__ If you need any more detail, just drop a note here.
Thank you.

**Comment by hustxiaoc** [comment]
@Muzietto that's very nice of you, could you please check if this pr[https://github.com/node-inspector/node-inspector/pull/994] works ok with you?

**Comment by Muzietto** [comment]
__Major improvement__, but still not 100% solved in my case:

- error "Error: Debugger: Failed to resolve value by handle, ' #3# not found" has disappeared
- instruction `--debug-brk` is still ignored, and I have to put a `debugger` instruction manually in my code
- after stopping at the `debugger` instruction, the debugger works flawlessly

I can live with that for the time being :-)

**Comment by Muzietto** [comment]
I have copied manually the 4 files (except .gitignore) you modified into my node_modules/node-inspector/lib directory.

**Comment by hustxiaoc** [comment]
Can you show me a litter bit demo code ?

**Comment by hustxiaoc** [comment]
@Muzietto `node-inspector@1.0.1` was just released, thanks for your reporting.

**Comment by Muzietto** [comment]
I confirm that the flag `--debug-brk` is ignored in both use cases that I have. I must place an explicit `debugger `instruction in the code, and that stops the execution.
From that moment on, the debugger works perfectly.

**Comment by Muzietto** [comment]
First use case is a plain server-side node.js app started from the command line. I cannot share the code, unfortunately. Are there specific aspects of the application that could trigger this misbehaviour?

**Comment by Muzietto** [comment]
Second use case is **using grunt to start mocha**. Command line is `node-debug --debug-brk C:\Users\MyUser\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt simplemocha`.
Also in this case I put a `debugger `instruction at the start of the test and things work out fine.
I noticed that in this second scenario, I see regularly the text:

    Runtime.getProperties failed.
    Object #-1# not found
    spec.js:34 

printed in the console.

**Comment by hustxiaoc** [comment]
Thanks for the detail , I've reproduced the issue now.

**Comment by PrinC** [comment]
In my case, stale chrome version accounts for this problem.
My chrome version is 51.x, everything works fine when I upgrade to 57.x.

**Comment by Muzietto** [comment]
@PrinC - lucky you. I am Chrome 57.0.2987.133 and still experience the issue.
Moreover, this issue popped up about one week ago out of the blue, and maybe it was some automatic Chrome update thing that indeed triggered it :-)
Who knows?

**Comment by hustxiaoc** [comment]
Turns out that when you launch your app with command `node-debug --debug-brk`, node-inspector will transform it into `node-debug --debug-brk=port` and that will cause the wrong detection of whether you're running it with `--debug-brk`. 

This pr will fix it. https://github.com/node-inspector/node-inspector/pull/997

**Comment by hustxiaoc** [comment]
`node-inspector@1.1.0`

**Comment by Muzietto** [comment]
I confirm that upgrade to 1.1.0 solves completely every issue.
Superb work, @hustxiaoc !! Thank you...
