### ISSUE TITLE
Question : Does it use chrome's dev tools or it has its own HTML/CSS ?

### ISSUE THREAD

**Issue by gs-akhan** [node-inspector/node-inspector#996]
Hi,
My question is does it uses the chrome tools built by Google. Or you guyz have built it grounds up that looks exact same as chrome's dev tools.

Thanks

**Comment by hustxiaoc** [comment]
The front end is based on chromium dev tools. http://src.chromium.org/blink/branches/chromium

**Comment by gs-akhan** [comment]
Cool. Thanks
